### ISSUE TITLE
Google Play requires app updates to target API 29 starting from August

### ISSUE THREAD

**Issue by tcitworld** [wallabag/android-app#1024]

**Comment by di72nn** [comment]
Are you sure? [This page](https://developer.android.com/distribute/play-policies) says that the requirement for **updates** is not due till November.

Anyway, we'd better release 2.4.0 with `targetSdkVersion 28` before that.
2.4.0 has enough changes already, so testing the update of `targetSdkVersion` should be done separately.

**Comment by tcitworld** [comment]
I must have misread their warning when published beta 5, it indeed makes more sense that way.
