### ISSUE TITLE
Problem to connect to a wallabag server using https with port 8443

### ISSUE THREAD

**Issue by emiliogonzalezjunior** [wallabag/android-app#1058]
# Issue details

### Duplicate?
Have you searched the issues of this repository if your issue is already known? yes

### Actual behaviour
I insert the address of my server in the wallabag android app https://wallabag.mydomain.com:8443/ but the app ignore the port (8443) and try https://wallabag.mydomain.com/ with the standard https port (443) instead which is blocked by my isp. I had use the port 8443 to access the wallabag server from my browser and also connected the wallabag firefox add-on with success, the problem look to be related only with the android app. The problem seems to be related to the use of the https://, when i use my ip adress with http, the app respect the port indication (6500 in this case)

## Expected behaviour
When I specify a port in my https:// address it should be used

# Steps to reproduce the issue
1. open the app 
2. go to connection page in settings
3. use a https address with a different port (8443 in my case)

# Environment details
- **wallabag app version**: 2.4.0
- **wallabag app installation source** (e.g. Gplay, F-Droid, manual): F-Droid (but I also had try the google play version)
- **Android OS version**: Android 10
- **Android ROM** (e.g. stock, LineageOS, SlimRom,…): One UI 2.5
- **Android hardware**: Galaxy S10e
- **wallabag server version**: 2.3.8
- **Do you have Two-Factor-Authentication enabled?**: no

# Logs
Omitted, but can submit if required.

# Your experience with wallabag Android app
Have you had any luck using wallabag Android app before? (Sometimes we get tired of reading bug reports all day and a lil' positive end note does wonders)
The experience, beside this problem, has been great.

**Comment by di72nn** [comment]
> I insert the address of my server in the wallabag android app

Do you use the "connection wizard" (preferred) or manual configuration?

> but the app ignore the port (8443) and try https://wallabag.mydomain.com/ with the standard https port (443) instead

Is that an assumption or did you get that data from logs?

This may be similar to #911 (and probably some other issues).
@emiliogonzalezjunior run `curl  -I https://<your instance address>` and check the `Location` header in the output.

**Comment by emiliogonzalezjunior** [comment]
> 
> Do you use the "connection wizard" (preferred) or manual configuration?
> 
I had test with booth "connection wizard" and manual.


> > but the app ignore the port (8443) and try https://wallabag.mydomain.com/ with the standard https port (443) instead
> 
> Is that an assumption or did you get that data from logs?
> 
Its is an assumption because I receive this following message when I tryed:

![Screenshot_20200919-092105_wallabag_1](https://user-images.githubusercontent.com/19764039/93667445-4cc2ee00-fa5c-11ea-8732-a169ed1f2507.jpg)


> This may be similar to #911 (and probably some other issues).
> @emiliogonzalezjunior run `curl -I https://<your instance address>` and check the `Location` header in the output.

I had try curl with booth https://wallabag.mydomaim.com and https://wallabag.mydomaim.com:8443

With https://wallabag.mydomaim.com curls fails and give the following message:
`curl: (60) SSL certificate problem: self signed certificate
More details here: https://curl.haxx.se/docs/sslcerts.html`
`curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above`

With https://wallabag.mydomaim.com:8443 it works and I receive the following location:
`location: https://wallabag.mydomain.com/login`

**Comment by di72nn** [comment]
> With https://wallabag.mydomaim.com:8443 it works and I receive the following location:
> `location: https://wallabag.mydomain.com/login`

Well, there you go. It should contain port in this redirection. It's a matter of server configuration. I can't help with this, but someone else probably can. You can also search issues in this repo - there were some problems like that.

**Comment by emiliogonzalezjunior** [comment]
I cant find any place in the docker setup where a can force the login page to use the port 8443. I Already set the enviroment `-e SYMFONY__ENV__DOMAIN_NAME=` to https://wallabag.mydomain.com:8443/ 

I also doesn't find a similar isse to my in the repository, are you referring to the wallabag/android or the wallabag/wallabag server one?

**Comment by emiliogonzalezjunior** [comment]
Nevermind, I was able to solve the problem by adding `proxy_set_header Host $host:8443;` to the `location / {}` part of the wallabag.subdomain.conf file.
