### ISSUE TITLE
Copy original link in clipboard

### ISSUE THREAD

**Issue by tcitworld** [wallabag/android-app#107]

**Comment by JyotiDubey** [comment]
Can I get more clarity on this feature?

**Comment by tcitworld** [comment]
Use javascript in order to copy the original link of the article inside the clipboard.

**Comment by JyotiDubey** [comment]
I have just downloaded the wallabag application for android but I have no
clue as to what all information to be filled in the setting page. Please do
the needful.


Regards
Jyoti

**Comment by tcitworld** [comment]
This has nothing to do here. Please open a ticket on http://support.wallabag.org

**Comment by di72nn** [comment]
That's actually does not require JavaScript.

**Comment by tcitworld** [comment]
Sorry, I didn't even realize on which repo I was.
