### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by tcitworld** [wallabag/android-app#108]
For reading at night

**Comment by tcitworld** [comment]
cc @Caliandroid for this one

**Comment by Caliandroid** [comment]
Done:  https://github.com/wallabag/android-app/commit/b1591558213f3e036defe7e332fe2a3542e0e88f

**Comment by Strubbl** [comment]
Isn't this already implemented? Okay, maybe not in the About dialog, but when reading articles. Can be closed?

**Comment by tcitworld** [comment]
Yup. The About dialog style can be done easily with https://github.com/mikepenz/AboutLibraries/wiki/HOWTO:-Style.

Closing here.
