### ISSUE TITLE
error during delete

### ISSUE THREAD

**Issue by password123123123** [wallabag/android-app#1102]
# Issue details
Got an error with blink sound in notification.
### Duplicate?
No
### Actual behaviour
Got an error message after I tries to delete one of saved pages.

### Expected behaviour
- Item deleted

# Steps to reproduce the issue
1. Select post with long press
2. Choose "Delete"
3. 

# Environment details
- **wallabag app version**: 
2.4.1
- **wallabag app installation source** (e.g. Gplay, F-Droid, manual)
F-droid 
- **Android OS version**: 
10, Lineage
- **Android ROM** (e.g. stock, LineageOS, SlimRom,…): 
Lineage

--------- beginning of main
11-22 21:16:00.060 17517 17517 D SettingsFragment: onStop() started
11-22 21:16:00.060 17517 17517 D SettingsFragment: applyChanges() started
11-22 21:24:50.358 17517 17541 I AdrenoGLES: QUALCOMM build                   : f2ab992, I401605978b
11-22 21:24:50.358 17517 17541 I AdrenoGLES: Build Date                       : 09/28/19
11-22 21:24:50.358 17517 17541 I AdrenoGLES: OpenGL ES Shader Compiler Version: EV031.27.05.01
11-22 21:24:50.358 17517 17541 I AdrenoGLES: Local Branch                     : 
11-22 21:24:50.358 17517 17541 I AdrenoGLES: Remote Branch                    : 
11-22 21:24:50.358 17517 17541 I AdrenoGLES: Remote Branch                    : 
11-22 21:24:50.358 17517 17541 I AdrenoGLES: Reconstruct Branch               : 
11-22 21:24:50.358 17517 17541 I AdrenoGLES: Build Config                     : S L 8.0.11 AArch64
11-22 21:24:50.366 17517 17541 I AdrenoGLES: PFP: 0x005ff112, ME: 0x005ff066
11-22 21:24:50.423 17517 17517 D SettingsFragment: onStart() started
11-22 21:24:50.423 17517 17517 D SettingsFragment: resetChanges() started
11-22 21:25:04.384 17517 17517 D SettingsFragment: onPreferenceChange(key: misc.handleHttpScheme, newValue: true)
11-22 21:25:06.749 17517 18089 E DatabaseUtils: Writing exception to parcel
11-22 21:25:06.749 17517 18089 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading fr.gaulupeau.apps.Poche.utils.WallabagFileProvider uri content://fr.gaulupeau.apps.InThePoche.fileprovider/wallabag_files/logcat_20201122_212505.txt from pid=19481, uid=1000 requires the provider be exported, or grantUriPermission()
11-22 21:25:06.749 17517 18089 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:729)
11-22 21:25:06.749 17517 18089 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:602)
11-22 21:25:06.749 17517 18089 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:231)
11-22 21:25:06.749 17517 18089 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:104)
11-22 21:25:06.749 17517 18089 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1021)
11-22 21:25:06.749 17517 18089 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:994)
11-22 21:25:17.847 17517 17517 D SettingsFragment: onStop() started
11-22 21:25:17.848 17517 17517 D SettingsFragment: applyChanges() started
11-22 21:25:21.309 17517 17541 I AdrenoGLES: QUALCOMM build                   : f2ab992, I401605978b
11-22 21:25:21.309 17517 17541 I AdrenoGLES: Build Date                       : 09/28/19
11-22 21:25:21.309 17517 17541 I AdrenoGLES: OpenGL ES Shader Compiler Version: EV031.27.05.01
11-22 21:25:21.309 17517 17541 I AdrenoGLES: Local Branch                     : 
11-22 21:25:21.309 17517 17541 I AdrenoGLES: Remote Branch                    : 
11-22 21:25:21.309 17517 17541 I AdrenoGLES: Remote Branch                    : 
11-22 21:25:21.309 17517 17541 I AdrenoGLES: Reconstruct Branch               : 
11-22 21:25:21.309 17517 17541 I AdrenoGLES: Build Config                     : S L 8.0.11 AArch64
11-22 21:25:21.315 17517 17541 I AdrenoGLES: PFP: 0x005ff112, ME: 0x005ff066
11-22 21:25:21.351 17517 17517 D SettingsFragment: onStart() started
11-22 21:25:21.351 17517 17517 D SettingsFragment: resetChanges() started

**Comment by di72nn** [comment]
> Got an error message after I tries to delete one of saved pages.

Do you get an error notification? If so, there should be an option to copy its content.

Also, which server version are you using?

**Comment by password123123123** [comment]
I alredy copied a message to bugreport. I use https://framabag.org as a server.


23 лист. 2020, 12:40 з notifications@github.com:

**Comment by di72nn** [comment]
[Framabag's issue](https://github.com/wallabag/android-app/issues/1076#issuecomment-708970634).
