### ISSUE TITLE
Time Reading Estimation

### ISSUE THREAD

**Issue by tcitworld** [wallabag/android-app#111]
As wallabag does.

**Comment by tcitworld** [comment]
It's really hard to calculate all times when showing the list of articles (too many entries, too much work to strip tags, count words, etc.), so it must be done when articles are fetched for the first time and then stored.

**Comment by tcitworld** [comment]
Okay. If it's calculated when entries are fetched, it's still taking ages. So for now, I will only display it from inside article view. It will be fetched from server when API will be here.

**Comment by di72nn** [comment]
Checked out `estimatedreadingtime` branch. Calculations are awfully long for UI thread. The only two ways I see to implement it right now are either:
* get it from server (add it to feeds, if possible),
or
* calculate it in a low-priority background thread (only while lists are foreground, for example) and **save the value in local DB**.

The first way is definitely preferred, but requires server-side update.

**Comment by tcitworld** [comment]
I didn't realised it was taking so much time when displaying an article, but I admit I didn't test on huge content articles. It is indeed quite bothering, even on my relatively powerful phone.

> get it from server (add it to feeds, if possible)

wallabag v2.0 and it's API provide it.

> calculate it in a low-priority background thread (only while lists are foreground, for example) and save the value in local DB.

This can be done too, yes.

**Comment by di72nn** [comment]
Reading estimation time can actually be added to 1.x server feeds with one line `$newItem->addElement('estimatedTime', Tools::getReadingTime($entry['content']));` (though, I was hoping that number was stored in DB, not calculated every time -_- ).
Is 1.x branch still accepting changes like that?

Client-side code can easily support that element as optional - doesn't require server to update.

**Comment by tcitworld** [comment]
> (though, I was hoping that number was stored in DB, not calculated every time -_- ).

Yeah, we do it like this in v2.

>  Is 1.x branch still accepting changes like that?

We would really rather not have to do it. I think I better postpone this feature for v2.

**Comment by tcitworld** [comment]
Now shown through content.
