### ISSUE TITLE
No cached images are displayed in the webview of the read article activity

### ISSUE THREAD

**Issue by Strubbl** [wallabag/android-app#1117]
# Issue details

### Duplicate?
Have you searched the issues of this repository if your issue is already known? yes/

### Actual behaviour
No cached images are displayed in the article's view

### Expected behaviour
the images shall be loaded from the /storage and displayed in the article view

# Steps to reproduce the issue
1. turn on image caching
2. open any article which has images inside
3. see a white rectangle instead of the image

# Environment details
- **wallabag app version**: current master commit 7230559376576b30ff861fc313fb527418a1f609
- **wallabag app installation source** (e.g. Gplay, F-Droid, manual): manual
- **Android OS version**: 10
- **Android ROM** (e.g. stock, LineageOS, SlimRom,…): stock
- **Android hardware**: samsung s9
- **wallabag server version**: 2.4.0
- **Do you have Two-Factor-Authentication enabled?**: no

**Comment by Strubbl** [comment]
The issue is also reproducible on another device with wallabag installed from Gplay.

**Comment by di72nn** [comment]
Seems to be working on an emulator.

Anything interesting in the logs?

Do you know have any idea when it started?

**Comment by Strubbl** [comment]
I am not sure if it is since the official latest wallabag server release or the latest official android update. 
Is it possible that since we target a newer Android SDK version a more restricted external storage file access is implemented? From the logs it looks like the app is replacing the image paths with the correct /storage paths and the paths are accessible via adb shell and have file size > 0. 

When i switch to online loading of the pictures, every image is displayed.

So my gut feeling is some access right to read files from /storage is missing. I haven't had the time yet to dig into this more to prove if my gut feeling is right.

**Comment by di72nn** [comment]
Did you mean Android 11? Images are not displayed on an Android 11 emulator.

**Comment by Strubbl** [comment]
> Did you mean Android 11? Images are not displayed on an Android 11 emulator.

No. Both devices show 10 as Android version.

**Comment by di72nn** [comment]
I guess Samsung changed the default earlier.

**Comment by Strubbl** [comment]
Thank you for the fix. :+1:

**Comment by di72nn** [comment]
Sure, thanks for reporting!
