### ISSUE TITLE
Add the possibility to connect when 2FA is enabled on the server

### ISSUE THREAD

**Issue by Eliesemoule** [wallabag/android-app#1123]
# Issue details

### Actual behaviour
- I can't connect to Wallabag server when 2FA is activated

# Environment details
- **wallabag app version**: 2.4.2
- **wallabag app installation source** (e.g. Gplay, F-Droid, manual): Google Play Store
- **Android OS version**: 11
- **Android ROM** (e.g. stock, LineageOS, SlimRom,…): Stock
- **Android hardware**: Pixel 2
- **wallabag server version**: 2.4.0
- **Do you have Two-Factor-Authentication enabled?**: yes

# Your experience with wallabag Android app
Login works fine when 2FA is not activated

**Comment by di72nn** [comment]
#359.
