### ISSUE TITLE
Wallabag Service Not Found - can login on web

### ISSUE THREAD

**Issue by prashantsengar** [wallabag/android-app#1131]
# Issue details
While trying to login using the Wallabag android app, I get the error "wallabag service not found -- check URL". On the other hand, I am able to login to the web portal, but the app cannot login.

### Duplicate?
Have you searched the issues of this repository if your issue is already known? yes. But the issue is quite old and was apparently resolved in a newer version. #744 is the closest.

### Actual behaviour
- Cannot log into Wallabag using the Android app, works with browsers

### Expected behaviour
- Should be able to login with Android app as well

# Steps to reproduce the issue
1. Try to login using the app, enter host, username and password
2. Get the error

# Environment details
- **wallabag app version**: 2.4.1
- **wallabag app installation source** F-droid
- **Android OS version**: 10
- **Android ROM** (e.g. stock, LineageOS, SlimRom,…): ColorOS
- **Android hardware**: Realme 6i
- **wallabag server version**: 2.4.1
- **Do you have Two-Factor-Authentication enabled?**: No

# Logs
## wallabag server
Please paste relevant wallabag server logs here (from file `<wallabag>/var/logs/prod.log`):
no relevant log

# Your experience with wallabag Android app
Have you had any luck using wallabag Android app before? (Sometimes we get tired of reading bug reports all day and a lil' positive end note does wonders)

I used the app a few years ago and it was working fine then, same hosting and similar configuration.

**Comment by di72nn** [comment]
Check [this](https://github.com/wallabag/android-app/issues/997#issuecomment-641100325).

**Comment by starsareintherose** [comment]
I have the same problem, I use nginx to proxy the website. I still can't connect

> Check [this](https://github.com/wallabag/android-app/issues/997#issuecomment-641100325).

**Comment by di72nn** [comment]
No response in regards to the `curl -I` test.
