### ISSUE TITLE
[Feature request] Jump to a random article

### ISSUE THREAD

**Issue by ngosang** [wallabag/android-app#1138]
Add a button in the "tree dots" or in the menu to jump to a random article.
This feature is already implemented in the Web UI.

![image](https://user-images.githubusercontent.com/10577978/110254918-8ac3b800-7f91-11eb-926d-4904528109ad.png)

**Comment by di72nn** [comment]
There's an "open random article" item in the "three dots" menu. That was one of the first things I contributed to this app :-)
