### ISSUE TITLE
Updated quote style

### ISSUE THREAD

**Issue by creywood** [wallabag/android-app#1141]
Hi, I have some draft changes to the quote style making them closer to the style on the Wallabag web service.

eg. From ...

![image](https://user-images.githubusercontent.com/31988069/111925828-738ed980-8afe-11eb-9be0-fbde912b125b.png)

To ...

![image](https://user-images.githubusercontent.com/31988069/111927217-172eb880-8b04-11eb-96fb-a824b408704e.png)

Is that of interest? I can send through a PR. `pre` blocks are unchanged.

**Comment by di72nn** [comment]
Hi, thanks!

I, for one, like the suggested change.
@ngosang you did a quotes-related PR, what do you think?

**Comment by creywood** [comment]
I should have mentioned that I'm suggesting the change as it wasn't immediately obvious to me what the quote blocks were. Aligning up with Wallabag web's perhaps more conventional style seemed like a reasonable approach :slightly_smiling_face:

**Comment by ngosang** [comment]
I think it's a good idea. Please, open the PR. Just remember to test all the themes. Thank you!

**Comment by creywood** [comment]
Great, thanks, PR created. Only tested on the single device thus far.
