### ISSUE TITLE
"Unknown error: Connection reset" when connecting to Wallabag Docker behind Traefik

### ISSUE THREAD

**Issue by sethsimmons** [wallabag/android-app#1150]
# Issue details

### Duplicate?
Yes:

https://github.com/wallabag/android-app/issues/997
https://github.com/wallabag/android-app/issues/911

### Actual behaviour
- Android app gives "Unknown error: Connection reset" when attempting to connect, but web behaves properly.

### Expected behaviour
- Android app should be able to login/autofill properly.

# Steps to reproduce the issue
1. Run Wallabag via Docker Compose with Traefik SSL redirection
  a. Relevant Traefik configs
  b. 
  ```56     labels:
 57       - "traefik.enable=true"
 58       - "traefik.http.routers.wallabag.rule=Host(`${WALLABAG_HOSTNAME}`)"
 59       - "traefik.http.routers.wallabag.middlewares=wallabag"
 60       - "traefik.http.routers.wallabag.entrypoints=websecure"
 61       - "traefik.http.routers.wallabag.tls.certresolver=selfhostedservices"
 64       - "traefik.http.middlewares.wallabag.headers.customRequestHeaders.X-Forwarded-Proto=https"
 ```
2. Validate that web login works properly
3. Attempt to login/connect via the Android app

# Environment details
- **wallabag app version**: 2.4.2
- **wallabag app installation source** (e.g. Gplay, F-Droid, manual): F-Droid
- **Android OS version**: 11
- **Android ROM** (e.g. stock, LineageOS, SlimRom,…): CalyxOS
- **Android hardware**: Pixel 4A
- **wallabag server version**: wallabag/wallabag:latest (Docker)
- **Do you have Two-Factor-Authentication enabled?**: no

# Logs
## wallabag server
Please paste relevant wallabag server logs here (from file `<wallabag>/var/logs/prod.log`):

n/a

## Web server
Please paste relevant web server logs (e.g. from nginx, Apache, …) here:

```
wallabag        | 172.29.0.2 - - [07/Apr/2021:00:47:28 +0000] "GET / HTTP/1.1" 302 215 "-" "okhttp/4.9.0"
wallabag        | 172.29.0.2 - - [07/Apr/2021:00:47:29 +0000] "GET / HTTP/1.1" 302 215 "-" "okhttp/4.9.0"
```

Curl showing redirect to http for some reason:

```
curl -I https://wallabag.domain.com
HTTP/2 302
cache-control: max-age=0, must-revalidate, private
content-type: text/html; charset=UTF-8
date: Wed, 07 Apr 2021 00:47:55 GMT
expires: Wed, 07 Apr 2021 00:47:55 GMT
location: http://wallabag.domain.com/login
server: nginx
set-cookie: PHPSESSID=6004cd91853f8a9abffeda383e60874c; path=/; HttpOnly
```

# Your experience with wallabag Android app
Have absolutely loved it in the past, just can't seem to get it working behind Traefik instead of local NGINX!

**Comment by sethsimmons** [comment]
Note that I have also tried practically every configuration variation I could find, including:

https://github.com/wallabag/docker/issues/77#issuecomment-460080724
https://github.com/wallabag/docker/issues/77#issuecomment-467981907
https://florianfranke.dev/posts/2018/09/self-hosted-wallabag-using-docker/
https://www.reddit.com/r/selfhosted/comments/kb5jdz/selfhosters_running_wallabag_via_docker_what_does/gfeq0yz?utm_source=share&utm_medium=web2x&context=3
https://www.reddit.com/r/selfhosted/comments/kb5jdz/selfhosters_running_wallabag_via_docker_what_does/gff59pc?utm_source=share&utm_medium=web2x&context=3

None of these corrected the issue.

**Comment by contrun** [comment]
I can confirm this is still a problem.

**Comment by pilzandreas** [comment]
Same issues with my setup - andoird-app wont work while web-app does.
My guess is, that the android-app connects to ip:port while the webapp uses domain:port .
The traefik setup I run forwards wallabag.mydomain.com to the contrainer wallabag is running.
However the traefik rule is the request must ask wallabag.mydomain.com - if it asks xxx.xxx.xxx.xx (ip) - traefik wont forward.
So a possible solution could be to open a specific second port on the main domain/ip (not subdomain) and forward all requests of that port to the wallabag container.

On the otherhand - if that guess is right, the app should use the url for requests instead of the vanilla ip.

**Comment by di72nn** [comment]
You should start with doing [the location header check](https://github.com/wallabag/android-app/issues/997#issuecomment-641100325).

If it's not the cause, the Android app logs connection related info if you run a debug build.

**Comment by sethsimmons** [comment]
> You should start with doing [the location header check](https://github.com/wallabag/android-app/issues/997#issuecomment-641100325).
> 
> If it's not the cause, the Android app logs connection related info if you run a debug build.

I've already posted the output of that in the issue's description, it's HTTP despite that not being what is set in the environment variables:

WALLABAG_HOSTNAME=wallabag.domain.com
WALLABAG_URL=https://wallabag.domain.com

**Comment by di72nn** [comment]
> I've already posted the output of that in the issue's description

It was addressed to the other posters, not you @sethsimmons. In your case it's a server-side issue (confirmed by the `curl` output), should probably be dealt with at [wallabag/docker](https://github.com/wallabag/docker/). Sorry, I can't help with this problem.

> I can confirm this is still a problem.

@contrun create a separate issue, provide details pertaining to **your** situation. [Check](https://github.com/wallabag/android-app/issues/997#issuecomment-641100325) that it's not the same **server-side issue** first.

@pilzandreas the app doesn't use "the vanilla ip". Just [check the header](https://github.com/wallabag/android-app/issues/997#issuecomment-641100325), will you? If it's not it, create a separate issue.

Keeping this issue open have proven to be unhelpful.
