### ISSUE TITLE
Improve bagging / saving to fix missing content

### ISSUE THREAD

**Issue by lenowac** [wallabag/android-app#1169]
First of all, thank you to the awesome people working on this nice app. <3

Sometimes, when saving articles on mobile, wallabag doesn't get the content right, but other reading modes (firefox (desktop & mobile), telegram, edge) or readers (pocket) do. 

I encountered this with various sites, but never noted them. I'll start a list now:

- taz.de  

Does anyone know how to improve this? Or where I could start looking into it?

Best regards, lenowac

**Comment by Strubbl** [comment]
I am not sure if i get your issue right. Does this only happen when using the app? If you save the same article with the help of the wallabag web application, do you have the same issue?

**Comment by di72nn** [comment]
I assume it's about poor fetching.

@lenowac [have a look at this](https://doc.wallabag.org/en/user/errors_during_fetching.html#content-is-not-what-i-wanted-andor-is-incomplete).
