### ISSUE TITLE
Allow custom text selection actions in Android 11

### ISSUE THREAD

**Issue by scubajeff** [wallabag/android-app#1176]
After version 11, Android changes package visibility behavior, to allow other apps, like translator, to add action when user select text in wallabag, please add the following to wallabag's manifest:
```
<queries>
 <intent>
   <action android:name="android.intent.action.PROCESS_TEXT" />
   <data android:mimeType="text/plain" />
 </intent>
</queries>
```
Please refer to https://developer.android.com/training/package-visibility/use-cases#custom-text-selection-actions

**Comment by di72nn** [comment]
Thanks!
