### ISSUE TITLE
Instagram links are broken when saved to wallabag

### ISSUE THREAD

**Issue by abudden** [wallabag/android-app#1201]
# Issue details

### Duplicate?
Have you searched the issues of this repository if your issue is already known? yes

### Actual behaviour
- Tell us what happens

Go into the instagram app, click on the three dots in the top-right of a post and click "Share Via".  Select wallabag.  What used to happen (this seems to have stopped working for me in the last few says) is that the shared link was saved in wallabag.  What actually happens is that link gets changed to https://www.instagram.com/accounts/login/ regardless of which post was shared.

### Expected behaviour
- Tell us what should happen

It should save the original link, not change it to something else.  This worked until very recently.  If you turn on the "Show a dialog when bagging" option, you see the original link appear and then after a second or two it changes to "Login Instagram" - at which point the original link is lost.

# Steps to reproduce the issue

1. Go into the instagram app, click on the three dots in the top-right of a post and click "Share Via".
2. Select Wallabag
3. Look in the wallabag app (or on the server) and see a link to the instagram login page rather than the actual post

# Environment details

- **wallabag app version**: 2.4.3
- **wallabag app installation source** (e.g. Gplay, F-Droid, manual):  play store
- **Android OS version**: 11 (Oxygen OS 11.1.5.5.AC01AA)
- **Android ROM** (e.g. stock, LineageOS, SlimRom,…): Stock (oneplus)
- **Android hardware**: OnePlus Nord
- **wallabag server version**: 2.2.3
- **Do you have Two-Factor-Authentication enabled?**: no

# Logs
## wallabag server

I don't think this is relevant (although I'll post if you like) - it seems like the app is corrupting the link rather than the server.  The server hasn't been updated for a while and this problem has only just occurred.

## Web server
Please paste relevant web server logs (e.g. from nginx, Apache, …) here:

I don't think this is relevant (although I'll post if you like) - it seems like the app is corrupting the link rather than the server.  The server hasn't been updated for a while and this problem has only just occurred.

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here!

# Your experience with wallabag Android app
Have you had any luck using wallabag Android app before? (Sometimes we get tired of reading bug reports all day and a lil' positive end note does wonders)

It's worked **wonderfully** for years (I installed it in 2017).  The last successfully saved instagram post I have was 10th September 2021, so it feels like something has changed recently, although I don't save stuff every day and I don't always go back and look at posts so I'm not sure when it actually stopped working.

**Comment by di72nn** [comment]
The app doesn't do anything with the links, so I'll have to assume the issue is with Instagram changing something. You can see the same result by trying to add an Instagram link via the web UI.

You may create an issue in [the server repo](https://github.com/wallabag/wallabag/issues).
