### ISSUE TITLE
Faux positif

### ISSUE THREAD

**Issue by qwertygc** [wallabag/android-app#126]
Avast dit que c'est un fichier suspect, car : 
APK:CloudRep(Susp)

Voilà voilà.

**Comment by tcitworld** [comment]
En installant l'APK depuis Github du coup ?

**Comment by qwertygc** [comment]
Oui

**Comment by tcitworld** [comment]
Bon, y a pas grand chose à faire apparemment. Je peux juste t'assurer qu'on est clean. Ça ira peut-être mieux quand ça sera publié en public sur GPlay.

**Comment by qwertygc** [comment]
Oui, j'ai confiance. J'ai pas de problème avec F-Droid (j'ai pas Gplay, ce qui est assez problématique au passage).

**Comment by qwertygc** [comment]
Je tenais quand même à informer au cas où.

**Comment by tcitworld** [comment]
Tu as bien fait.
