### ISSUE TITLE
[1.9] Combine URL upload and sync

### ISSUE THREAD

**Issue by khinsen** [wallabag/android-app#127]
I don't see any good reason to have the upload of locally stored URLs as a separate operation that must be launched manually. I'd expect this to be part of the sync operation. It should first upload the locally stored URLs, and then download articles via the RSS stream.

Moreover, I'd appreciate an option to sync automatically when the app is started.

**Comment by tcitworld** [comment]
Yup, it's just at first all processes were separated. Will change that.

**Comment by tcitworld** [comment]
Related to #7.

**Comment by di72nn** [comment]
Implemented it 1.12.0.

> Moreover, I'd appreciate an option to sync automatically when the app is started.

Track #360 and #404 for that.
