### ISSUE TITLE
Android app cannot connect 

### ISSUE THREAD

**Issue by silverman10** [wallabag/android-app#1272]
Describe what's wrong:

Android app cannot complete the initial connection and test.
Get the error saying connection cant be established due to unknown error.
Something i noticed is that it shows port 80 even though i am using https.

Interface loads without issues on Android and PC browser.

App version 2.4.3

![Screenshot_20220719-183820_wallabag~2.png](https://user-images.githubusercontent.com/33454830/179926658-18527c0d-bf86-4a63-96a5-f34a47dfab2c.png)

**Comment by silverman10** [comment]
Moved to Android app repo as suggested

**Comment by silverman10** [comment]
I suspected it would be something like that as described in the linked issue. I have a reverse proxy running that serves https.

So, for docker, is there an env var that sets the url to https? Can the wallabag server serve https directly?

**Comment by silverman10** [comment]
I was able to fix this from my reverse proxy, but would like to know if there was a easy/better fix within wallabag server

**Comment by di72nn** [comment]
That issue should probably be brought up in either the server or the docker repo.

> I was able to fix this from my reverse proxy
If it's not something mentioned in other issues, could you post some info on that please?

**Comment by silverman10** [comment]
Can do, but why? This is specific to Android app; the app works okay with a browser.
This was initially raised no the server repo, but was asked to be raised here, so dont want that to happen tbh

**Comment by di72nn** [comment]
> This is specific to Android app; the app works okay with a browser.

Not really. The app is just a bit too strict in how it follows redirects (it follows https->http downgrades, as the headers instruct it to), but the cause is what the server suggests, so other theoretical clients may have the same issue. Probably a docker-related issue.

Ok, maybe I'll have a look myself some other time.
