### ISSUE TITLE
[1.9] Slow URL upload

### ISSUE THREAD

**Issue by khinsen** [wallabag/android-app#128]
When I have a slow network connection, uploading a URL can take up to a minute, with the phone unusable during that time. Other read-later apps (Pocket, Instapaper) do the upload in the background.

A simple solution would be to store all URLs locally all the time, as if there were no network connection. This could be an option in the settings as it probably doesn't please everyone.

**Comment by tcitworld** [comment]
Yup. There's a number of things we want to do as background tasks.

**Comment by tcitworld** [comment]
#7

**Comment by di72nn** [comment]
Done in `master`.
