### ISSUE TITLE
Night reading mode with light text on dark background

### ISSUE THREAD

**Issue by menelic** [wallabag/android-app#13]
The Android app should have a day and a night reading mode, with the latter being white text on black background (with options to change text and background color ina range of lighter text and dark background colors). See Pocket, Pulse, the OwnCloud NewsReader App and others as examples. Maybe some code for this could be lifted from FBreader https://github.com/geometer/FBReaderJ which has a great night mode.

**Comment by Caliandroid** [comment]
night reading mode -> https://github.com/Caliandroid/wallabag-android-app
