### ISSUE TITLE
Adjust dark themes

### ISSUE THREAD

**Issue by nicosomb** [wallabag/android-app#135]
- missing pictures (starred / archived entries)
- notification popin (`please check your connection` and others) is grey with dark background. I think it should be better if we remove dark background

**Comment by nicosomb** [comment]
* same problem with dark background when I click on a tab

**Comment by tcitworld** [comment]
> notification popin (please check your connection and others) is grey with dark background. I think it should be better if we remove dark background 

Well, it's visible for me. We could update to material design and use a colored Snackbar instead.

> same problem with dark background when I click on a tab or an entry

You refer to what you said just below, or did I miss something ?

**Comment by nicosomb** [comment]
> We could update to material design and use a colored Snackbar instead.

YES!

> You refer to what you said just below

sorry, yes

**Comment by nr458h** [comment]
We had several changes on the UI are your issues still present - otherwise we probably could close this ticket.

**Comment by Strubbl** [comment]
I am closing this issue after the hint of @nr458h . 
If i was wrong and the issue still persists please reopen or create a new issue.
