### ISSUE TITLE
synchronize read

### ISSUE THREAD

**Issue by qwertygc** [wallabag/android-app#14]
Hi !
It's possible to synchronise article "mark as read" of Android to Wallabag servor Instance ?
Think.

------------
Salut !
C'est possible de synchroniser les articles "marqué comme lu" de Android à l'instance serveur Wallabag ?
Merci

**Comment by shtrom** [comment]
:+1:

**Comment by tgrosinger** [comment]
Does this issue mean marking things as read on the Android app does not actuall update the server? Any progress on this issue?

**Comment by tcitworld** [comment]
Yup. It needs wallabag server v2.0 with it's API.

**Comment by robertvanbregt** [comment]
+1 for syncing read articles across web, android phone and iPad.

**Comment by ParoTheParrot** [comment]
+1!

**Comment by shutdown76** [comment]
I need too!

**Comment by tcitworld** [comment]
Article status sync is now possible in the beta builds (only if you are online, however).
