### ISSUE TITLE
[1.9] on article view, put domain back

### ISSUE THREAD

**Issue by nicosomb** [wallabag/android-app#140]
When I'm reading an article, I want to know the URL and open this article in my browser (if the article is not fetched correctly).

**Comment by tcitworld** [comment]
I'll put the domain back (more stylized though) but you can open the article by going through the menu > Open in browser.

**Comment by nicosomb** [comment]
\o/ I discover one feature a day with this application!

**Comment by tcitworld** [comment]
We agree the domain is enough, not the whole URL has to be displayed (just like v2 web interface does) ?

**Comment by nicosomb** [comment]
Yes it is!
