### ISSUE TITLE
Feeds not found

### ISSUE THREAD

**Issue by AurelWeinhold** [wallabag/android-app#1402]
# Issue details
When I try to connect to my selfhosted instance of wallabag it does not work and throws the error "Feeds test failed. Unknown error".

### Duplicate?
Have you searched the issues of this repository if your issue is already known? yes

### Actual behaviour
- When connecting I get an error message: "Feeds test failed. Unknown error"

How do I find more logs in the android app to troubleshoot this issue? It is very much possible that this is an error with my server. However, the iOS client, browser integration and an rss feed application are working without any trouble.

### Expected behaviour
- I connect to my instance and see my unread feed

# Steps to reproduce the issue
1. I fill in the url (in this case `http://ip:port`) , username and password
2. I try to automatically fill in the rest: error "Something went wrong. Check your internet connection"
3. I fill in the rest (user id, token) by hand
4.I try to connect: error: "Feeds test failed, Unknown error"

# Environment details
- **wallabag app version**: 1.11.0 (29)
- **wallabag app installation source** (e.g. Gplay, F-Droid, manual): F-Droid
- **Android OS version**: 14
- **Android ROM** (e.g. stock, LineageOS, SlimRom,…): stock
- **Android hardware**: Pixel 5
- **wallabag server version**: 2.6.9
- **Do you have Two-Factor-Authentication enabled?**: no

# Logs
## wallabag server
Please paste relevant wallabag server logs here (from file `<wallabag>/var/logs/prod.log`):
None

## Web server
Please paste relevant web server logs (e.g. from nginx, Apache, …) here:
None

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here!

# Your experience with wallabag Android app
Have you had any luck using wallabag Android app before? (Sometimes we get tired of reading bug reports all day and a lil' positive end note does wonders)
Unfortunately none. I would love to, though

**Comment by tcitworld** [comment]
F-Droid has disabled all current builds because of https://github.com/wallabag/android-app/issues/1399
