### ISSUE TITLE
TTS stucks if edit tts_parser.js in some specific ways

### ISSUE THREAD

**Issue by void285** [wallabag/android-app#1408]
# Issue details

### Duplicate?
no

### Actual behaviour
In `app/src/main/res/raw/tts_parser.js`, there is a function named `shouldSkip`, when I try editing it to skip pre or code tags, I found if include `!==` operator or edit the function in some specific ways, a problem occurs: **after tap the play button, the play button stays as `...` and the TTS wont work.**

The original function:
```js
function shouldSkip(element) {
    return element.nodeType === Node.COMMENT_NODE
        || element.tagName === 'SCRIPT' || element.tagName === 'NOSCRIPT'
        // Skip stats icons
        || (element.tagName === 'I' && element.classList.contains('no-tts'));
}
```

Success conditions:
```js
        || (element.tagName === 'I' && element.classList.contains('no-tts'))
        || (element.tagName === 'PRE' && element.textContent.match(/ /) && element.textContent.match(/[\(\[\{=]/))
        || (element.tagName === 'CODE' && element.textContent.match(/ /) && element.textContent.match(/[\(\[\{=]/))
```

If include condition like this, the problem occur:
```js
        // cause problem, if change sub condition order
        || (element.classList.contains('no-tts') && element.tagName === 'I')
        // cause problem, if contains !==
        || (element.tagName !== '' && element.classList.contains('no-tts'))
        // cause problem, if no tagName condition, use classList.contains only
        || element.classList.contains('no-tts')
        // cause problem, if use str.includes(' ')
        || (element.tagName === 'PRE' && element.textContent.includes(' ') && element.textContent.match(/[\(\[\{=]/))
        || (element.tagName === 'CODE' && element.textContent.includes(' ') && element.textContent.match(/[\(\[\{=]/))
```

# Environment details
- **wallabag app version**: 2.5.3
- **wallabag app installation source** (e.g. Gplay, F-Droid, manual): self generated apk
- **Android OS version**: 6.0 / 10.0
- **Android ROM** (e.g. stock, LineageOS, SlimRom,…): vivo
- **Android hardware**: vivo
- **wallabag server version**: 2.6.6
- **Do you have Two-Factor-Authentication enabled?**: no

# Your experience with wallabag Android app
Wonderfull, wallabag is my most used APP.

**Comment by void285** [comment]
I try replace `ttsHost.getWebView().evaluateJavascript` with `ttsHost.getWebView().loadUrl` in `java/fr/gaulupeau/apps/Poche/tts/WebViewText.java`, even worse, the play button always stucks.

**Comment by di72nn** [comment]
Have you tried using [WebView debugging](https://developer.chrome.com/docs/devtools/remote-debugging/webviews)? If I recall correctly, it was quite useful for debugging this functionality.
I think all you have to do is to have your device in the same network and open `chrome://inspect` in Chrome (or Chromium).

**Comment by void285** [comment]
Thank you! I debug webview and find the problem is caused by "no contains method on undefined", so I have to check if element.classList is undefined first. Obviously, the script/style elements have no classList properties.
