### ISSUE TITLE
Cannot display entry content

### ISSUE THREAD

**Issue by alfredbuehler** [wallabag/android-app#1421]
# Issue details

Trying to display an entry content, the screen stays on "Loading" forever. As It has been working earlier, could it be that the support for Android 8.0 was dropped? I tried downgrading to almost every older version of the app, without any success. And it is working well with Android 8.1.

### Duplicate?
Have you searched the issues of this repository if your issue is already known? yes

### Actual behaviour
- Tap on an entry to display it.
- The screen stays on "Loading" forever.

### Expected behaviour
- Entry content should be displayed.

# Steps to reproduce the issue
1. Tap on any entry to display it.
2. Wait forever

# Environment details
- **wallabag app version**:  2.5.3 (233)
- **wallabag app installation source** (e.g. Gplay, F-Droid, manual): Tried both
- **Android OS version**:  8.0.0
- **Android ROM** (e.g. stock, LineageOS, SlimRom,…): stock
- **Android hardware**:  Galaxy A3 2017
- **wallabag server version**: 2.6.9
- **Do you have Two-Factor-Authentication enabled?**: no

# Logs
## wallabag server
Please paste relevant wallabag server logs here (from file `<wallabag>/var/logs/prod.log`):
There is no such log, directory is empty.

## Web server
Please paste relevant web server logs (e.g. from nginx, Apache, …) here:
```
84.72.75.16 - - [02/Aug/2024:09:39:53 +0200] "GET /api/version HTTP/1.0" 200 372 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0"
84.72.75.16 - - [02/Aug/2024:09:39:53 +0200] "POST /oauth/v2/token HTTP/1.0" 200 691 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0"
84.72.75.16 - - [02/Aug/2024:09:39:54 +0200] "GET /api/tags.json HTTP/1.0" 200 558 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0

```

## Logcat
Partial, grepped for "error".
```
08-02 09:39:11.006 14536 14557 I zygote  : Rejecting re-init on previously-failed class java.lang.Class<kotlinx.coroutines.internal.ClassValueCtorCache$cache$1>: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/lang/ClassValue;
08-02 09:39:11.008 14536 14557 I zygote  : Rejecting re-init on previously-failed class java.lang.Class<kotlinx.coroutines.internal.ClassValueCtorCache$cache$1>: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/lang/ClassValue;
08-02 09:39:11.009 14536 14557 I zygote  : Rejecting re-init on previously-failed class java.lang.Class<kotlinx.coroutines.internal.ClassValueCtorCache$cache$1>: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/lang/ClassValue;
08-02 09:39:52.757 14536 14536 I zygote  : Rejecting re-init on previously-failed class java.lang.Class<WV.NG>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/webkit/PacProcessor;
08-02 09:39:52.761 14536 14536 I zygote  : Rejecting re-init on previously-failed class java.lang.Class<WV.NG>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/webkit/PacProcessor;
08-02 09:39:52.764 14536 14536 I zygote  : Rejecting re-init on previously-failed class java.lang.Class<WV.NG>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/webkit/PacProcessor;
08-02 09:39:52.771 14536 14536 I zygote  : Rejecting re-init on previously-failed class java.lang.Class<WV.NG>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/webkit/PacProcessor;
08-02 09:39:52.774 14536 14536 I zygote  : Rejecting re-init on previously-failed class java.lang.Class<WV.NG>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/webkit/PacProcessor;
08-02 09:39:52.777 14536 14536 I zygote  : Rejecting re-init on previously-failed class java.lang.Class<WV.NG>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/webkit/PacProcessor;
08-02 09:39:53.291 14536 14639 E chromium: [ERROR:simple_backend_impl.cc(762)] Simple Cache Backend: cache directory inaccessible right after creation; path: /data/user/0/fr.gaulupeau.apps.InThePoche/cache/WebView/Default/HTTP Cache/Code Cache/js
08-02 09:39:53.293 14536 14641 E chromium: [ERROR:disk_cache.cc(208)] Unable to create cache
```

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here!

# Your experience with wallabag Android app
Have you had any luck using wallabag Android app before? (Sometimes we get tired of reading bug reports all day and a lil' positive end note does wonders)

Yes, Im still very satisfied, but I dont know when the described issue appeared. And everything else works like a charm, eg I can create and delete entries, add to favorites etc.

**Comment by Strubbl** [comment]
Minimum Android version is still at Android 5.0, see https://github.com/wallabag/android-app/blob/master/app/build.gradle#L8
Otherwise i have no idea at the moment.

**Comment by alfredbuehler** [comment]
Meanwhile, it works again, even if I don't know why.
