### ISSUE TITLE
Use a PreferenceScreen for settings instead of regular view

### ISSUE THREAD

**Issue by tcitworld** [wallabag/android-app#143]

**Comment by nicosomb** [comment]
I don't know if I have to open a new issue for that, but the list to change the theme of the application is not easy to use (or maybe my fingers are too big).

**Comment by Strubbl** [comment]
Indeed, it is hard to choose the desired theme in the small drop down menu. I would like it, if it can be improved.

**Comment by di72nn** [comment]
Done in `master`.
