### ISSUE TITLE
Annotation button disappears

### ISSUE THREAD

**Issue by QuAzI** [wallabag/android-app#1431]
Sometimes a user has to scroll a page or do something else (like extract stylus on Samsung Note) to see the `Annotate` option in the menu. Occasionally, the user can see an option, but it hides when the user tries to select more text by dragging selection border points.

https://github.com/user-attachments/assets/63c475b2-22fe-41c3-a008-603731739d47

**Comment by Strubbl** [comment]
I can also reproduce this issue. After selecting text, one has to scroll some pixels in order to get the annotate button.

**Comment by jason-mehmel** [comment]
This is also happening with me!

(Though I'm happy to have discovered a trick where annotate works!)

**Comment by Lorite** [comment]
It also happens to me on all my devices. It's nice to hear that there's a workaround. I hope it gets fixed too ☺️

**Comment by cristianmtr** [comment]
I can't annotate at all either. I select text, scroll up and down, but no annotation buttons appears.

**Comment by mirenbz** [comment]
Thanks! I was thinking the highlight/annotate feature was simply not implemented, great to know this tip, works on mboile.

However, it doesn't work in my Boox Note Air 3 (Android 12). The scroll tweak invokes the "Add tag" button, but "Annotate" is not showing. There is also no three-button menu... any clues? It would be great to have Wallabag working in eInk!

**Comment by geewiz** [comment]
I see the same behaviour as @mirenbz on my Boox Go 10.3. I bought it specifically for reading and annotating, so this is a huge bummer.

**Comment by Strubbl** [comment]
I found a fix in calling [invalidate()](https://developer.android.com/reference/android/view/ActionMode#invalidate()) when the menu is created. This should fix this issue because the menu is refreshed before it is shown.
