### ISSUE TITLE
Title images duplication

### ISSUE THREAD

**Issue by QuAzI** [wallabag/android-app#1432]
In the mobile app I see two images instead of one
![image](https://github.com/user-attachments/assets/c954d460-a40a-4a70-a773-6695747ca94b)

The same article in Web app

![image](https://github.com/user-attachments/assets/90463f9a-348b-47c4-911c-cf24f6a31385)

**Comment by di72nn** [comment]
That's been discussed in #777, but not fixed. Also, the preview images (so the first one will not appear) can be disabled in the UI settings.
Closing as duplicate.
