### ISSUE TITLE
java.lang.NullPointerException when trying to put website "In the Bag"

### ISSUE THREAD

**Issue by MaoPU** [wallabag/android-app#154]
Every time I try to add a website to wallabag, the app crashes.

The NullPointerException is reported for FormEncodingBuilder.java on line 38 (add method). I am using package version 17 on Android 5.1.1.

**Comment by di72nn** [comment]
Thank you for the report. In order to save pages you have to enter username and password in the settings. We probably will add a notification for that soon.
The NPE by itself is fixed in #148.

**Comment by tcitworld** [comment]
An update has been submitted on the Play Store.

**Comment by di72nn** [comment]
Outdated.

**Comment by MaoPU** [comment]
This problem only occurred after an update from the previous version of wallabag. Once I deleted all cache and data for the app, I was asked to enter my credentials and was able to use the app without problems afterwards. It would be helpful to have those instructions somewhere or delete the cache during the update.

**Comment by di72nn** [comment]
Yeah, I added another notification dialog for such cases in #160.
