### ISSUE TITLE
Set status bar to the same color than wallabag theme color

### ISSUE THREAD

**Issue by tcitworld** [wallabag/android-app#157]
Avoid this kind of thing : 

![](https://pbs.twimg.com/media/CVk3QJXWEAA8-4I.jpg)

**Comment by tcitworld** [comment]
https://developer.android.com/training/material/theme.html#StatusBar

**Comment by Lokesh-Krishna** [comment]
With the direction the new icon is taking in #317 could it possible to change the color scheme of the app from the current black to the colors on the website, with a complementary status bar color?

**Comment by Strubbl** [comment]
@tcitworld cannot reproduce this issue with current version of the app. Do you still have this issue?

**Comment by Strubbl** [comment]
I guess this is issue is fixed. If not please re-open.
