### ISSUE TITLE
Soft menu missing

### ISSUE THREAD

**Issue by olafgroetz** [wallabag/android-app#16]
Hi there,

I've recently updated my phone to Android KitKat and the soft menu has disappeared from the app (the one for settings and purge DB). Thanks to a backup application (Titanium Backup) I could restore my settings but I cannot modify them neither purge the DB so my reading list is growing despite I do read a lot :)
I could reproduce the bug on my wife's phone also on KitKat.

Anybody has the same issue and a possible a workaround ?

**Comment by tcitworld** [comment]
Not relevant anymore (design changed)
