### ISSUE TITLE
Article Images are missing [self-signed certificate]

### ISSUE THREAD

**Issue by AmrEldib** [wallabag/android-app#162]
Images load correctly in the browser, but not on the Android app. Is this just me?
![articleimageonandroid](https://cloud.githubusercontent.com/assets/769272/11664612/a17da3e4-9d97-11e5-802c-cb75c1d3ac55.png)
![articleimageinbrowser](https://cloud.githubusercontent.com/assets/769272/11664616/a3a492f4-9d97-11e5-9659-e62db82ef037.png)

**Comment by tcitworld** [comment]
Hi,
Are you by any chance using HTTP Auth ? Are you using Framabag, or are you caching pictures on the server ? What's your Android version ?

**Comment by AmrEldib** [comment]
App version 1.9
Android version 6.0
Self-hosted on Windows. Wallabag version 1.9.1
Using HTTPS with a self-signed certificate
Not sure if I'm caching pictures on the server. I have "Delete Cache" option in the configurations, but no option for caching pictures.

**Comment by tcitworld** [comment]
> Not sure if I'm caching pictures on the server.

It's only accessible through [a config file](http://doc.wallabag.org/en/Administrator/hidden_options.html) (see `DOWNLOAD_PICTURES`), so I guess you didn't.

Can you provide us your wallabag address and token (**not** your username or password) so that we test it for ourselves ?

**Comment by AmrEldib** [comment]
I'll check the config file to see if I'm caching pictures. Hopefully that will fix it. I'll report back. Thanks!

**Comment by di72nn** [comment]
I believe it's related to self-signed certificate: looks like we don't support images with "Accept all SSL certificates" option.

@AmrEldib if you use "Accept all SSL certificates" option, then I strongly advise you to [import the certificate into your system](https://davdroid.bitfire.at/faq/entry/importing-a-certificate) (and disable the option).

**Comment by AmrEldib** [comment]
@di72nn I'll try this first. Thanks for linking to how to import the certificate.

**Comment by AmrEldib** [comment]
Excellent suggestion @di72nn 
That fixed the problem. After installing the self-signed certificate and unchecking "Accept All Certificates", I can see images.

**Comment by tcitworld** [comment]
I keep this opened until #163 fixes or not the issue. :)
