### ISSUE TITLE
error 500 archive

### ISSUE THREAD

**Issue by qwertygc** [wallabag/android-app#165]
J'ai une erreur 500 quand je réactualise les archives. J'ai supprimé les archives via une requête SQL, et j'ai plus l'erreur. Je suppute un problème avec un des articles.
Test quand j'ai tout mes articles : 
J'ai cette erreur : Erreur d'analyse XML : aucun élément trouvé
Emplacement  : /bag/?feed&type=archive&user_id=1&token=blabla
Numéro de ligne 1, Colonne 1 :
^

Nota bene :  2406 articles marked as read. Si ça peut aider.

**Comment by tcitworld** [comment]
Same as  #97

**Comment by qwertygc** [comment]
Comment rechercher ces caractères bizzares ?

**Comment by Ygster** [comment]
Si cela peut aider, j'ai le même problème et dans mon cas cela semble venir de page du site https://wiki.debian.org (par exemple la page https://wiki.debian.org/SSDOptimization)

**Comment by tcitworld** [comment]
Ce site et cette page ne me pose pas de problème. Grr.

> : 2406 articles marked as read. Si ça peut aider.

Cela ne me motive pas trop à les regarder un par un pour voir quel est le coupable. :p
