### ISSUE TITLE
[1.9] Screen blocked after saving a URL

### ISSUE THREAD

**Issue by khinsen** [wallabag/android-app#166]
Since the latest beta update (done yesterday), I observe the following behavior when saving URLs:
 1. I tap "share" in some app (tested with TweetCaster and gReader Pro)
 2. I select Wallabag.
 3. Wallabag confims with the popup "added".
 4. The screen is blocked, I cannot interact with the initial app any more.
 5. When I tap the "back" button on my phone, operation is back to normal.

**Comment by di72nn** [comment]
Oops, my bad. I forgot to close transparent proxy activity, when I removed progress dialog.
I'll fix it as soon as I can. Thanks for the report.

**Comment by The0x539** [comment]
Hooray!
