### ISSUE TITLE
Sorting mode of the articles

### ISSUE THREAD

**Issue by acotte** [wallabag/android-app#17]
I really don't understand how articles are sort. If we had to resort to only one sorting mode. Date of add in Wallabag is the best one for me.  More options is a plus.

**Comment by tcitworld** [comment]
More sorting ways : estimated reading time, alphabetical.

**Comment by Strubbl** [comment]
issue #42 also deals with sorting, but by name. Creation and update date should be possible, too.

**Comment by di72nn** [comment]
Closed in favor of #42.
