### ISSUE TITLE
[1.9.3.1] Save first on first call but then no longer works

### ISSUE THREAD

**Issue by nsteinmetz** [wallabag/android-app#171]
On Anroid 4.4.2 with latest stable firefox

When I use the Save button provided by Wallabag, it works on first call. Then if in other tabs I want to save another article it no longer works.

I would say it worked in 1.9.1 or 1.9.2 but no longer works since 1.9.3.*

Let me know how I can provide more details (logs ?) if necessary.

Thanks,
Nicolas

**Comment by tcitworld** [comment]
I can't manage to reproduce it on my own device. Will launch an emulator tonight to see how it goes on Android 4.4.2

**Comment by di72nn** [comment]
What exactly happens? Does a toast-message "Added" appear on the screen?

**Comment by nsteinmetz** [comment]
@di72nn nothing happens ; the toast message does not appear and nothing is added in my wallabag instance.

btw, just checking, could it be a letsencrypt related issue ? But It would always fail and app loads/synchronise correctly. And adding a bookmark worked at least once.

**Comment by nsteinmetz** [comment]
Weird it now works after closing FF & Wallabag ; maybe previous 1.9.3 save action was still there ?

Sorry for the noise, testing more, it works perfectly.
