### ISSUE TITLE
Adding Link from In-App Doesn't Trigger Refresh

### ISSUE THREAD

**Issue by psycotica0** [wallabag/android-app#172]
If I click on a link and pick 'add to wallabag', I've now saved it in my list.
If I then go "back", though, I won't see the items I just added until I refresh.

**Comment by tcitworld** [comment]
Yup, we could add an option to choose to refresh list after adding an element (we shouldn't refresh as default, since it needs a lot of data - this will of course change in the future).

**Comment by di72nn** [comment]
Done in `master`.
