### ISSUE TITLE
HTML link appear too bold and underlined

### ISSUE THREAD

**Issue by etiess** [wallabag/android-app#173]
Reading an article on the app is cool (by the way, great to have the "Save in Wallabag" option now!), but HTML links appear too bold and underlined. I think it could be nicer to have a different color to indicate links (not underline, and not bold).

I agree it's a matter of taste, but I have the impression that it's becoming a standard (look at Github for example).

Server: Framabag
App : 1.9.3.1

**Comment by Strubbl** [comment]
It would be nice to have more concrete suggestions here. At least for the themes dark, light and solarized. 
Maybe @ngosang has an idea?

For high contrast themes in light and dark i would keep this bold and underlined, because color would decrease the contrast.

**Comment by ngosang** [comment]
@etiess take a look #598

**Comment by etiess** [comment]
Great, thanks @ngosang
