### ISSUE TITLE
Yunohost : the app can't see Wallabag

### ISSUE THREAD

**Issue by Krands** [wallabag/android-app#174]
Hi,

I have a Yunohost instance which has a Wallabag instance : ril.krands.be (*ril* for *Read It Later*).
When I log in the Android app, it says that the `URL is not found`.

The user ID is entered and the token, generated and pasted.

While I tried everything I could, I don't know where the problem is from : the app or the way to log in Yuhonost's Wallabag.

Cheers !

**Comment by tcitworld** [comment]
Hi,
URL is correctly entered into the android app ? Also, I can be mistaken, but it seems to me you need to enter your Yunohost LDAP credentials in the Http Auth fields of the wallabag android app settings.

**Comment by Krands** [comment]
Yes, it's a `HTTPS` URL. I verified more than twice in any possible combination. 

In `HTTP` Auth fields ? Ha, never tried, because I am not using HTTP, I am going to try that.

**Comment by tcitworld** [comment]
Perfect. I'll see with the Yunohost guys if they can put something about this in their documentation.
