### ISSUE TITLE
Scroll position restored based on wrong height

### ISSUE THREAD

**Issue by psycotica0** [wallabag/android-app#178]
It looks like the position of an article is stored if the back button is pressed, but if I switch to another app and don't come back right away the reading position is back at the top after the app reopens.

**Comment by di72nn** [comment]
The position is stored in the `onStop()` call, which happens when the activity is removed from screen.
Is the behavior you talking about reproducible? Does it happen for any article?
There is also a chance the problem is that the position is *saved*, but *not restored* for some reason.

**Comment by psycotica0** [comment]
Alright, I've looked at the log now, and you're right. The position is saved properly.

At the time of restore, it looks like it's getting the height during the "loading" phase and calculating the otalHeight to be 75, much smaller than the viewHeight, and so it's staying at the top.

**Comment by psycotica0** [comment]
I've been testing a bit and found that, on my device, it seems to end up in the `onPageFinished` callback at a point where the height of `webViewContent` is `16` about 60% of the time.

So, if I put an `|| webViewContent.getHeight() == 16` next to the `0` that's already being checked for, and it goes around again, I now have rock solid position resuming.

I don't know why `16`, though, so `==` makes me nervous.
And I assume the current setting is working for other people.

Will there ever be an article ` < 30`? Is that better or worse?

**Comment by psycotica0** [comment]
My Device is MotoG 2nd Generation, running 5.0.2.

**Comment by di72nn** [comment]
That's weird.
Does it happen with any article or only with a particular one? If the latter, what kind of content does it have (text only, text/images, images only, other)? Also in that case a link to an original page would be helpful.

**Comment by psycotica0** [comment]
I've tried it with 2 articles, and both have this. I've also just now tried it with the "Large Font" accessibility feature on, and it is still `16`, so it's not "one line of text plus padding" or something.

The articles I've tried don't seem to have images.

- https://18f.gsa.gov/2015/12/15/how-bot-named-dolores-landingham-transformed-18fs-onboarding/
- https://blog.ethereum.org/2014/05/06/daos-dacs-das-and-more-an-incomplete-terminology-guide/

**Comment by psycotica0** [comment]
Tapping a bunch of other articles, it seems like some they all either work with `0`, or work with `16`. I haven't had any fail to get reading position, but it seems like some articles need `16` more often than others. Some I've only seen it use it once in a bunch of testing, others I haven't seen it use it at all. Some it's fairly common for me. Feels race-conditiony...

**Comment by psycotica0** [comment]
https://roamingaroundatrandom.wordpress.com/2014/06/16/an-mpc-based-privacy-preserving-flexible-cryptographic-voting-scheme/

This one (based on my log) sometimes goes around on my `16` code path 5 times before it gets it right.

**Comment by di72nn** [comment]
Thanks for your efforts in debugging it.
I can't reproduce it with these articles on Android 4.4.4, so it's probably have something to do with Android's WebView.
Can you also try the following on your device? Override `onPageStarted` and `onLoadResource` methods of `WebViewClient` and log WebView's height on these calls. Maybe we can get "start value" from there to use it in `onPageFinished` check.

**Comment by psycotica0** [comment]
On my device I get a height of `0` during `onPageStarted`, even when going through the weird height path. It only seems to call `onLoadResource` once. The height was `16` when it was called, but then it wasn't called any of the other times I opened and closed the article. And, that one time it was called, I didn't end up going through the weird path (probably because of timing more than anything), so it doesn't seem like a reliable path.

**Comment by di72nn** [comment]
@psycotica0 you may want to try #180 out.
I set condition to "< 50" (in any case we have title line + url line + some margins, which gives more than 60 pixels on mdpi).

**Comment by psycotica0** [comment]
Alright, I've put a little extra logging in there and run one of my bad eggs, and found that it did go through the code 10 times with a height of 16, but ultimately did load the right position.

Seems good to me, :+1:

**Comment by di72nn** [comment]
Thanks again.
