### ISSUE TITLE
Flags while offline

### ISSUE THREAD

**Issue by Matthias84** [wallabag/android-app#182]
Currently the client complains if the device is offline and the user interacts with the documents (mark read, fav, ...). IMHO wallabag is designed for offline usage (on travel, ...) so it would be nice, if the user could also do the essential actions while he isn't online

P.S: Anyway it's working and simple to use. Thanks for the client and server :+1:

**Comment by di72nn** [comment]
Yeah, I want to move all the network operations to background (and queue them while offline), but I can't find time for that. Unfortunately, there are not much contributors.

**Comment by di72nn** [comment]
Done in `master`.
