### ISSUE TITLE
Support for TLS 1.2

### ISSUE THREAD

**Issue by Amarandus** [wallabag/android-app#183]
Hi,

I am running my own instance of wallabag on a hardened nginx server. As the only protocol version allowed is 1.2, I am not able to use the android app, as it looks like android defaults to (only) 1.0, if not demanded otherwise.

I think that I found the "problematic" line here, but as I am not an android dev, the problem might exist somewhere else:
https://github.com/wallabag/android-app/blob/master/app/src/main/java/fr/gaulupeau/apps/Poche/network/WallabagConnection.java#L127

By changing the parameter to "TLSv1.2" (See https://developer.android.com/reference/javax/net/ssl/SSLContext.html#getInstance%28java.lang.String%29), well, TLS 1.2 should be working, but I can not estimate what would get broken by that, as a higher API-Level might be required.

I hope that TLS 1.2 gets supported soon, if it is possible.

Greetings,
Amarandus

**Comment by di72nn** [comment]
Hello Amarandus,

The code you mentioned is only called if you have option "Accept all SSL certificates" enabled (which is not by default), so it's not the part that needs to be changed.

It looks like Android 4.1+ got TLSv1.1 and TLSv.1.2 support, but these protocol are disabled by default till Android 5. **If you run Android version lower than 4.1, there is no easy way to use TLSv1.1/1.2.**

To add support for TLSv1.2 we need to implement something like [this](http://blog.dev-area.net/2015/08/13/android-4-1-enable-tls-1-1-and-tls-1-2/). I'll look into it, but I can't promise it will be soon.

**Comment by Amarandus** [comment]
> The code you mentioned is only called if you have option "Accept all SSL certificates" enabled (which is not by default), so it's not the part that needs to be changed.

Ah, I am sorry, I should have read a bit in the surrounding code. I did not enable that option, so it is correct that the "normal" TLS-wrapping occurs in OkHttpClient then?

>If you run Android version lower than 4.1, there is no easy way to use TLSv1.1/1.2.

Yes, that is correct as far as I know. I am running 4.4.4 and I checked this before.
The error I recieved was (at least a part of it):
> I/O error during system call

After searching for a solution of this error, the version problem was mentioned a few times, which led me to try TLSv1.0 in the first place.

Thanks for having a look into it :+1: 

Greetings,
Amarandus

**Comment by BenoitMartin2** [comment]
Hi, same here. A+ SSL site and couldn't use the APK anymore (Android 4.4.2).
BTW thanx for your job on this project!

**Comment by di72nn** [comment]
I added "Custom SSL settings" option (which is disabled by default). The option (if works correctly) disables all SSL* protocols and enables all the supported TLS* protocols, it also enables custom set of cipher suites. The code is mostly based on DAVdroid's SSL Socket Factory implementation.

I don't have much time to test it, so it's only available as sources [here](https://github.com/di72nn/wallabag-android-app/tree/custom_ssl). If anyone is willing to test it (and is able to build it), go ahead.

**Comment by tcitworld** [comment]
I can build signed apks if needed.

**Comment by BenoitMartin2** [comment]
Thanks but i'm afraid I'm a noob at Android and don't know how to build a package. Would be really pleased if @tcitworld could build and push it to F-Droid (don't have gapps).

**Comment by tcitworld** [comment]
I can't push beta versions to f-droid (they have disabled it), I can only build an APK file that you can install directly without gapps (you'll have to temporarily uninstall the F-Droid version before, though).

**Comment by BenoitMartin2** [comment]
If you can provide me with any link to get your APK I'll give it a try.

**Comment by tcitworld** [comment]
Here you are : https://framadrive.org/index.php/s/uQae8ZIoh8Mh6rN

**Comment by tcitworld** [comment]
Don't forget to uninstall the old one before installing it.

**Comment by BenoitMartin2** [comment]
Thanks a lot! It's now okay using a hardened SSL URL  :)
