### ISSUE TITLE
PayPal Giving Fund

### ISSUE THREAD

**Issue by SweetLion** [wallabag/android-app#184]
Hey there,

are you registered in the PayPal Giving Fund? I was not able to find you there.
When you enroll you do not have to pay fees when you get money. It is also possible to support you in the Humble Bundle / Store. Thank you very much.

I wish everyone a very Merry Christmas and a wonderful Happy New Year!

**Comment by SweetLion** [comment]
And you could use an affiliate program like https://affiliate-program.amazon.com/ to get donations 😎

**Comment by tcitworld** [comment]
We'll have a look at the Paypal Giving Fund.

**Comment by SweetLion** [comment]
You can check out gooding too, if you like: https://www.gooding.de

**Comment by SweetLion** [comment]
https://donorbox.org/
https://viget.com/advance/accepting-donations-online-and-how-stripe-can-help
