### ISSUE TITLE
Wallabag v2 support

### ISSUE THREAD

**Issue by rominf** [wallabag/android-app#185]
I'm trying to connect to the `http://v2.wallabag.org` server and I'm getting following error:
```
Fail

Wallabag service not found; check URL. Error code: 1
```

I guess that Android app doesn't support Wallabag v2 yet. If so, can you give more precise error message?

Also, what are the plans for Wallabag v2 support?

**Comment by tcitworld** [comment]
The android app doesn't support v2 yet (even though it's accessible through RSS feeds as well, but you miss all the new functionalities). Support will be added progressively as soon as possible.

**Comment by Asara** [comment]
+1 for v2 support.

**Comment by N07070** [comment]
Big up for V2 support !

**Comment by benediktg** [comment]
What about the support for Wallabag v2.0 now that it is released?

**Comment by bigretromike** [comment]
:+1: Would love that

**Comment by bigretromike** [comment]
Which repo is for newest 2.0.0 ? This or https://github.com/wallabag/wallabag-v2-android ?

**Comment by tcitworld** [comment]
I'm continuing work on this repo for now to make the app v2-compatible. However, if anyone would be interested in looking up the other one, I would be pleased to give him/her a hand.

**Comment by bigretromike** [comment]
so both of them are trying to add support to v2?

**Comment by tcitworld** [comment]
Yes. Both apps only miss the authentication/connection part, though.

**Comment by bigretromike** [comment]
So almost there ;-) wish you best with finishing this! Hope it will hit f-droid soon ! :+1:

**Comment by prysme01** [comment]
can't wait to test it on fdroid :)
Thanks for your time and your work !

**Comment by Asara** [comment]
Seems like the app works with v2 now.  Give it a try!

**Comment by tcitworld** [comment]
Basic functionalities are here.

**Comment by azrdev** [comment]
@tcitworld can you elaborate what "basic functionalities" mean? Syncing unread/archived/favorite articles? (in background, or still in the GUI thread?) telling the server about read articles?

**Comment by Strubbl** [comment]
@azrdev yes
- Syncing unread/archived/favorite articles
- toggle unread/archived/favorite status and deletion of articles. it works in the wallabag backend, but you get a 500 server error due to a bug in in Wallabag (see https://github.com/wallabag/wallabag/issues/1924)

**Comment by tcitworld** [comment]
(Which will be fixed in wallabag 2.0.2.)

**Comment by anarcat** [comment]
so i guess the next question is what is *missing* from the v2 app compared to the v1? :) is there somewhere we can track progress other than here or this is a good place?

thanks!

**Comment by benediktg** [comment]
I think there should not be missing much in comparison to the old app in version 1.9.3.1 since it is not a rewrite.

**Comment by anarcat** [comment]
it looks like this is generally working, except for issues noticed in #203 and (for me) #215. thanks!

**Comment by bigretromike** [comment]
Most important thing work :-) Which I thank you guys for.
Finally something that made pocket say bye-bye from my devices !
