### ISSUE TITLE
Cannot set “Accept all SSL certificates” on first configuration

### ISSUE THREAD

**Issue by shtrom** [wallabag/android-app#189]
I have an account on a self-hosted instance with a CAcert certificate (waiting to migrate to Let's Encrypt).

When first configuring the application, it refused to connect with the message mentioned in #151. I tried checking the “Accept all SSL certificates” option, but the error remains. I tried restarting the app, as mentioned next to the check-box but, as the app couldn't connect, the “Save” button is inhibited, and the state of the option is not saved.

This is a bit of a chicken-and-egg problem where I need a valid connection to be able to save the SSL-acceptance option and put it in force, but I need for it to be in force to be abe to establish a valid connection.

**Comment by di72nn** [comment]
The "save" button is disabled if either user id or toked field is empty. That *kinda* made sense when the app had less options, but now it should be fixed.
