### ISSUE TITLE
Bug when trying to send offline links

### ISSUE THREAD

**Issue by nytche** [wallabag/android-app#193]
hello,
first of all, i'd like to tell you that I love the new version of the app, it's a great job and it does almost all I need to read my daily news in the train. thanks :)

The main issue I have is that I cannot send my offline links to my my server. At first, it worked, and now I always have the fail message. Is there a way to retreive them simply?

another bug is that several articles stay in my unread list, even if I have deleted them on the server. They come back again and again...

**Comment by tcitworld** [comment]
Hi,

Thank you for using wallabag.

What's the fail message you're talking about ? Something about a timeout ?

> another bug is that several articles stay in my unread list, even if I have deleted them on the server. They come back again and again...

Strange. If it bothers you too much, you can purge all articles from database (menu in the settings view) and fetch them again.

**Comment by nicocans** [comment]
1. The message is: "Echec" after the "Ajout des URL hors-lignes" popin.

2. I used to purge the database this way, but the option have disapeared in the new version of the app for me. Or is it very hidden?

**Comment by tcitworld** [comment]
Here is it.
![screenshot_20160203-092201](https://cloud.githubusercontent.com/assets/2197836/12776613/b22ac2de-ca57-11e5-8990-2ff5cd627813.png)

When purging database, the faulting offline urls not imported will be deleted and you should be able to import new ones again.

**Comment by nicocans** [comment]
I dont't see your top button :(
my version is 1.9.3.1

no way to recover my existing offline URLs?

**Comment by di72nn** [comment]
> no way to recover my existing offline URLs?

Hang on, I'll make a workaround.

**Comment by di72nn** [comment]
The app won't stop on first failed offline URL; all the failed URLs will be copied to clipboard (the failed URL won't be deleted from the app).
[workaround branch](https://github.com/di72nn/wallabag-android-app/tree/offline_urls_workaround)
@tcitworld can you build it?
@nicocans can you provide us with problem URLs (once you get them) so we can debug the issue?

**Comment by tcitworld** [comment]
There is it (apk is zipped). [app-release.apk.zip](https://github.com/wallabag/android-app/files/116137/app-release.apk.zip)
It won't work if you have F-Droid's version, though.

**Comment by nicocans** [comment]
I do have the f-droid version.
do I have to uninstall it?

**Comment by tcitworld** [comment]
Yes (apk from f-droid are signed with they key), but you'll loose the incriminating urls for now.

**Comment by nicocans** [comment]
I had 22 links offline :'(

**Comment by nicocans** [comment]
what if I backup the DB and import it back after installing the new version of the app? could I recover my former links? Is it compatible?

**Comment by tcitworld** [comment]
Yup, that should work, sorry for not posting it, I thought I had.

**Comment by nicocans** [comment]
Hello,
I backup'd /databases folder, I deleted app, I installed yours, I replaced new /databases with old one, but after launching the new app, it says the data are empty ("Pas 'articles"). Also, I still don't see your button "Purger la base de données". did I miss something?

**Comment by di72nn** [comment]
Does 'Upload offline URLs' button work?
I thought you were going to backup all the data. Not sure what may go wrong if you backup only `databases` directory.

If the upload button does not work, I may advise you to get URLs directly:
`sqlite3 <wallabag db file> 'select url from offline_url;'`

**Comment by nicocans** [comment]
Don't know yet if it work, did not imported links for now 

in fact, I thought "all the data" == /databases. I also have /cache,
/lib and /shared_prefs. Do I have to restore them too? 

I will try to extract offline url later, thx for the tip. 
---

​Nicolas Canseco
http://www.nitche.org/blog/
https://twitter.com/nitchesurleweb
https://friendica.nitche.org/profile/niitche [2]
http://www.dxo.com/

Le 2016-02-11 09:03, Dmitriy Bogdanov a écrit : 

> Does 'Upload offline URLs' button work?
> I thought you were going to backup all the data. Not sure what may go wrong if you backup only databases directory. 
> 
> If the upload button does not work, I may advise you to get URLs directly:
> sqlite3 <wallabag db file> 'select url from offline_url;' 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1]
https://github.com/wallabag/android-app/issues/193#issuecomment-182757151
[2] https://twitter.com/nitchesurleweb

**Comment by di72nn** [comment]
Generally, preferences are stored in `/shared_prefs` and structured data in `/databases`. Next time I recommend to use something like [oandbackup](https://f-droid.org/repository/browse/?fdid=dk.jens.backup).

You probably might want to restore `/shared_prefs` to avoid configuring the app all over again.

**Comment by nicocans** [comment]
- saved offline urls with your query;
- imported old /databases and /shared_prefs did not work, installed app from scratch.
- made a test with one offline url: it works.

I will tell you if the issue come back again. thx for yours quick feedbacks.
