### ISSUE TITLE
Show estimated reading time in the mobile app

### ISSUE THREAD

**Issue by LenzGr** [wallabag/android-app#194]
Thanks a lot for providing the Android app, I recently moved from Pocket to Wallabag and really like it! One thing that I find quite useful is the display of the estimated reading time in the web application. Would it be possible to display this information in the mobile app as well?

**Comment by tcitworld** [comment]
As soon as wallabag v2 is finish, we start work on this.

**Comment by Strubbl** [comment]
At the moment the reading time is show in the article view.
