### ISSUE TITLE
Enable tags support

### ISSUE THREAD

**Issue by LenzGr** [wallabag/android-app#195]
It would be really helpful if the mobile app would allow me to manage tags associated with an article, as well as displaying them or using them to filter my reading list.

**Comment by tcitworld** [comment]
As soon as wallabag v2 is finish, we start work on this.

**Comment by anarcat** [comment]
v2 is finished, is this being worked on now? :)

**Comment by anarcat** [comment]
should this be closed in favor of #116, actually?

**Comment by di72nn** [comment]
Closed in favor of #116.

**Comment by Strubbl** [comment]
@anarcat no, currently it is not being worked on. We need help with the API wrapper in Java.
I have started work in the repo https://github.com/Strubbl/jWallabag and i would appreciate a PR. Maybe we can move the repo to the wallabag organization later on
