### ISSUE TITLE
Add support for Multi Window Mode (Multitasking)

### ISSUE THREAD

**Issue by he7d3r** [wallabag/android-app#196]
It seems the feature
http://www.samsung.com/ie/support/skp/faq/1079693
is not available for the wallabag app.

**Comment by tcitworld** [comment]
Will add ! [Bookmark](http://stackoverflow.com/a/17514132)

**Comment by nr458h** [comment]
As a user with lineageos 16 this is working fine for me.
Do we still need this issue?

**Comment by tcitworld** [comment]
Nope, not required anymore on modern Android versions
