### ISSUE TITLE
Wrong article counter during import from Pocket

### ISSUE THREAD

**Issue by Suncatcher** [wallabag/android-app#198]
Hi there,
Well, I am trying to test the bug #97 and once again noticed that Framabag Wallabag inconsistently treats my Pocket article list. While in fact it has 504 articls, Wallabag import recognizes 1010 there, which is obviously wrong.
This is Pocket file in question (extension changed to TXT for compliance with Github)
[ril_export.txt](https://github.com/wallabag/android-app/files/147711/ril_export.txt)

**Comment by tcitworld** [comment]
Indeed. I'll test your file on v2 to see how it goes.

**Comment by Suncatcher** [comment]
![image](https://cloud.githubusercontent.com/assets/6388034/13344536/ea2ad602-dc67-11e5-8412-16101e91590c.png)

**Comment by Suncatcher** [comment]
Was this issue resolved?

**Comment by tcitworld** [comment]
Related to v1, not applicable to v2 (Framabag will soon be updated).

**Comment by Suncatcher** [comment]
OK.
