### ISSUE TITLE
Text justification as an option

### ISSUE THREAD

**Issue by raphaelbastide** [wallabag/android-app#202]
I don’t feel comfortable reading an article with justified text, because the typographic balance is quite bad on the paragraph. Most of the reading app, text-based apps and blog, books etc. doesn’t justify text for ergonomic reasons. I can understand it is a matter of taste, so I suggest to add the option between `left`,`justify`.

**Comment by NerosTie** [comment]
Any news about this issue?

**Comment by Strubbl** [comment]
No. It would be nice if somebody can submit a pull request for this issue.

**Comment by di72nn** [comment]
Done.
