### ISSUE TITLE
Export articles as pdf embedded in the app

### ISSUE THREAD

**Issue by giovi321** [wallabag/android-app#216]
I think it would be a great feature to add a button to download the articles as a pdf (or mobi, or whatever format). The button already exists in the web interface, maybe it wouldn't be too hard to implement in the app.

**Comment by Strubbl** [comment]
Sorry, i do not understand the use case. Why sould anybody want to do this on a phone?

**Comment by giovi321** [comment]
You can download the pdf when boarding on the plane and then read it during the flight.

**Comment by Strubbl** [comment]
Ah okay, i under stand Pdf downloading should be possible. 

In my opinion I would rather like the app to support an offline mode more robustly. For me, then there would not be the need to download PDFs.

**Comment by giovi321** [comment]
I totally agree with you, but implementing a pdf download button takes probably a few minutes (since it's just a link), while an offline reaing option, I believe, would take much longer.

**Comment by Strubbl** [comment]
Unforunately it was more than a few minutes to get this working.
