### ISSUE TITLE
Write documentation about v2 app

### ISSUE THREAD

**Issue by nicosomb** [wallabag/android-app#217]
Please add a new page here: https://github.com/wallabag/wallabag/tree/master/docs to explain how to configure the application.

**Comment by Lokesh-Krishna** [comment]
Any guide that I can refer to to help me write this?

**Comment by Strubbl** [comment]
There is already some documentation: https://github.com/wallabag/doc/blob/master/en/apps/android.md

This can be improved of course. But this issue is very unconcrete. Therefore i suggest to make specific requirements for documentation or close the issue
