### ISSUE TITLE
trailing slash handling in Wallabag instance URL

### ISSUE THREAD

**Issue by Strubbl** [wallabag/android-app#222]
According to the comments in https://github.com/wallabag/android-app/issues/203#issuecomment-212333264 several users had the problem that if they entered a wallabag URL with a trailing slash, the app did not work. 

Do we want to handle the trailing slashes in the URL somehow?

If yes: how? only remove it and then save the URL to the settings? Does removing the trailing slash maybe cause any side effects?

**Comment by di72nn** [comment]
Improved in `master`.
