### ISSUE TITLE
filter list by tag

### ISSUE THREAD

**Issue by foxmask** [wallabag/android-app#230]
It will be helpful if we could filter our list of articles by tag

**Comment by Strubbl** [comment]
Oh yes! But i want to see that feature in the web interface of v2, too. It's still missing there.

**Comment by foxmask** [comment]
I did not notice that yet.
I'll open a ticket too if i dont find the feature too ;)

**Comment by Strubbl** [comment]
Have you opened a ticket at wallabag already? Can you please reference it here. If it is closed in future and we have API support in android app, we work on this issue here.

**Comment by Strubbl** [comment]
We need https://github.com/wallabag/wallabag/issues/1984 to be fixed to implement this.

**Comment by anarcat** [comment]
https://github.com/wallabag/wallabag/issues/1984 is fixed now, so this has no blocker, except mayb tags support in the first place, see #195 or #116.

**Comment by di72nn** [comment]
Closed in favor of #116.
