### ISSUE TITLE
tag creation 

### ISSUE THREAD

**Issue by foxmask** [wallabag/android-app#231]
It could be helpful to be able to create tag from the app / or even when we add a post

**Comment by Strubbl** [comment]
There are a lot of open requirements to implement this feature:

It needs wallabag v2.1 https://github.com/wallabag/wallabag/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.1.0
especially https://github.com/wallabag/wallabag/issues/1984

And of course it needs our app to use the API. Currently we use the RSS feeds and not the API.

**Comment by huegelc** [comment]
This feature would be great

**Comment by anarcat** [comment]
this seems like a dupe of #195 or #116. the API is ready though...

**Comment by di72nn** [comment]
Closed in favor of #116.
