### ISSUE TITLE
Preview pictures

### ISSUE THREAD

**Issue by foxmask** [wallabag/android-app#232]
When i get a article  i dont see the image that illustrates this post , image i xan see from my wallabag instance. 

Exemple of article that does not display image http://sixactualites.fr/high-tech/hubble-etonne-decouverte-dune-lune-gravitant-autour-de-planete-makemake/27331

**Comment by Strubbl** [comment]
The preview picture is not part of the content of that article saved in the database. It is saved separetly (separate column in the DB). 

If we do not get the preview picture within the content of that article delivered through the RSS feed, there is no chance for the app to display that picture. 

This is not even possible with the API of Wallabag v2 by now. If you want to have that preview pic somehow included, can you please address it in the wallabag repository. Maybe the entry delivered by the API can get extended by the preview picture. 

(i hope you understand what i want to say. )

I close this issue for now, cause it is not possible to implement that at the moment. Feel free to reopen it, if we somehow can get the image from Wallabag API (and RSS feed maybe).

**Comment by tcitworld** [comment]
> This is not even possible with the API of Wallabag v2 by now. If you want to have that preview pic somehow included, can you please address it in the wallabag repository. Maybe the entry delivered by the API can get extended by the preview picture. 

The API *should* return the preview picture `preview_picture`

**Comment by Strubbl** [comment]
@tcitworld You are referring to the section "Adding your first entry". This is the result you should get when you add an entry. I did not test that. But i tested /api/entries.json and there the article items do not have the preview picture in Wallabag v2.0.3

**Comment by tcitworld** [comment]
Not sure about it, but when you get an individual entry you should get it.

**Comment by Strubbl** [comment]
It would also make sense to get when retrieving a couple of entries. The preview picture would be the only data that's missing ATM.

**Comment by nicosomb** [comment]
We need to check because in the Windows Phone app (ping @jlnostr), preview pictures are available.

**Comment by Strubbl** [comment]
Preview pictures (link to it) are already available via API. Sorry, I overlooked that.

**Comment by jlnostr** [comment]
Well, the issue can be closed now, right?

**Comment by anarcat** [comment]
@jlnostr no: the preview is in the API, but is not used yet by the app.

**Comment by ngosang** [comment]
I really need this feature. There are many articles in which the most important info is in the preview_image.
Example => http://www.economist.com/blogs/graphicdetail/2017/01/daily-chart-19?fsrc=rss

**Comment by Strubbl** [comment]
> Example => http://www.economist.com/blogs/graphicdetail/2017/01/daily-chart-19?fsrc=rss

This should be in the content, not only in the preview image. So maybe the content expression is wrong

**Comment by ngosang** [comment]
Without image catching

line 143 @ ReadArticleActivity
```
        String previewPicture = "<br><img src='" + mArticle.getPreviewPictureURL() + "'/><br>";
        int estimatedReadingTime = mArticle.getEstimatedReadingTime(settings.getReadingSpeed());
        htmlContent = getString(R.string.content_estimatedReadingTime,
                estimatedReadingTime > 0 ? estimatedReadingTime : "&lt; 1")
                + previewPicture + htmlContent;
```

**Comment by nicosomb** [comment]
I want this feature 😍

**Comment by returntrip** [comment]
Would be great to have pls!

**Comment by ngosang** [comment]
@di72nn could you make it for us? :heart: 
Would be nice to have this settings:
* Show preview pictures?
* Download preview pictures and save them for offline usage? (Maybe this option is not necessary, just reuse the "chache images" option)
* Display preview picture only if the image URL is not in the article, so we don't show duplicate images.

**Comment by di72nn** [comment]
There's a lot of stuff to implement:
 * Since "image caching" is optional and the previews is an unrelated feature, downloading of previews should be a completely separate process (some of the code can be reused of course).
 * The layout needs to be updated to incorporate previews. And I'm not into Android UI.
 * It is likely that lists loading should be made asynchronous (finally).

No estimates.

**Comment by ngosang** [comment]
By now, implementing an option to show/hide the preview image at the beginning of the article content is sufficient for most people.
![screenshot_2017-05-31-08-28-55](https://cloud.githubusercontent.com/assets/10577978/26618670/6f1e3bdc-45db-11e7-8832-39de477f7fd9.png)

**Comment by di72nn** [comment]
I'm not sure that the preview picture should be shown in the article view, but it seems the web version does exactly that. So here you go: #539. I don't check for duplicates too.

**Comment by Strubbl** [comment]
Should work with commit b97b4a3175eb55f783d1ff60f40e73316a6acfbc on master.
Thanks @di72nn
