### ISSUE TITLE
Pressing sync button should start a new sync

### ISSUE THREAD

**Issue by Mistress-Anna** [wallabag/android-app#247]
When the connection is unstable, if I start a sync, it may get stalled and never end in timeout, even if I get a better connection aftewards. Worse, if I press the sync button later, it complains a sync is already running, though it'll never end. The only solution then is restarting the app.

**Comment by Strubbl** [comment]
I experienced that behaviour, too. Can you give a process how to reproduce this behaviour?

**Comment by tcitworld** [comment]
@Mistress-Anna @Strubbl Is this still relevant with version 1.12 ?

**Comment by Strubbl** [comment]
No, i cannot reproduce this issue with the current alpha release. Update process runs very stable now, thanks to @di72nn
