### ISSUE TITLE
Pas d'accès aux Settings sur Galaxy Tab Pro

### ISSUE THREAD

**Issue by michelleunen** [wallabag/android-app#26]
Impossible de configurer l'extension sur une tablette Samsung Galaxy Tab Pro.
Lorsqu'on appuie sut la touche menu à côté du bouton home, c'est le gestionnaire des tâches qui s'ouvre et pas le menu (voir screenshot joint)
![galaxytabpro](https://cloud.githubusercontent.com/assets/1244406/3498607/0559e240-05f7-11e4-87c7-3b58c9d9b416.png)

**Comment by tcitworld** [comment]
Not relevant anymore (design changed in beta builds)
