### ISSUE TITLE
FR: Page Scrolling

### ISSUE THREAD

**Issue by gerroon** [wallabag/android-app#264]
Hi

It would be nice if we could scroll down or up by certain amounts (set in the pref) by tapping the left or the rright of the screen. Screen scrolling is a big issue with Eink devices due to contant refreshing.

thanks

**Comment by Strubbl** [comment]
this issue duplicates your ticket #168. If not, can you please clarify the difference and reopen.

**Comment by gerroon** [comment]
@Strubbl 

It looks like I made a similar request before ;)
