### ISSUE TITLE
Wallabag app crash while refresh

### ISSUE THREAD

**Issue by monsieurpouet** [wallabag/android-app#267]
Hi,

With the 1.9.9.4 version, the wallabag apps crash when I want refresh. :/ Maybe an issue.
I've Lollipop for One Plus X
Bye

**Comment by di72nn** [comment]
Can you try [1.9.9.4b](https://github.com/wallabag/android-app/releases/tag/1.9.9.4b)?

**Comment by tcitworld** [comment]
Please note that F-Droid didn't build this release (they do not seem to allow such release version names)

**Comment by DoumeDuSud** [comment]
La version b fonctionne pour moi
Galaxy Note 2 android 4.4 wallabag 1.9

Part contre la version de f-droid ne fonctionne pas pour la synchronisation et l'envoies d'article au serveur de wallabag

**Comment by mentat-fr** [comment]
I've same bug with One Plus X and it's fix with the 1.9.9.4b (need to uninstall the F-Droid version).

**Comment by zertrin** [comment]
Why not doing a release 1.9.9.5, or said differently, why doing a 1.9.9.4**b** release.

To put the question more generally, what is the version number policy here?

It's sad to force us to use Google Play for a fix release that fixes a quite important bug...

Is there an ETA for the next release that will be compatible with F-Droid?

**Comment by tcitworld** [comment]
Sorry. I didn't intend for so much time to pass before a new version. Will do very soon.

**Comment by Strubbl** [comment]
@tcitworld can you please spend some words on the version numbering?

**Comment by di72nn** [comment]
&lt;off-topic&gt;
We can include beta builds to F-Droid, but I'm not sure whether it is desired behavior.

Currently new builds are added when a new git-tag is added:
[`Update Check Mode:Tags ^v?[0-9.]*$`](https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/fr.gaulupeau.apps.InThePoche.txt) (beta tags does not match the pattern).
The pattern may be updated to suite our needs.

F-Droid supports "beta" builds (which are available to download, but not suggested as recommended, e.i. "normal" builds are installed *by default* even if there are newer "beta" builds available), but it seems to be impossible to automate (currently).
&lt;/off-topic&gt;

**Comment by di72nn** [comment]
Fixed in 1.9.9.5.
