### ISSUE TITLE
Error 500 when deleting an article

### ISSUE THREAD

**Issue by giovi321** [wallabag/android-app#271]
I am running wallabag 2.0.1 on my server, and I am running the app version 1.9.9.4b (26) on a Cyanogen OS 12.1 device.
When I delete an article it gets successfully deleted but it gives the following error:

> Connection Failure
> Request unsuccessful; response code: 500, response message: Internal Server Error

**Comment by di72nn** [comment]
First of all I suggest to update the server (wallabag 2.0.5 is the latest version). It is most likely server-side issue.

**Comment by giovi321** [comment]
I'll try this and give you a feedback.

**Comment by giovi321** [comment]
You were right. Upgraded to 2.0.5 and no more error 500.

**Comment by Strubbl** [comment]
just for reference: https://github.com/wallabag/wallabag/issues/1924

Should be fixed since wallabag 2.0.2
