### ISSUE TITLE
Use material design icons for sync and add buttons

### ISSUE THREAD

**Issue by The0x539** [wallabag/android-app#272]
https://design.google.com/icons/#ic_sync

https://design.google.com/icons/#ic_add

**Comment by Strubbl** [comment]
I like the idea. Are you going to implement that please?

**Comment by The0x539** [comment]
I currently have no experience whatsoever with Android development, but since it *should* be nothing more than replacing image files, I might be able to.

**Comment by Lokesh-Krishna** [comment]
I'd like to work on this. Is a sync button really necessary though when you can simply pull down on the list to sync?

**Comment by di72nn** [comment]
The sync button performs "full sync", pull-to-refresh performs "fast sync". So we need both for the moment.

**Comment by Lokesh-Krishna** [comment]
Thanks for the reply. 
Regarding updating the icons, is replacing resources all that needs to be done? I can do that this QKSMS when I have access to my laptop once again.

**Comment by di72nn** [comment]
We probably want to move from the old PNG icons to the new SVG ones. I don't remember whether it takes extra work. Probably just file replacement.

**Comment by Lokesh-Krishna** [comment]
I'll definitely work on this then.
