### ISSUE TITLE
[Android 6] "Erreur de connexion" à la synchro

### ISSUE THREAD

**Issue by TalesOfTea** [wallabag/android-app#276]
_English translation below._

J'ai fait la MAJ vers Android 6 hier et depuis, je rencontre le problème suivant.
Sur l'appli, j'ouvre un article, je le tick pour archivage, et lors du retour sur l'index des "Non lus", la pop-up suivante apparaît :
"
Erreur de connexion
Impossible de se connecter :
L'identifiant et le mot de passe doivent être erronés
"
Si je vais dans les params de l'appli et que je fais "Tester la connexion", j'ai la pop-up suivante qui apparaît: 
"
Échec
Impossible de se connecter. Vérifiez votre identifiant et votre mot de passe.
Corde d'erreur: 2
"
Pas de problème de connexion sur l'appli Web, je n'ai donc pas changé mes IDs à mon insu :)

Besoin d'infos complémentaires ?

_**English translation (tcit)**_

I made the update to Android 6 yesterday and since then, I encounter the following issue : 
On the app, I open an article, I mark it for archive, and when returning on "Unread" index, the following popup shows :

> Connection error
> Could not login
> ID and password must be wrong

If I go the the app settings and I test connection, I have the following popup showing : 

> Failure
> Unable to connect. Check ID and password.
> Error code: 2

No issue trying to connect to the web app, so I didn't change my ids not knowing. :)

Need extra informations ?

**Comment by di72nn** [comment]
Was it a clean install (or restored from a backup)?
What server do you use (what version, if self-hosted)?

**Comment by TalesOfTea** [comment]
Clean install (of Android 6, if that's what you're asking about)
Using [the Framabag instance of Wallabag](https://framabag.org/)

**Comment by tcitworld** [comment]
I translated your original message. Please use english from now on. ;-)

**Comment by di72nn** [comment]
Have you entered "Feed credentials" manually? Because you can download articles from server with only feed credentials, but to perform most of the operations (mark as read, favorite, etc.) you need valid username and password.
There is a big chance you actually have an incorrect username or password in your settings.

**Comment by TalesOfTea** [comment]
"Have you entered "Feed credentials" manually?" --> nope, as far as I remember, I used the appropriate button to retreive them automatically, and it worked like a charm.

Actually, everything worked perfectly fine until yesterday when I upgraded to Android 6 ; it's already a while now I use the app, and never had any trouble before.

I've just tried to unistall/reinstall the app, cleared all the params and set only the URL/ID/password, and still get the very same errors. Connection test keeps returning the same connection error, and the app "can't find the ids" when I try to obtain the feed informations.

Anything I could have done wrong ? Some more suggestions ?

**Comment by Strubbl** [comment]
@TalesOfTea hav you checked the known limitations, e.g. 2FA? http://doc.wallabag.org/en/master/user/android.html#known-limitations

Please also make sure your wallabag URL does not end with a slash.

**Comment by di72nn** [comment]
@TalesOfTea also check that you have a correct username in wallabag URL.

**Comment by Strubbl** [comment]
@di72nn @TalesOfTea Maybe you post your URL here

**Comment by TalesOfTea** [comment]
@Strubbl I have no idea what version of Wallabag is used by Framabag. The URL does not end with a slash, and after checking the known limitations, everything appears to be OK.
@di72nn the username in the URL seems correct (I guess it is, if not, would it have ever worked ?).
Here's the url: http://www.framabag.org/u/c3zr

**Comment by di72nn** [comment]
Try https://www.framabag.org/u/c3zr or https://framabag.org/u/c3zr

**Comment by TalesOfTea** [comment]
Success, works properly again now ! Thanks !
Out of curiosity, how's it possible that upgrading Android makes necessary to switch from http to https ?

**Comment by di72nn** [comment]
AFAIR, the app does not support redirects on any version of Android, so something else might go awry before you reinstalled the app.

**Comment by TalesOfTea** [comment]
Ok. 
Thanks again, I close the issue :)

**Comment by tcitworld** [comment]
Hi,
Framabag has been configured to redirect http to https automatically.

**Comment by Strubbl** [comment]
The solution is exactly what is described in here http://doc.wallabag.org/en/master/user/android.html#ssl-tls-encryption

**Comment by nayessiva** [comment]
I had exactly the same problem ; dealing with framabag and android. Though i didn't upgrade android ! the HTTPS was the exact solution ! :) thanks !
