### ISSUE TITLE
Support redirection in given wallabag URLs

### ISSUE THREAD

**Issue by Strubbl** [wallabag/android-app#277]
When we enter a URL in the settings, which redirects to another URL, we cannot login and get the user credentials for the feed. 
E.g. in issue #276 there is a redirection described, which just redirects from http to https. The app shall support this.

**Comment by Strubbl** [comment]
This issue is already fixed. 

If i enter a http url and click in the connection wizard on connect, i get a popup that it is better to use the redirected URL (https one), which i can confirm or abort.

**Comment by di72nn** [comment]
For the record: it still doesn't work if a user ignores the suggestion or enters URL manually in settings.
