### ISSUE TITLE
Issue when adding any page on the app after the app has timed out once

### ISSUE THREAD

**Issue by Flore-mozfr** [wallabag/android-app#278]
Context : I have a framabag instance. Wallabag is installed on my android phone and my android tablet.
I use it on my tablet at home without issue (steady wifi and FFTH at home).
However, in the bus on my way to work, the connection is very bad and there are a lot of timeouts (different from a 'no service' like in the metro, which causes no bug).
If I access wallabag during one of those timeouts, it will cause issue to happen. And later, I can't save an article using my phone, because "ID or password are incorrect". Which it is not of course, because I did not change them.
Proofs that they are not incorrect:
- I can still access wallabag from my tablet and computer with the same old ID/password
- I can still access wallabag on my phone and it updates correctly. Ex: I add an article using my computer, refresh my wallabag on the phone -> it works! so it manages to read the data on the server.
- If I delete the wallabag app from my phone, reinstall it, use the same ID/password and token... I can add articles using my phone. Until the next timeout (and then it's the same all over again).

If you need any logs or more information, just tell me how to get it and I will provide it.

**Comment by Flore-mozfr** [comment]
![tmp_19643-screenshot_20160624-102631828813773](https://cloud.githubusercontent.com/assets/6987429/16332892/c14ad842-39f8-11e6-9b3e-ba26e2e6a407.png)

When I want to save a page

**Comment by di72nn** [comment]
Perhaps `OkHttpClient` somehow gets broken after a timeout error (because the app doesn't save any other connection state (or at least I keep overlooking it)). It probably should be tested it with the latest version of `okhttp` (`3.2.0` -> `3.3.1`).

@Flore-mozfr which version of the app do you use? Does the error happen for other actions ("mark as read", etc.; **except** updating feeds - these updates use different authorization mechanism), not only for "add article"? Do these failed requests finish in a short time (or maybe it timeouts every time)?

**Comment by Flore-mozfr** [comment]
I'm using wallabag 1.9.9.5 (27).
I get the same error for mark as read, star articles, delete... Everything except 'update'.
It happens really quickly : a few seconds, everytime (no longer than loading a webpage or refreshing twitter). I checked the connection before performing these actions and it was H+ (and working, checked by refreshing my twitter feed).

Yes it seems to me that something gets broken once there was a timeout and I can't get it fixed without deleting the app and reinstalling it (and wiping whatever causes the issue in the process).

**Comment by di72nn** [comment]
@tcitworld can you build an APK with the latest `okhttp` version?

@Flore-mozfr you may try to kill the app (or reboot your device) instead of reinstalling it.

**Comment by tcitworld** [comment]
Here is an APK just build.

[app-release.apk.zip](https://github.com/wallabag/android-app/files/333046/app-release.apk.zip)

**Comment by Flore-mozfr** [comment]
@di72nn I killed the app and rebooted the device -> no effect, I really need to reinstall it to fix this issue.

**Comment by di72nn** [comment]
@Flore-mozfr will you try the APK provided by @tcitworld? If you can get logcat output, it may shed some light on the situation. Otherwise it is still a mystery to me.

**Comment by Flore-mozfr** [comment]
I just installed the apk and it is no better...
Now it does not work even if I reinstall it (even with the play store version). When I want to test the connection (in the settings), I get the same message but updating the feeds still works.
I'll get a logcat tonight

**Comment by di72nn** [comment]
@Flore-mozfr try the latest version (you can install it from [f-droid](https://f-droid.org/repository/browse/?fdid=fr.gaulupeau.apps.InThePoche), download [apk](https://github.com/wallabag/android-app/releases/latest) or get testing version from [Google Play](https://play.google.com/apps/testing/fr.gaulupeau.apps.InThePoche)).

**Comment by Flore-mozfr** [comment]
Hi @di72nn I updated it yesterday evening when the notification popped on my screen. And I'm happy to tell you that it works, now. I installed it from F-droid, had to first delete the previous version because of authentication keys (not the only app with which it happened) and installed and finally it worked.
Good work, team!

**Comment by di72nn** [comment]
Nice to hear that the problem is resolved.
