### ISSUE TITLE
Add article doesn't work with Wallabag 2

### ISSUE THREAD

**Issue by kpn3m0** [wallabag/android-app#285]
Steps to reproduce:
* install wallabag 2.0.6
* install android app 1.9.9.5
* enter needed credentials
* synchronize
  * articles are showed
* try to add new article via the mobile app
* the app calls '"GET /bookmarklet?url=http://wikipedia.fr HTTP/1.1" 302 259 "-" "okhttp/3.2.0"'
* the article is not saved to wallabag

**Comment by di72nn** [comment]
`302` suggests redirection, which may not be handled well. If your server uses `http -> https` redirection use `https` in settings, same applies to redirects like `www.hostname -> hostname`, `hostname -> www.hostname`, etc.

Did you try to 'Test connection' in settings? Articles being shown does not guarantee all credentials being valid (articles sync is done using feed credentials, article add is done using username and password).

**Comment by kpn3m0** [comment]
I found the problem.
It was the web server configuration. The rewrite RegEx was wrong for lighttpd.

```
"^/([^?])(?:\?(.))?" => "/app.php?$1&$2",
```

I see you already corrected it: http://doc.wallabag.org/en/master/user/installation.html

**Comment by tcitworld** [comment]
Closing then.
