### ISSUE TITLE
Prefill android app with user & server information

### ISSUE THREAD

**Issue by tcitworld** [wallabag/android-app#290]
Idea from https://github.com/nextcloud/android/issues/248

**Comment by AndyScherzinger** [comment]
work in progress https://github.com/nextcloud/android/pull/253

**Comment by AndyScherzinger** [comment]
@tcitworld can you tell me which of your activities would need to be launched and which information you would like to transmit? If I find the time I might be able to provide you a raw implementation :grin:

**Comment by tcitworld** [comment]
It should be the [ConnectionWizardActivity](https://github.com/wallabag/android-app/blob/master/app/src/main/java/fr/gaulupeau/apps/Poche/ui/preferences/ConnectionWizardActivity.java) activity.

cc @Strubbl & @di72nn

**Comment by AndyScherzinger** [comment]
Implementation for wallabag Android app to be found here: https://github.com/wallabag/android-app/pull/300

**Comment by di72nn** [comment]
@tcitworld @Strubbl
Do we want to include more parameters into "magic url"?

Parameter | Details
--- | ---
Wallabag URL | Done.
Username | Done.
Password | Sensitive information; also needs to be escaped.
Server version | Not important: auto-detectable.
Feeds id | Nothing special.
Feeds token | Somewhat sensitive.
HTTP Auth | Can it be detected/provided?

**Comment by AndyScherzinger** [comment]
@tcitworld @Strubbl @di72nn you can also create server different intent filters (on different activities), like

 	wallabag://login/...
 	wallabag://feed/...

**Comment by tcitworld** [comment]
* Password can't be passed since it is a sensitive information and we don't have it anyway.
* Not sure about HTTP auth
* I would not consider the feeds id/token for now but we definitely should provide the oauth id and tokens when the android app will use them.

It's possible that we use more intents in the future.

**Comment by AndyScherzinger** [comment]
#300 has been merged :tada:
