### ISSUE TITLE
Wallabag for Android 1.9.9.5 (27) - Exception IO

### ISSUE THREAD

**Issue by jbvh173** [wallabag/android-app#293]
wallabag 1.9.9.5 (27)
framabag account
synchronization failed with error
Erreur lors du chargement du flux: Exception IO lors de la connexion

new articles saved from the android app are stored on the server and visible in firefox for example
but not visible in the app
connexion test from the parameters menu is successful
it has worked before

**Comment by di72nn** [comment]
Is this problem constant? Do actions like "mark as favorite" work?

**Comment by di72nn** [comment]
Please reopen if you can reproduce the problem with the latest app version.
