### ISSUE TITLE
Images not shown in the app

### ISSUE THREAD

**Issue by KuenzelIT** [wallabag/android-app#295]
Hey,

the Android app does not show the images for the following site:
https://newark1.com/iphone-7-wireless-consumerism-marketing

In the browser everything is fine and images are shown for other articles, but not this one. Here there is just a big white box with the title on top.

Any clue why this happens?

**Comment by di72nn** [comment]
Works fine for me. What wallabag version (server) do you use?

**Comment by KuenzelIT** [comment]
I'm using 2.0.7 currently. Gonna update soon and see if that fixes it.

**Comment by di72nn** [comment]
Please reopen if you can reproduce the problem with the latest versions of the app and the server.
