### ISSUE TITLE
Background sync only with activated wifi

### ISSUE THREAD

**Issue by Strubbl** [wallabag/android-app#302]
From the settings screen i cannot guess if background sync is only working if i have wifi active or even when i am on mobile data. Is this already considered?

**Comment by di72nn** [comment]
Any available type of connection is used currently.

Should "Only on Wi-Fi" checkbox suffice?

**Comment by Strubbl** [comment]
Yes

**Comment by di72nn** [comment]
Closed in favor of #346.

**Comment by Strubbl** [comment]
Ups, sorry. I forgot that i already created that issue. Thanks for keeping the issue list clean!
