### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by di72nn** [wallabag/android-app#308]
It's the main project page on github. Update and include some useful information.

**Comment by jsroyal** [comment]
Can you @di72nn  please me little bit more about or give link  so I can contribute here. :+1:

**Comment by di72nn** [comment]
The idea is to add some more useful information to the [README](https://github.com/wallabag/android-app/README.md).

Here are some ideas:
 * Detailed description.
 * Screenshots.
 * Features.
 * Describe permissions usage.

**Comment by Lokesh-Krishna** [comment]
@jsroyal Are you working on this currently? Please do let me know for I would like to if you aren't.

**Comment by Lokesh-Krishna** [comment]
@di72nn Could you look into #388?

**Comment by jsroyal** [comment]
@Lokesh-Krishna  sure go ahead. Sorry, I'm some other project work.Thanks

**Comment by Lokesh-Krishna** [comment]
Can this be closed now or are does there remain something to be added?
