### ISSUE TITLE
Synchronisation

### ISSUE THREAD

**Issue by foxmask** [wallabag/android-app#309]
With the last beta version, when we set the synchronisation to be done each hour (we can see the image of the synchronisation in the notification status bar) and to be done once we open the application, then when we launch the app, nothing happened, I have to request of synchronisation by hand to get the articles to finnally get them.

With all that settings I made, I supposed this will be done automatically once I opened the app.

**Comment by di72nn** [comment]
What type of sync did you choose? "Fast" or "Full"? If you select "Fast", then only new articles in the Unread feed will be fetched. "Full" sync will re-download all feeds.

**Comment by foxmask** [comment]
I see "fast" ; I didnt change it, it should be the default value ?

**Comment by di72nn** [comment]
Try selecting "Full".

**Comment by foxmask** [comment]
nothing better

**Comment by di72nn** [comment]
Can you provide logs?

**Comment by foxmask** [comment]
No, it looks like that the application does not premits that.

**Comment by di72nn** [comment]
#310 will probably fix it.

Currently you may try to:
 1. open Settings,
 1. uncheck "Enable auto-sync", don't change any other options,
 1. close Settings (go to the main app screen),
 1. open Settings,
 1. check "Enable auto-sync", don't change any other options,
 1. close Settings.

It is not guaranteed to work, but worth a shot.

**Comment by foxmask** [comment]
Looks like ok now. Thanks
