### ISSUE TITLE
Actions for articles removed on server are stuck in offline queue

### ISSUE THREAD

**Issue by di72nn** [wallabag/android-app#319]
1. Remove an article on server.
2. Try to remove / favorite / mark as read it in the app.

Expected result: no errors, article is changed offline until "full sync" is done (probably).

Actual result:
"Unknown error" is shown. The offline queue sync is blocked (no future changes will be synced until the erroneous action is somehow removed).

Cause: server (v2) responds with HTTP status code `404` for any action with removed articles. (I did not test it against v1 server).

This is pretty serious, because there are no way for user to get rid of it except to clear the app data (at least I'm not aware of any other way).

**Comment by tcitworld** [comment]
As of now, I would advise to ignore this issue and focus on the app using the wallabag v2 api (that would fix this issue). I think wallabag v1 servers compatibility is not a required thing.

**Comment by tcitworld** [comment]
cc @Strubbl for advice

**Comment by Strubbl** [comment]
I would need help in bringing the task for the wbg v2 api wrapper forward. From my point of view we can start from scratch or move my project to the wallabag organization.
