### ISSUE TITLE
creating a new account still shows old articles

### ISSUE THREAD

**Issue by Strubbl** [wallabag/android-app#320]
On current master 6db23507616e6be00d29324834277be2cfa24fc2 I have the issue, that i 

- started the connection assistant
- created a complety new wallabag instance
- after finishing connection setup i got to the article list,

but article list show the old entries of my other wallabag instance. Only after a full refresh via the reload button on the main screen i get the article list from my new instance

**Comment by tcitworld** [comment]
So finalizing the assistant should clear data, I guess.

**Comment by di72nn** [comment]
Should I implement similar behavior for cases when user changes username/url/etc. in settings?

**Comment by Strubbl** [comment]
@di72nn I do not know if i understand you question right. Currently with #324 the "wipe db" function is only triggered on successful connection wizard? And you are asking if this wipe db function should be triggered when the user changes one of username/url/etc. in settings manually without the connection wizard? Then i would say yes. 
But in which cases exactly? When we have a change in 

- url
- user name
- wallabag version

But not on password change, or? And how about token change? Or for simplicity on every connection parameter change?

**Comment by di72nn** [comment]
> Currently with #324 the "wipe db" function is only triggered on successful connection wizard? And you are asking if this wipe db function should be triggered when the user changes one of username/url/etc. in settings manually without the connection wizard?

Both correct.

I was thinking about:
 * URL.
 * Username.
 * HTTP Auth username (e.g. for YunoHost users).
 * Feeds User ID.
Not sure about wallabag version.
Password and token change don't switch to different user by themselves, so I would ignore it.

**Comment by di72nn** [comment]
Fixed.
