### ISSUE TITLE
font in tables in dark theme is black and not white

### ISSUE THREAD

**Issue by Strubbl** [wallabag/android-app#326]
if we have a table in the wallabag article and use the dark theme, it is hard to read the black font on the gray background. I think the font color should be the same as in the usual paragraphs.

![screenshot_20161015-004948](https://cloud.githubusercontent.com/assets/97055/19410588/1d6b953a-92f0-11e6-85df-5e5428cd6030.png)

**Comment by di72nn** [comment]
Closed in favor of #559.
