### ISSUE TITLE
add Dependency Tests tests via dependencyci.com

### ISSUE THREAD

**Issue by Strubbl** [wallabag/android-app#329]
I would like to add dependency tests to this app via the service dependencyci.com. What do you think? I already added my personal repo of this app for testing the service. Please see here:
https://dependencyci.com/github/Strubbl/wallabag-android-app

Further information what test are running:
https://dependencyci.com/docs#tests

What do you think about adding dependency tests?

PS: The admin of this repo would need to authorize dependencyci to allow repo access.

**Comment by tcitworld** [comment]
Not sure it helps a lot. :(

**Comment by di72nn** [comment]
I agree with @tcitworld - the platform seems to have a bunch of its features as "Coming soon" and it was able to say something about only 3 out of 11 libraries used in the project.
But I think it wouldn't hurt (unless it requires weird permissions for the repo).

**Comment by di72nn** [comment]
Is it relevant?

**Comment by Strubbl** [comment]
no.
