### ISSUE TITLE
Add the app as an option the "share" android menu

### ISSUE THREAD

**Issue by yvesle** [wallabag/android-app#332]
Hi
In the V1 era of this app I believe there was an option the android "share menu" that was very convenient to use. 
Could you add it back ? It it very inconvenient to add a website to wallabg without it.
Regards

**Comment by tcitworld** [comment]
It is still here...

**Comment by di72nn** [comment]
Maybe it wasn't called "Bag it!" before (~ a year ago)?

**Comment by yvesle** [comment]
Indeed it is there,  I apologise !
I guess I was looking for the "bag it" label. I use Firefox though, the share menu uses far smaller icons  than in Chrome and the wallabag one is not very legible at this scale.

for comparaison , Share menu in Chrome on a Motorola MOTO E
![screenshot_20161018-210710](https://cloud.githubusercontent.com/assets/22190569/19511661/6d5e805c-95e8-11e6-9b12-e3f2da948bed.png)

share menu in Firefox
![screenshot_20161018-210724](https://cloud.githubusercontent.com/assets/22190569/19511660/6d59882c-95e8-11e6-89f4-df88ccef890f.png)
