### ISSUE TITLE
Connection test failed (Android)

### ISSUE THREAD

**Issue by ChristianAE** [wallabag/android-app#333]
When trying to connect my self-hosted wallabag instance (Docker, using apache2 as a proxy) I get an "Connection test failed" "Wallabag service not found - check URL".

I triple checked the URL and posted it to the browser on my phone. There it opens right away. Is there something I'm missing? Is there further debugging steps I can take? Can I access a more in-depth log somewhere?

**Comment by ChristianAE** [comment]
Resolved. See https://github.com/wallabag/android-app/issues/292#issuecomment-255399333 for details.

**Comment by Strubbl** [comment]
I think this can be closed. There is still the #292 as follow up to check our app behaviour in case of redirections in a web server.
