### ISSUE TITLE
Add link from e.g. browser gives no feedback

### ISSUE THREAD

**Issue by Strubbl** [wallabag/android-app#339]
I just shared an URL from my Firefox to the wallabag app and i did not receive any feedback. So i tried again and again, but it still did not give feedback nor could i see my added article in the list of items. Not even after full sync! 

I attached the mobile to my PC and i saw the following log:

```
10-30 10:50:24.888 11950-11950/fr.gaulupeau.apps.InThePoche.debug D/BagItProxyActivity: Bagging https://www.elie.net/blog/security/fuller-house-exposing-high-end-poker-cheating-devices
10-30 10:50:24.892 11950-11950/fr.gaulupeau.apps.InThePoche.debug D/ServiceHelper: archiveArticle() started
10-30 10:50:24.901 11950-11950/fr.gaulupeau.apps.InThePoche.debug D/ServiceHelper: archiveArticle() finished
10-30 10:50:24.921 11950-11950/fr.gaulupeau.apps.InThePoche.debug D/BGService: BGService() created
10-30 10:50:24.923 11950-13790/fr.gaulupeau.apps.InThePoche.debug D/BGService: onHandleIntent() started
10-30 10:50:24.927 11950-13790/fr.gaulupeau.apps.InThePoche.debug D/BGService: serveSimpleRequest() started; action: AddLink, articleID: null, link: https://www.elie.net/blog/security/fuller-house-exposing-high-end-poker-cheating-devices
10-30 10:50:24.927 11950-13790/fr.gaulupeau.apps.InThePoche.debug D/DbConnection: using existing db session
10-30 10:50:24.931 11950-13790/fr.gaulupeau.apps.InThePoche.debug D/QueueHelper: addLink("https://www.elie.net/blog/security/fuller-house-exposing-high-end-poker-cheating-devices") started
10-30 10:50:24.931 11950-13790/fr.gaulupeau.apps.InThePoche.debug D/greenDAO: Built SQL for query: SELECT COUNT(*) FROM "QUEUE_ITEM" T  WHERE T."ACTION"=? AND T."EXTRA"=?
10-30 10:50:24.931 11950-13790/fr.gaulupeau.apps.InThePoche.debug D/greenDAO: Values for query: [1, https://www.elie.net/blog/security/fuller-house-exposing-high-end-poker-cheating-devices]
10-30 10:50:24.933 11950-13790/fr.gaulupeau.apps.InThePoche.debug D/QueueHelper: addLink() the link is already in queue
10-30 10:50:24.933 11950-13790/fr.gaulupeau.apps.InThePoche.debug D/QueueHelper: addLink() finished
10-30 10:50:24.933 11950-13790/fr.gaulupeau.apps.InThePoche.debug D/BGService: serveSimpleRequest() finished
10-30 10:50:24.933 11950-13790/fr.gaulupeau.apps.InThePoche.debug D/BGService: onHandleIntent() finished
```

Four issues i have here:
# 1Can we please give the user feedback when adding multiple times

I expected adding the link did not work, but it did. It was just added to the offline queue. Say this to me in a toast, please, like: "your url is already added to the offline queue"
# 2 Why is the url added to the offline queue?

I am online and it is still added to the offline queue. Why? From a programmers point of view i understand, but can we immediately please sync local queue items to the wallabag instance if we detect i am online?
# 3 I did not receive feedback on first adding of the url

So even when i added the article at first, i also got no feedback. A toast is needed here, too: "your url has been added to wallabag"
# 4 Open app and auto-sync

Please auto-sync offline queue when i start the app and i am online.

Should i create separate issues for my four items here?

**Comment by di72nn** [comment]
> Not even after full sync!

Good it or not, but it is called "Update all feeds" and it does not sync offline queue.
If your offline queue is not empty, there is an "Sync local changes" item in the same menu.

> 1 Can we please give the user feedback when adding multiple times
> 3 I did not receive feedback on first adding of the url

It was showing "Added" toast message when a URL was uploaded to the server, but it got broken because of the switch to queue.
My suggestion is to show "Added" toast message at the moment we receive a URL from a user, no matter can we upload it at that time or not. If something goes awry at upload time, a notification will be shown. In my opinion, showing any additional info about duplicate URLs doesn't really help.

> 2 Why is the url added to the offline queue?
> can we immediately please sync local queue items to the wallabag instance if we detect i am online

That's how it is supposed to work. If it doesn't happen, we need to investigate it.

> 4 Open app and auto-sync

Yeah, I think it should be done.

**Comment by Strubbl** [comment]
> > Not even after full sync!

> Good it or not, but it is called "Update all feeds" and it does not sync offline queue.
If your offline queue is not empty, there is an "Sync local changes" item in the same menu.

That's very nitpicking. From a user perspective i click on a button with an icon which looks like reloading, refresh or something. 

I expect all changes to be synced, which means changes i have done in the meantime on the server and of course also on the android client. It should at first try to clean offline queue in my client and after that do the full sync. So i am totally in sync. One button to rule sync at all. 

![Automate it all](http://www.kitchensoap.com/wp-content/uploads/2012/07/automate_all_the_things.jpeg)

It would be very convenient for the user, wouldn't it?



> > 1 Can we please give the user feedback when adding multiple times
> > 3 I did not receive feedback on first adding of the url

> It was showing "Added" toast message when a URL was uploaded to the server, but it got broken because of the switch to queue.
> My suggestion is to show "Added" toast message at the moment we receive a URL from a user, no matter can we upload it at that time or not. If something goes awry at upload time, a notification will be shown. 

Yes i agree, one toast is okay. ATM we have none. That is confusing.

> In my opinion, showing any additional info about duplicate URLs doesn't really help.

If the user is forgetful, like i am, and he tries adding an URL he already added, a toast would be a nice reminder. As a user, i do not have any chance to inspect, why i do not get the aforementioned "Added" toast, which i usually get. As a developer i can hook up my mobile to the PC and see, okay, i was dumb, the URL is already added. But as a user i am lost in that case.

> > can we immediately please sync local queue items to the wallabag instance if we detect i am online
> That's how it is supposed to work. If it doesn't happen, we need to investigate it.

Okay, i will follow this issue up in another request and hopefully with a logcat output.

**Comment by di72nn** [comment]
The problem mentioned in title is fixed. We need to restructure the issue.

**Comment by Strubbl** [comment]
Yes you are right. I am going to close this one and open up a new issue if needed.
