### ISSUE TITLE
No error message if nonexistent / invalid user id is used

### ISSUE THREAD

**Issue by lightonflux** [wallabag/android-app#34]
I falsely assumed that user ID is the username when i setup wallabag for the first time and didn't check it (token etc. was right). 

There was never an error that there is no such ID or that my username is in fact no number.

So i might "lost" several articles (which i wallabagged on android) because there was no error message. 

Would be great if wallabag checked if the ID is an existent number or throw an error. :)

**Comment by axelsimon** [comment]
+1 for this issue, the app is not very helpful.

When you install and run for the first time, you already have to go into the settings, the app doesn't prompt you for your login info. I agree it's not very hard to go into settings, but expecting less tech-savvy users to figure this out on their own isn't very helpful ;)

Then, you just see "User ID" with no explanation. User ID is *not the same* as "username", and that's not obvious.
"Token" is also not "password", which isn't obvious either.

I suggest adding some text between "Your wallabag URL" and "Your User ID" that reads:

>Before you can use this app, you must ensure that Feeds are enabled in your wallabag. To do so, go to the config page of your wallabag and in the Feeds section, click “generate Feed tokens”. You will then have your User ID (a number) and your token (a string of characters) which you can enter below.

I'll try to create a patch to add this :) (no promises though ;))

**Comment by tcitworld** [comment]
The latest updates (available in beta versions) changes this.

**Comment by di72nn** [comment]
#50.
