### ISSUE TITLE
font settings

### ISSUE THREAD

**Issue by muxueqz** [wallabag/android-app#35]
It really needs font resize, thx ^_^

**Comment by shtrom** [comment]
:+1:

I would extend this request by also allowing the user to change the font family (I prefer serif for long text, though I don't mind sans-serif for headers).

Same for the colours: on black and white devices, such as the Nook Simple Touch, the solarized-like colour-theme make some of the text hard to read. I have a WIP branch which hardcodes some of these changes in the CSS (shtrom@48c1c317e5bd3a58ef919b5ec7f9f5e103c82190), but it would be better if it were pulled up to the user.

**Comment by nicosomb** [comment]
Done.
