### ISSUE TITLE
Use a service like transifex for translations

### ISSUE THREAD

**Issue by di72nn** [wallabag/android-app#351]
It's not like it is our main problem, but usage of such services significantly facilitates project translation (from translators' point of view).

*Personally, I don't endorse SaaS, but in this case I find the compromise acceptable (a translation service can't tie us to itself - we can always switch to a different one or reject it).*

I checked out a few open source apps, here's the list by service:

**Transifex**:
Amaze File Manager
Autostarts
Clementine
Clementine Remote
Conversations
DAVdroid
K-9 Mail
OpenKeychain
OSMTracker
ownCloud
? VLC

**Crowdin**:
DiasporaForAndroid
OpenVPN for Android
Xabber

**POEditor**:
Loop Habit Tracker

**Weblate**:
F-Droid
Red Moon

I had no projects translated with such a service, so I have no opinion from a maintainer's point of view.
I have little experience as a translator on such platforms. For some reason I didn't like POEditor. Transifex and Crowdin seem fine, **but (if I'm not mistaken) Transifex requires a translator to join a project (requires maintainer's confirmation) before he can do anything (like see a list of lines or suggest a translation)**. Maybe it is configurable, but it works like that [even here](https://www.transifex.com/wallabag/wallabag/).
Crowdin allows anyone with an account to suggest translations. Crowdin is my personal preference so far.

**Comment by tcitworld** [comment]
I'm used to Transifex. wallabag server is starting to use Weblate (the transifex was never used). The wallabag windows app uses POEditor.

The fact that Transifex requires a maintainer's doesn't bothers me much. I however see that you need to contact Crowdin to apply to a open source licence, and that's what they say : 
> You do not have Commercial products related to the Open Source project you are requesting a license for.

Maybe this will cause issues with http://www.wallabag.it/

Whatever suits you best. ;-)

**Comment by di72nn** [comment]
> The fact that Transifex requires a maintainer's doesn't bothers me much.

Have you considered a translator's experience? A translator might want to check what exactly is not translated before deciding whether he wants to join or not. He may have spare 5 minutes to fix something in his language translation, but he can't do it until the maintainer accept him into the project. I find it very repulsive for an open source project.

> ...
> Maybe this will cause issues with http://www.wallabag.it/

Yeah, I have doubts about it too.

I'll try to check out Weblate then.

**Comment by tcitworld** [comment]
> Have you considered a translator's experience?

Totally agree with you on this. However the experience with wallabag so far is that we have one or maybe two translators for each language, not someone just passing by. :/

**Comment by di72nn** [comment]
Well, a passerby is rarely willing to edit files and use git to push his translation :/

**Comment by tcitworld** [comment]
That's also a good point. Weblate looks good enough to me.

**Comment by Strubbl** [comment]
I use POEditor in a role as translator for another project. So i do not know the process to setup a project to work with POEditor. But translating strings is fine and works the way i would wish it works. 

I do not know the other services, but i like this initiative to go for such a service for this project. Thanks for pushing that

**Comment by di72nn** [comment]
I wasn't realizing that weblate is free as in freedom. Most of the time I prefer free software to proprietary software, but I would consider an exception for translation of an open project.

I tried to translate two projects at https://hosted.weblate.org. I didn't like the UI much, but it's good enough. It's a bit too developer-oriented (translation locks, VCS-like approach). "Save" and "Suggest" buttons and "Needs review" checkbox are not obvious. The hosted version for free software seems to allow any user to replace translations (there is history, but only the latest translation is shown as "current translation"). Anonymous users can add suggestions, which is great.

I like crowdin's usability the most, but weblate (being free) is a good option.

**Comment by tcitworld** [comment]
I've send a request to hosting.weblate.org.

**Comment by nicosomb** [comment]
Maybe we can share https://hosted.weblate.org/projects/wallabag/ with android app?

**Comment by tcitworld** [comment]
Let's see what they tell us.

**Comment by tcitworld** [comment]
@di72nn @nicosomb We are at https://hosted.weblate.org/projects/wallabag/android-app/

**Comment by Strubbl** [comment]
weblate looks like a really good service for translations. Many assistant functions. Compared to poeditor this is far better.

**Comment by di72nn** [comment]
One of the options:
We can add `https://hosted.weblate.org/git/wallabag/android-app/` as a remote and merge it manually. After such merge, the project owner should be able to press "rebase" in the weblate UI (or something like that).

I also found [a handy script](https://gitlab.com/fdroid/fdroidclient/blob/master/tools/pull-trans.sh) to pull translations and squash commits like [that](https://gitlab.com/fdroid/fdroidclient/commit/f566a53efb4a0fa2dcef766098e674b4cbeac118).

**Comment by di72nn** [comment]
@tcitworld thanks for adding the app to weblate.

**Comment by di72nn** [comment]
Ok, Weblate seems to work fine so far.

**Comment by nicosomb** [comment]
I want a documentation :)
