### ISSUE TITLE
Article list does not get refreshed after full update

### ISSUE THREAD

**Issue by Strubbl** [wallabag/android-app#356]
When i start the app, and do a full refresh via that button, sometimes my article list does not get refreshed although there were new items. How do i know that? It behaves strange. I open after the update, e.g. the first article, but the opened article is a completely different than i clicked on. It is one of the new articles being freshly synced. If i go back to the list again, it is still the old list and i can repeat the behaviour.

This bug is not always reproducible and i do not know the conditions how to reproduce that. But i already had that bug several times.

I did not have that behaviour when my logcat console was nearby. But if that happens one day, i am going to provide a log for this issue. But maybe we find the issue without it.

**Comment by di72nn** [comment]
It is likely fixed in #403. Reopen if it happens again.
