### ISSUE TITLE
Bug : error to build project.

### ISSUE THREAD

**Issue by jsroyal** [wallabag/android-app#357]
In this stub of code here show error : Bold color<br>

if(android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.**N**) {
                JobInfo job = scheduler.**getPendingJob**(CONNECTIVITY_CHANGE_JOB_ID);

**Comment by tcitworld** [comment]
Sure your SDK's up-to-date ?

**Comment by jsroyal** [comment]
@tcitworld Some where else problem? MY SDK is up-to-date! yeah sure.
Please help to figure out how to solve this ?

**Comment by di72nn** [comment]
What the error message? How do you build the project? Did you try `./gradlew assembleDebug`?
