### ISSUE TITLE
Add a button to start QR-code scanner to set up the app

### ISSUE THREAD

**Issue by di72nn** [wallabag/android-app#362]
So the user doesn't have to find and launch QR-code scanner manually.

**Comment by aisbergde** [comment]
when I have seen the barcode on wallabag website I scanned it with a barcode scanner, but I only got a link and did not know what to do with the link.

**Comment by di72nn** [comment]
The app handles `wallabag://` URI scheme. "Open browser" button in [Barcode Scanner](https://f-droid.org/repository/browse/?fdid=com.google.zxing.client.android) allows to open the link, which is then automatically handled by the wallabag app. Check whether your QR-code scanner supports opening links.

**Comment by azrdev** [comment]
> "Open browser" button in [Barcode Scanner](https://f-droid.org/repository/browse/?fdid=com.google.zxing.client.android) allows to open the link, which is then automatically handled by the wallabag

This seems to be broken (here), I get an error message that the protocol would be not supported.
Android 9, wallabag app 2.2.1 from f-droid

**Comment by di72nn** [comment]
That's weird. I just tried Barcode Scanner on Android 8.1: it didn't open the URL. [Binary Eye](https://f-droid.org/app/de.markusfisch.android.binaryeye) worked alright though.

**Comment by di72nn** [comment]
#369.
