### ISSUE TITLE
Don't retry to delete article if 404 received -> high battery drain

### ISSUE THREAD

**Issue by shtrom** [wallabag/android-app#375]
I am seeing an odd behaviour due (probably) to deleting an article both in the Android app, and the Web interface before it synced.

Now, the Android app repeatedly tries to delete the article, as seen in my webserver logs:

    wallabag.example.net 192.0.2.1 - - [19/Dec/2016:06:25:56 +0100] "GET /delete/3992 HTTP/1.1" 200 818 "-" "okhttp/3.4.1"
    wallabag.example.net 192.0.2.1 - - [19/Dec/2016:06:26:01 +0100] "GET /delete/3992 HTTP/1.1" 200 818 "-" "okhttp/3.4.1"
    wallabag.example.net 192.0.2.1 - - [19/Dec/2016:06:26:07 +0100] "GET /delete/3992 HTTP/1.1" 200 818 "-" "okhttp/3.4.1"

Oddly enough, the application sees this as 404 error, as per the logcat (to follow), and keeps popping an unknown error (also to follow) before retrying to sync immediately. This leads to a high battery drain.

There are several things that could be done to address the issue.
* HTTP DELETE should be idempotent, and not return a 404, or any indication that the object to delete was not there, to the client. This is a GET happening here, but it should probably follow the same semantics
* In the current situation, if the Android app receives a 200 from a `GET /delete/...` wrapping a 404, this means that Wallabag has responded properly, but the item is no longer there, there should therefore be no need to retry the delete.
* Add some sort of incremental back-off in case of repeated sync failures to avoid draining the battery.
* Add a way to clear the app's sync queue, so one can manually cancel local sync actions that might be causing this sort of issue.

**Comment by shtrom** [comment]
```
I/ActivityManager( 2537): Start proc 5225:fr.gaulupeau.apps.InThePoche/u0a66 for service fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.service.WallabagJobService
D/WallabagServiceEndpointV2( 5225): executeRequestForResult() got response
W/WallabagServiceEndpoint( 5225): checkResponse() response is not OK; response code: 404, response message: Not Found
W/BGService( 5225):     at fr.gaulupeau.apps.Poche.network.WallabagServiceEndpoint.checkResponse(WallabagServiceEndpoint.java:124)
W/BGService( 5225):     at fr.gaulupeau.apps.Poche.network.WallabagServiceEndpoint.checkResponse(WallabagServiceEndpoint.java:115)
W/BGService( 5225):     at fr.gaulupeau.apps.Poche.network.WallabagServiceEndpointV2.executeRequestForResult(WallabagServiceEndpointV2.java:187)
W/BGService( 5225):     at fr.gaulupeau.apps.Poche.network.WallabagServiceEndpoint.executeRequest(WallabagServiceEndpoint.java:174)
W/BGService( 5225):     at fr.gaulupeau.apps.Poche.network.WallabagServiceEndpoint.executeRequest(WallabagServiceEndpoint.java:169)
W/BGService( 5225):     at fr.gaulupeau.apps.Poche.network.WallabagServiceEndpointV2.deleteArticle(WallabagServiceEndpointV2.java:295)
W/BGService( 5225):     at fr.gaulupeau.apps.Poche.network.WallabagService.deleteArticle(WallabagService.java:78)
D/WallabagJobService( 5225): enable(true) started
D/WallabagJobService( 5225): enable() trying to schedule a job
D/WallabagJobService( 5225): onStartJob() started
D/WallabagJobService( 5225): enable(): JobScheduler job scheduled
D/WallabagServiceEndpointV2( 5225): deleteArticle() articleId=3992
D/WallabagServiceEndpointV2( 5225): executeRequestForResult(url: https://wallabag.narf.ssji.net/delete/3992, checkResponse: true, autoRelogin: true) started
```

A quick workaround to fix the issue when it happens is just to insert a fake entry to be deleted by the app. If using SQLite,

    sqlite3 /path/to/wallabag.sqlite 'insert into wallabag_entry values(3992, 1, "", "", "", 0, 0, "", '2016-12-18 22:46:01', '2016-12-18 22:46:01', 'text/html', "en", 1, "", "", 1);'

Example notification:

![screenshot_20161219-163123](https://cloud.githubusercontent.com/assets/160280/21302563/15a941ae-c60c-11e6-8bdf-da21b5386b63.png)

**Comment by shtrom** [comment]
This issue also blocks any other syncing activity.

**Comment by di72nn** [comment]
Thank you for your thorough review. I created a workaround for the issue: #376.

Also discussed here: #319.

**Comment by di72nn** [comment]
The fix is merged.
