### ISSUE TITLE
not able to share from feedly-app to wallabag

### ISSUE THREAD

**Issue by aisbergde** [wallabag/android-app#38]
I would like to test wallabag as an alternative to pocket. wallabag has a free full text search. But I am not able to share links from androids feedly app to wallabag on my android device. something is shared, but the link is invalid and can't be used.

when I click on the "link to the original" I get something like file:///android_asset/a_long_name_without_a_website

When I look at the link in wallabag web client, it looks like:
https://www.framabag.org/u/aisberg/Andreas%20Popp%20%E2%80%93%20Kapitalismus%20vs.%20Demokratie%20http://pinksliberal.wordpress.com/2014/10/04/andreas-popp-kapitalismus-vs-demokratie

and the content is also not shown.
but when I copy the contained link
http://pinksliberal.wordpress.com/2014/10/04/andreas-popp-kapitalismus-vs-demokratie
then this link works. 

When I share a link in the browser to wallabag-app, it works fine. I think feedly addes something which will not be resolved by wallabag-app.

Normally I never use the feedly share function, but I use ifttt service to push marked articles from feedly to pocket, but there is not yet a wallabag channel on ifttt. So I can't use feedly this way.

**Comment by tcitworld** [comment]
Closed for #106.
