### ISSUE TITLE
add articles without web browser, and also when offline

### ISSUE THREAD

**Issue by aisbergde** [wallabag/android-app#39]
currently links can be added only when online and only via the web browser. And it takes some time. 

I suggest to implement a way to collect the links which should be added in the app and to sync them to the server when synchronizing articles. Otherwise the app can't be used to add links when offline or with a bad connection. This would also save a lot of time when sharing links to wallabag.

To get some ideas have a look on the pocket app and how it works. Btw, I started to use pocket when I was without mobile internet (for example in a rooming situation) and a good offline support was the main reason to start to use it.

**Comment by Fenntasy** [comment]
If I can add my two cents, that's maybe the only thing lacking for me to change to wallabag.

**Comment by tcitworld** [comment]
That's why we develop wallabag v2, to provide an API and allow these kind of features. Not possible at the moment.

**Comment by Fenntasy** [comment]
Well, allright if you're working on it then. I'll use both pocket and wallabag for the moment :)

**Comment by tcitworld** [comment]
Done with v1.
