### ISSUE TITLE
no articles displayed

### ISSUE THREAD

**Issue by emporeso2** [wallabag/android-app#398]
I have the app version 1.11.0(29) on android 6 , the app worked well but since one week i have no articles in the app !
How to debug this in the phone ? Is there a log on my phone to show you ?

**Comment by emporeso2** [comment]
Yes i purge the app , reinstall it and reconfigure it ,but still not working .
I forget i have subscribe to the payed service https://www.wallabag.it/

**Comment by tcitworld** [comment]
When you reconfigure the app, when does the issue occur ? You need to put `app.wallabag.it` as the service URL.
You can come on https://gitter.im/wallabag/wallabag for quicker support (french and english).

**Comment by di72nn** [comment]
@emporeso2 what exactly is the problem? The lists are empty? Is the "updating feeds" notification displayed for some time when you update feeds (or does it disappear immediately)? Is there any notifications with errors after you update feeds?

**Comment by emporeso2** [comment]
Strange it work now !!!
In fact, the list was empty , the update feeds notifications appear then a message "intern error".
So all work good now,strange , i don't really understand what happen !?
