### ISSUE TITLE
wallabag app crashes when "Cache in article embedded images" enabled

### ISSUE THREAD

**Issue by ThibaudDauce** [wallabag/android-app#410]
I'm using the latest version of the Android app with wallabag.it.

This morning, I saw the update and I went in my settings to enable "Cache in article embedded images". Immediately after that the application crashes with "wallabag has stopped". 

Now the application crashes when I try to synchronise with the "reload" button in the menu and sometimes crashes when I open it.

If I disable the "Cache in article embedded images" settings, everything is working fine again.

**Comment by di72nn** [comment]
Can you provide logs? You can use an app like "aLogcat" or follow the instructions in [this comment](https://github.com/wallabag/android-app/issues/373#issuecomment-267778747) if you can use "adb".

**Comment by ThibaudDauce** [comment]
Can I have more information on how to use aLogcat?

**Comment by di72nn** [comment]
It seems the aLogcat app requires root on Android 4.1+. Do you have root access or do you run pre-4.1 Android version?

**Comment by ThibaudDauce** [comment]
I'm using Android 6 and I don't have root access...

**Comment by di72nn** [comment]
Is there any chance you can [install Android SDK](https://developer.android.com/studio/releases/platform-tools.html) on PC and get logs via `adb`?

Does the app crashes if you use pull-to-refresh to update?
When the app updates there should be "feed update" notification and then "downloading images" notification. Right before the app crashes, does any of these two present?

**Comment by ThibaudDauce** [comment]
It also crashes when pull-to-refresh. 

The two notifications are present when it crashes, the application crashes just after the "Downloading images" notification appear.

**Comment by ThibaudDauce** [comment]
I sent a crash report, maybe you'll have more information...

**Comment by di72nn** [comment]
A crash report should do it, thanks.

**Comment by ThibaudDauce** [comment]
Here are the logs with ADB https://framabin.org/?8857b9ffd7aad69e#VvEPoX09AewGE6/BBgQEd1LkXNx/AC0NVdKX9r4NA48=

**Comment by ngosang** [comment]
I'm having the same problem :(

**Comment by ngosang** [comment]
I see this problem only with "Cache in article embedded images" in the Android App and "Download images locally" in wallabag Web. I have this problem only if both options are enabled.

**Comment by nicosomb** [comment]
@di72nn Is that fixed with https://github.com/wallabag/android-app/pull/412 ? If yes, can we release a new version please?

**Comment by di72nn** [comment]
@nicosomb yes, it is fixed (most likely). Ping @tcitworld.

**Comment by di72nn** [comment]
Fixed in 1.12.1.
