### ISSUE TITLE
Show article creation date

### ISSUE THREAD

**Issue by ngosang** [wallabag/android-app#414]
I would like to have the article creation date at the top of the article, just below the title. I mean the date in the original article, not the date it was fetched.

**Comment by Strubbl** [comment]
Is this information provided by the wallabag web app? I think it should be provided by the web app. Did you open an issue in that project? If yes, please reference it here as dependency

**Comment by ngosang** [comment]
> Is this information provided by the wallabag web app?

No, sorry. I opened https://github.com/wallabag/wallabag/issues/2827

**Comment by di72nn** [comment]
Done.
