### ISSUE TITLE
Favorite and Archive icons are not visible with black theme

### ISSUE THREAD

**Issue by ngosang** [wallabag/android-app#415]
Favorite icon is not visible with back theme. In the articles list the icon is black and should be white because the background is black.

**Comment by Strubbl** [comment]
in my app the icon is white/grey. Can you please post a screenshot? Which theme exactly are you using? I use the dark theme.

**Comment by ngosang** [comment]
Dark (high contrast)

**Comment by Strubbl** [comment]
Hmm, i cannot reproduce that. I just switched to that theme, but the fav icon is white. 

> In the articles list the icon is black and should be white

I do not have a favorite icon in the article list.

**Comment by ngosang** [comment]
![screenshot_2017-02-01-22-09-55](https://cloud.githubusercontent.com/assets/10577978/22526415/773d2ebc-e8cb-11e6-8a03-a0d06d65389b.png)
![screenshot_2017-02-01-22-10-27](https://cloud.githubusercontent.com/assets/10577978/22526421/79b154e8-e8cb-11e6-8756-0679db0191cd.png)

**Comment by di72nn** [comment]
Related to #337, #273.

**Comment by ngosang** [comment]
My proposal is:
Light themes => black icons
Dark themes => white icons

**Comment by di72nn** [comment]
We need to use attributes on themes to get resources like [here](https://stackoverflow.com/a/17277714).
