### ISSUE TITLE
Bug: Main image not displayed

### ISSUE THREAD

**Issue by ngosang** [wallabag/android-app#416]
In this article => http://blogs.elconfidencial.com/economia/big-data/2015-10-21/la-enfermedad-autoinmune_1066745/
This is the main image => http://8www.ecestaticos.com/imagestatic/clipping/8d9/1f7/8d91f72e80da7e354103469ddd3800a7/imagen-sin-titulo.jpg?mtime=1445355091
I see it perfectly in Wallabag Web but no in Android app.

**Comment by di72nn** [comment]
That's a "preview picture". See #232, #235.

**Comment by ngosang** [comment]
@di72nn @Strubbl But this is not implemented. According to that post the API v2 provides that image (https://github.com/wallabag/android-app/issues/232#issuecomment-216841497) but we are not using it.
Could you reopen this issue and change the title to "Improvement" instead of bug?

**Comment by di72nn** [comment]
> But this is not implemented.

That's why we have #232 opened.
This issue is closed as a duplicate of #232. Have anything to add - go to #232.

Don't get me wrong - issues (suggestions, bug reports, etc.) are welcome, thank you for your time BTW, but duplicates don't help at all.
