### ISSUE TITLE
Part of the article is not displayed

### ISSUE THREAD

**Issue by ngosang** [wallabag/android-app#422]
URL => https://www.adslzone.net/2017/01/09/intel-kaby-lake-procesadores-caracteristicas-precios/

Wallabag web => full article
RSS => full article
Wallabag app => just half article content (text and images)

**Comment by ngosang** [comment]
Same with http://www.novatostradingclub.com/formacion/el-ciclo-kitchin/

**Comment by di72nn** [comment]
Can't reproduce on self-hosted wallabag 2.2.1 with 1.12.0 app (from F-Droid): the articles seem fine.

Please provide more details.

**Comment by ngosang** [comment]
> Can't reproduce on self-hosted wallabag 2.2.1 with 1.12.0

Same versions here but I don't see the full article in the app :(

![screenshot_2017-02-08-10-44-45](https://cloud.githubusercontent.com/assets/10577978/22731815/3bf891ea-edec-11e6-99b0-5001da6bafa0.png)
![screenshot_2017-02-08-10-44-28](https://cloud.githubusercontent.com/assets/10577978/22731816/3dbeb11c-edec-11e6-8d5e-fe89e636287f.png)

**Comment by di72nn** [comment]
If you have image caching enabled, try to disable it and open the articles (there should be no need in updating articles; however, I would advice to restart the app just in case).

**Comment by ngosang** [comment]
> If you have image caching enabled, try to disable it and open the articles

That fixed the problem but it's a bug then.

**Comment by di72nn** [comment]
Yeah, thanks for reporting it.
What Android version do you run?

Dev note:
It seems regex greediness works differently. Anyway, `ImageCacheUtils.responsiveParametersPatterns` should probably use `[^\"]*` instead of `.*`.

**Comment by ngosang** [comment]
> What Android version do you run?

Android 5.1.1
Wallabag app 1.12.0
