### ISSUE TITLE
Favorite posts appearing in the unread list even if they were read

### ISSUE THREAD

**Issue by bnjbvr** [wallabag/android-app#427]
When syncing with my personal server, previous posts that I've read in the past (imported from Pocket) and that I've marked as favorite appear in the unread list on the Android app. On the web app, they don't appear as unread, so I'm guessing something is wrong here.

Please let me know if I can provide you with more information. Cheers!

**Comment by di72nn** [comment]
Do you see both the "checkmark" and "star" icons for such items in the unread list?

**Comment by bnjbvr** [comment]
Unfortunately, I've uninstalled the app temporarily, so I can't reproduce anymore. Note that I'm using the latest Wallabag (v2), and I've been told the application wasn't ready to use the new API yet, so that might be the reason.

**Comment by Strubbl** [comment]
Even with RSS feed syncronisation it should work as expected. 

Which versions exactly are you using of your wallabag? And which app version? 

In you wallabag, you can check the feeds, which are currently being used as the source of articles. You need to go to settings -> RSS. You will find feeds for unread, fav and archive there. Please check those feeds for an article which is displayed OK in wallabag, but not in the app.

**Comment by bnjbvr** [comment]
I've seen that the feeds are correct in the web app.

I'm using Wallabag 2.2.1 and the Android app distributed on the Play store, version number is 1.12.0.

**Comment by di72nn** [comment]
It might be caused by the "fast update" (invoked with pull-to-refresh) method currently used. This method updates feeds separately and have some issues.
If you have this issue after running "full update" (menu option) then it is something we was not aware of.

Anyway, we work on v2 API support, so it shouldn't be an issue in the [near] future.

**Comment by di72nn** [comment]
You may want to try our v2 test version. You can [download it directly](https://github.com/wallabag/android-app/releases) or from [Google Play](https://play.google.com/apps/testing/fr.gaulupeau.apps.InThePoche) (if it is not available there, it may still be processing by Google Play).

The new version works via API, so RSS feeds won't cause problems anymore.

**Comment by di72nn** [comment]
Please reopen if you encounter the problem in the latest release (v2.+).
