### ISSUE TITLE
Connection works via web browser but fails in Windows 10 app

### ISSUE THREAD

**Issue by profbib** [wallabag/android-app#430]
I just created an account at Framabag.org and, using the address https://www.framabag.org/u/profbib along with my username (which I have verified in the activation email to be typed correctly) & password and everything (viewing articles, saving them) works fine in the web browser, but initial connection fails in the Windows 10 app.  When trying to log in there, I used the same information above after selecting "other" at the initial screen, but get a connection error each and every time.  Any ideas?  I looked through a couple of the other issues involving connection errors, but it seems like most have been solved and several involved personal instances of Wallabag rather than the Framabag instance. Thanks in advance.

**Comment by di72nn** [comment]
Wrong repo. Try https://github.com/wallabag/windows-app.

**Comment by tcitworld** [comment]
@profbib Also, I'm not sure the Windows app still support wallabag v1.
