### ISSUE TITLE
Option to keep screen on while reading

### ISSUE THREAD

**Issue by lokesh-krishna** [wallabag/android-app#436]
Currently, the app offers no option to keep the screen on (overriding the display timeout), which is a very handy feature to have in a reading app.

There is an open source app that does this really well and might be of use in implementing it here: [FBReader](https://github.com/geometer/FBReaderJ).

**Comment by tcitworld** [comment]
Use [`FLAG_KEEP_SCREEN_ON`](https://developer.android.com/reference/android/view/WindowManager.LayoutParams.html#FLAG_KEEP_SCREEN_ON)

**Comment by NWuensche** [comment]
I will try to fix this.
