### ISSUE TITLE
keep the search set when an article is marked as read

### ISSUE THREAD

**Issue by aisbergde** [wallabag/android-app#437]
do a search
select an article, don't read it, go back and the search set is still available
but if you mark the article as read the search set will be lost

**Comment by di72nn** [comment]
Fixed in #370 (fixed with a hack, though).

Dev note: most likely caused by `invalidateOptionsMenu();` call in `onOfflineQueueChangedEvent(OfflineQueueChangedEvent)` in the main activity.

**Comment by di72nn** [comment]
Legacy version is no longer supported.
