### ISSUE TITLE
Invalid URL using share > wallabag in Twitter

### ISSUE THREAD

**Issue by Linuxine** [wallabag/android-app#44]
I'm on Android 4.2.2. 
My Wallabag is self hosted. When I try to add a page using "share > bag it ! " in my browser (Firefox or Opera) on Android, no problem. 
But when I try to use the "Share > Wallabag" button in Twitter, it launch my browser, then ask me to connect to my Wallabag page, then end up with a white page saying "Invalid URL supplied". When I look at the server logs, the URL seems indeed different : there are special characters such as %, that I don't find in URL added via the "bag it" button.

**Comment by tcitworld** [comment]
Closed for #106.
