### ISSUE TITLE
Whitespace issue in article list

### ISSUE THREAD

**Issue by lightonflux** [wallabag/android-app#45]
This article: http://aseigo.blogspot.gr/2014/10/four-paths.html

That result:

![wallabag-app](https://cloud.githubusercontent.com/assets/1377943/4780676/38769790-5c73-11e4-9d60-18c85ada8462.png)

Can't remember which version of wallabag imported the article, but nonetheless the app should not display titles in this manner.

**Comment by tcitworld** [comment]
Now using ChromeView, doesn't occur anymore.

**Comment by lightonflux** [comment]
Does one need chrome installed for chrome view? Or does it work on CM like ROMS?

**Comment by di72nn** [comment]
@lightonflux it's not related to "Chrome Browser".
