### ISSUE TITLE
Test API access error

### ISSUE THREAD

**Issue by klorydryk** [wallabag/android-app#462]
On the current master code version (d73e0c801120a11e92614cbd2cc9005b58e344de).
Android LineAgeOS v7.1.1
Wallabag v2.1.1

First launch, after filling the login information, ID client and Secret client are correctly recovered from the server. Back to the main window, I get a window "modified parameters", asking to test the connection. I say YES, so message is now "testing the connection", then "testing API access".
Then I get an "Error API test - unknown error: com.di72nn.stuff.wallabag.apiwrapper.exceptions.AuthorizationException: HTTP response: 400 Bad Request". 

And impossible to get my datas.

**Comment by di72nn** [comment]
Did you use the "connection wizard"? If you didn't, it wouldn't hurt to try.

I encountered HTTP 400 response only with this body: `{"error": "invalid_client","error_description": "The client credentials are invalid"}`. So from my experience it can only mean incorrect username / password / client ID / client secret.

Since you can build the app yourself, you can run the debug version which logs a lot of connection-related messages.

**Comment by di72nn** [comment]
I've just noticed that you use pretty old server version. The app wasn't tested with versions older than late 2.1.x (~2.1.4).

I also noticed that the error could only happen in `wallabagService.getVersion()` call.

If the "connection wizard" doesn't help, can you try to comment out the following line from TestApiAccessTast.java:
```java
Log.d(TAG, "doInBackground() API version: " + wallabagService.getVersion());
```
and test the app again?

**Comment by tcitworld** [comment]
@di72nn Could we handle the lack of `/api/version` route in `wallabagService.getVersion()` ?

**Comment by di72nn** [comment]
That is not lack of the method: the server responds with HTTP 400.
**Maybe** I should not pass the auth header when I request `/api/version`, but I would like to know whether it would help before doing such a change (currently I add the header to any requests, so creating an exception would require to check every request).

**Comment by klorydryk** [comment]
@di72nn the behavior of the "connection wizard" is weird: no error but after the "test connection", "get id from API" et "trying the API connection", I stay on the same page.

The Wallabag version is the one provided with Yunohost.
just test to remove 
> Log.d(TAG, "doInBackground() API version: " + wallabagService.getVersion());
and now it is "invalid username and password combination"

**Comment by di72nn** [comment]
> Yunohost

That may be important. AFAIR in some versions Yunohost used HTTP Auth, I have no idea what is the current configuration.

Did you try any other wallabag client (browser extension for example)?

**Comment by Strubbl** [comment]
The problem maybe here is, that Yunohost is still using wallabag **1**.9.2

**Comment by di72nn** [comment]
No, there's also a wallabag 2 package available.

@klorydryk it seems to be a Yunohost issue. Try this: https://github.com/YunoHost-Apps/wallabag2_ynh/issues/1#issuecomment-276953495.

**Comment by klorydryk** [comment]
I tried the workaround, but the reset link isn't working. I just get a page with the Wallabag logo, my username and my email address.

And the firefox plugin connection isn't working.

**Comment by di72nn** [comment]
There is probably a way to reset password via CLI. You may try to get help with it on [gitter](https://gitter.im/wallabag/wallabag).

**Comment by di72nn** [comment]
Please reopen, if you still need assistance.

**Comment by klorydryk** [comment]
(updated to https://github.com/YunoHost-Apps/wallabag2_ynh and it is working now)

**Comment by di72nn** [comment]
Thanks for the update.
