### ISSUE TITLE
Add article activity doesn't go back to main activity

### ISSUE THREAD

**Issue by tcitworld** [wallabag/android-app#469]
Steps : 
* Select add an article in the menu
* Enter the url
* hit save

What happens : 
* The url is correctly saves, but the screen stays on the add article activity

What it should happen:
* After the article been added and synched, it should return to the main activity

**Comment by di72nn** [comment]
Are you sure? Maybe you managed to open two dialogs: one on top of another?

**Comment by tcitworld** [comment]
Hmm, probably messed up with my old production build, since it was an activity and not a dialog.
