### ISSUE TITLE
Unknow error: java.security.cer.CertPathValidatorException

### ISSUE THREAD

**Issue by gerroon** [wallabag/android-app#479]
Hi

I use custom walla bag server. And the app runs perfectly fine with all my devices except the Nougat (Lineage OS) one. I use custom certs and those certs are imported into all the devices via the proper method. So the certs work, the app works. The nougat walla bag gives me this error when I try to autofill in the connection tab

"Unknow error: java.security.cer.CertPathValidatorException: Trust anchor for identification path not found"

**Comment by di72nn** [comment]
Do you have any particular reason to use self-signed certs instead of something like [Let's Encrypt](https://letsencrypt.org)?

**Comment by gerroon** [comment]
@di72nn

I do not have a registered domain name, I use my home server.

**Comment by gerroon** [comment]
Not sure if this is included in the latest Fdroid but it still gives the same error. I think it was abuilt done on 3/17/2017

**Comment by di72nn** [comment]
1.12.2 was released on 28th of February, but due to F-Droid problems it was built only a couple of days ago. The fix for this bug is not yet in the legacy version.

**Comment by gerroon** [comment]
@di72nn 

Thanks for the update.

**Comment by di72nn** [comment]
@gerroon can you confirm that the problem was solved for your Nougat device in v2.0.0 release?

**Comment by gerroon** [comment]
The problem is solved in v2
