### ISSUE TITLE
TTS is reading image tags

### ISSUE THREAD

**Issue by ngosang** [wallabag/android-app#491]
wallabag app master branch

When I use Text-to-Speech it's really annoying that it read `<img src="http://url...">` in each image of the article. Is there a way to exclude that tags from reading?

**Comment by nicosomb** [comment]
I think that TTS must read images alternative text. It's a great feature for people who have vision troubles.

**Comment by ngosang** [comment]
I agree, but not the url. Maybe replace < img alt="My text" src="url" > with "Image: My text"

**Comment by Strubbl** [comment]
Maybe the URL is also an important piece of information?

**Comment by ngosang** [comment]
> Maybe the URL is also an important piece of information?
I think it's not. Try to read this loud: => http://e00-elmundo.uecdn.es/assets/multimedia/imagenes/2017/03/26/14905243855423.jpg
It's really annoying. 😞

**Comment by tcitworld** [comment]
Yeah, let's look at removing the url.

**Comment by Strubbl** [comment]
>> Maybe the URL is also an important piece of information?

> I think it's not. Try to read this loud: => http://e00-elmundo.uecdn.es/assets/multimedia/imagenes/2017/03/26/14905243855423.jpg
It's really annoying. 😞 

For you yes. But for people who have vision troubles?

**Comment by tcitworld** [comment]
That's the purpose of the `alt` attribute.

**Comment by Strubbl** [comment]
> That's the purpose of the `alt` attribute.

Of course. But do you have any reference, that the link is not necessary?

**Comment by tcitworld** [comment]
As far as I've googled it, it's of no use. I'll ask a friend of mine who's specialized in accessiblity.

**Comment by ntnsndr** [comment]
Checking on this. It's a consistent problem for me. Can the app just automatically remove URL-like strings?

**Comment by di72nn** [comment]
Can somebody provide a couple of examples?

**Comment by ngosang** [comment]
Most images are read properly, but I found one that doesn't.

https://www.elconfidencial.com/espana/2020-04-01/coronavirus-ultima-hora-covid19-fallecidos_2524247/

Start reading in this paragraph, you will hear the URL in the image:

![image](https://user-images.githubusercontent.com/10577978/78167878-7efd7680-744f-11ea-8ea7-26e99299de75.png)

If you look at the source code it's a bit more complex than an img:
```html
<a href="https://www.ecestaticos.com/file/bb9dda95798ab68ea963442112b32b18/1585730429-carta-admin-provisional-u-nica-de-rtve-01-04-20.pdf" class="img-link" target="_blank" rel="nofollow">
   <figure class="news-img-figure">
      <noscript>
         <p><img class="eclazy news-img-def" src="https://www.ecestaticos.com/image/clipping/585/d2dd4f749212b4be8ddba6b5ce1c5e51/pinche-aqui-para-consultar-la-carta-integra-a-rtve.jpg" alt="Pinche aquí para consultar la carta íntegra a RTVE" width="585" height="836" referrerpolicy="no-referrer" /></p>
      </noscript>
      <img class="news-img-def" alt="Pinche aquí para consultar la carta íntegra a RTVE" src="https://www.ecestaticos.com/image/clipping/585/d2dd4f749212b4be8ddba6b5ce1c5e51/pinche-aqui-para-consultar-la-carta-integra-a-rtve.jpg" referrerpolicy="no-referrer" width="585" height="836">
      <figcaption class="news-img-caption-def">Pinche aquí para consultar la carta íntegra a RTVE</figcaption>
   </figure>
</a>
```

I hove @ntnsndr can provide better examples.

**Comment by ntnsndr** [comment]
Yes, I've been looking for examples! Will post as I encounter them. Sorry for the delay. It's true that this happens less than I think it used to. But I was reminded of this the other day when my wife said, "I love it when your robot reads URLs."

**Comment by di72nn** [comment]
That problem with `<noscript>` elements is unusual, but [trivial to fix](https://github.com/wallabag/android-app/pull/945/commits/a76e7db5b03ff835a2a6c914654c898802b94913).
I also encountered the same problem with [this article](https://de.wikipedia.org/wiki/Worte_des_Vorsitzenden_Mao_Tsetung#Struktur_und_Inhalt) (near the very end).

However, it seems to me that `<img>` tags are not read at all (an accessibility issue).

**Comment by ngosang** [comment]
> However, it seems to me that <img> tags are not read at all (an accessibility issue).

That should be easy to fix. Just add some code like this here => https://github.com/wallabag/android-app/pull/945/files#diff-db78bf95f5278b36d57b2bb1ace522c9R118

```javascript
            } else if (element.nodeName === 'IMG') {
                if (element.hasAttribute("alt")) {
                    accumulatedText += "Image: " + element.getAttribute("alt");
                }
            }
```

NOTE: You have to translate the text "Image".

**Comment by ntnsndr** [comment]
I noticed the problem today on an image in a Google Doc (I can't share the URL because it was shared with me privately).

**Comment by ntnsndr** [comment]
Okay, I found an example of an image tag the TTS is reading: See [this article](https://www.theatlantic.com/health/archive/2020/04/pandemic-summer-coronavirus-reopening-back-normal/609940/), just before the author's byline at the very end.

**Comment by di72nn** [comment]
Seems like another `<noscript>` tag. Should be fixed in #931.

**Comment by ntnsndr** [comment]
Another offender [here](https://qz.com/work/1868106/black-business-history-reveals-potent-management-lessons/). Looks like <noscript> again.

**Comment by di72nn** [comment]
You probably want to check out the latest beta ([APK](https://github.com/wallabag/android-app/releases/tag/2.4.0-beta.3), [beta on Google Play](https://play.google.com/apps/testing/fr.gaulupeau.apps.InThePoche), [eventually on F-Droid](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7000)) - it contains a lot of TTS-related changes (including the fix for the `<noscript>` tag).

**Comment by ngosang** [comment]
I have been testing the code in the master branch for a while. It's really good. Thank you!

**Comment by ntnsndr** [comment]
Thanks! Yes, I'm on the F-Droid bandwagon.

**Comment by di72nn** [comment]
`2.4.0-beta.4` is available in F-Droid (it's not marked as "suggested", so you have to choose the version manually).

**Comment by di72nn** [comment]
Reopen if you have new examples (with `2.4.0-beta.4+`).
