### ISSUE TITLE
Show time to read (estimated reading time) on article list

### ISSUE THREAD

**Issue by shtrom** [wallabag/android-app#494]
When choosing what to read next, the time it will take to read the piece is an important factor. At the moment, the app only displays this on the article's page only, which requires one to open an article, check the duration, then decide whether to read it or to go back to the list to look for a more suitable article.

It would be good to show this time to read on the main list, maybe to the right of the line showing the site that each item comes from. This would make scanning the list for a article of the desired length much faster.

**Comment by di72nn** [comment]
#492.

**Comment by joelostblom** [comment]
I think this can be closed since the feature was added in #592.

**Comment by di72nn** [comment]
Yeah, thanks.
