### ISSUE TITLE
Wallabag service not found - check URL

### ISSUE THREAD

**Issue by brettlangdon** [wallabag/android-app#495]
Hello,

The app was working perfectly fine a few days ago, then I noticed that it stopped wanting to sync. The sync error notification was kind of cryptic and didn't provide much information (sorry I can't remember what it said, and can't reproduce at this point). I then decided to clear the app cache, delete local database, etc and start fresh. Now the error I get when doing a test connection is `Wallabag service not found - check URL`.

Info:

* Wallbag android app version - 1.12.2 (32)
* Wallbag server version - 2.2.2
  * Self hosted server
* Using SSL/HTTPS
* Not using 2FA
* The previous RSS token that was stored in the app worked fine when tested outside the app
  * I regenerated just because, and the new token works as expected
* I am entering correct user/password
* I am entering `https://subdomain.domain.com` as the service url
* My server does url rewriting to `/app.php{uri}`

This is the access log of the server when the app tries to make a connection:
```
1.1.1.1 - [05/Apr/2017:13:48:25 +0000] "GET /app.php/ HTTP/1.1" 302 260
1.1.1.1 - [05/Apr/2017:13:48:25 +0000] "GET /app.php/login HTTP/1.1" 200 4119
1.1.1.1 - [05/Apr/2017:13:48:25 +0000] "GET /app.php/ HTTP/1.1" 302 260
1.1.1.1 - [05/Apr/2017:13:48:25 +0000] "GET /app.php/login HTTP/1.1" 200 4119
1.1.1.1 - [05/Apr/2017:13:48:25 +0000] "GET /app.php/login/ HTTP/1.1" 404 325
```

Not sure what I messed up here and I didn't have luck finding any existing issues that matched what I am experiencing exactly. Happy to help debug further, just not sure what to try next.

**Comment by di72nn** [comment]
First of all, try to set up the app using the "connection wizard" (you can start it from settings) - it has some logic to detect common configuration problems.

**Comment by di72nn** [comment]
Did you, by any chance, customize wallabag login page? The app relies on the presence of some HTML code snippets in the pages. The code snippets are mentioned in #292.

There is also a redirect-related issue described starting from [this comment](https://github.com/wallabag/android-app/issues/292#issuecomment-255378721).

**Comment by Strubbl** [comment]
I wonder why the app at first tries GET /app.php/login and after that /app.php/login/

Can you show us the complete rewrite config of your web server? Did you change anything at the web server or wallabag web app?

**Comment by di72nn** [comment]
I'm pretty sure that the request to `/app.php/login/` is the result of the app checking different redirects.

`GET /app.php/login HTTP/1.1" 200 4119` is the request the worries me. The app should recognize the login page there.

**Comment by brettlangdon** [comment]
ha! I figured it out... thanks @di72nn for the hint about the app looking for a specific HTML code snippet.

I am using [caddy](https://caddyserver.com/) as a web server, and I enabled the [minify](https://caddyserver.com/docs/minify) plugin a few days ago.

I disabled the use of that plugin for my server and the app is working perfectly fine again.

Seems kind of brittle that minifying the HTML would cause these issues.


Here is the minified version of the login page if you were curious:

```html

<!doctype html><!--[if lte IE 6]><html class="no-js ie6 ie67 ie678" lang="en"><![endif]--><!--[if lte IE 7]><html class="no-js ie7 ie67 ie678" lang="en"><![endif]--><!--[if IE 8]><html class="no-js ie8 ie678" lang="en"><![endif]--><!--[if gt IE 8]><html class="no-js" lang="en"><![endif]--><html lang=fr><meta name=viewport content="initial-scale=1"><meta charset=utf-8><!--[if IE]>
            <meta http-equiv="X-UA-Compatible" content="IE=10">
            <![endif]--><link rel=apple-touch-icon type=image/png href=/bundles/wallabagcore/themes/_global/img/appicon/apple-touch-icon-152.png sizes=152x152><link rel=icon type=image/png href=/bundles/wallabagcore/themes/_global/img/appicon/apple-touch-icon-152.png sizes=152x152><link rel=apple-touch-icon type=image/png href=/bundles/wallabagcore/themes/_global/img/appicon/apple-touch-icon-144.png sizes=144x144><link rel=icon type=image/png href=/bundles/wallabagcore/themes/_global/img/appicon/apple-touch-icon-144.png sizes=144x144><link rel=apple-touch-icon type=image/png href=/bundles/wallabagcore/themes/_global/img/appicon/apple-touch-icon-120.png sizes=120x120><link rel=icon type=image/png href=/bundles/wallabagcore/themes/_global/img/appicon/apple-touch-icon-120.png sizes=120x120><link rel=apple-touch-icon type=image/png href=/bundles/wallabagcore/themes/_global/img/appicon/apple-touch-icon-114.png sizes=114x114><link rel=icon type=image/png href=/bundles/wallabagcore/themes/_global/img/appicon/apple-touch-icon-114.png sizes=114x114><link rel=apple-touch-icon type=image/png href=/bundles/wallabagcore/themes/_global/img/appicon/apple-touch-icon-76.png sizes=76x76><link rel=icon type=image/png href=/bundles/wallabagcore/themes/_global/img/appicon/apple-touch-icon-76.png sizes=76x76><link rel=apple-touch-icon type=image/png href=/bundles/wallabagcore/themes/_global/img/appicon/apple-touch-icon-72.png sizes=72x72><link rel=icon type=image/png href=/bundles/wallabagcore/themes/_global/img/appicon/apple-touch-icon-72.png sizes=72x72><link rel=apple-touch-icon type=image/png href=/bundles/wallabagcore/themes/_global/img/appicon/apple-touch-icon-57.png sizes=57x57><link rel=icon type=image/png href=/bundles/wallabagcore/themes/_global/img/appicon/apple-touch-icon-57.png sizes=57x57><link rel=apple-touch-icon type=image/png href=/bundles/wallabagcore/themes/_global/img/appicon/apple-touch-icon.png><link rel=icon type=image/png href=/bundles/wallabagcore/themes/_global/img/appicon/apple-touch-icon.png><link rel="shortcut icon" type=image/x-icon href=/bundles/wallabagcore/themes/_global/img/appicon/favicon.ico><link rel=stylesheet href=/bundles/wallabagcore/themes/material/css/style.min.css media=screen,projection,print><script src=/bundles/fosjsrouting/js/router.js></script><script src="/js/routing?callback=fos.Router.setData"></script><script src=/bundles/wallabagcore/themes/material/js/material.min.js></script><title>Welcome to wallabag! – wallabag</title><body class=login><div id=main><main><div id=content><main class=valign-wrapper><div class="valign row"><div class="card sw"><div class=center><img src=/bundles/wallabagcore/themes/_global/img/logo-other_themes.png alt="wallabag logo"></div><form action=/login_check method=post name=loginform><div class=card-content><div class=row><div class="input-field col s12"><label for=username>Username</label>
<input id=username name=_username></div><div class="input-field col s12"><label for=password>Password</label>
<input type=password id=password name=_password></div><div class="input-field col s12"><input type=checkbox id=remember_me name=_remember_me checked><label for=remember_me>Keep me logged in</label></div></div></div><div class="card-action center"><input type=hidden name=_csrf_token value=uRzahXBicONfSl_AvFKFSe6cBPXenB8GnhY_sAkLj1U><a href=/register/ class="waves-effect waves-light grey btn">Register</a>
<button class="btn waves-effect waves-light" name=send>Login
<i class="material-icons right">send</i></button></div><div class="card-action center"><a href=/resetting/request>Forgot your password?</a></div></form></div></div></main></div></main></div>
```

**Comment by di72nn** [comment]
Good to know that you solved your problem. And thanks for posting the minified version of the page. We'll see (eventually) what can be done on the app side.

// On an unrelated note: you might want to try our beta version. You can [opt-in for beta-testing on GPlay](https://play.google.com/apps/testing/fr.gaulupeau.apps.InThePoche) or [download an APK](https://github.com/wallabag/android-app/releases).

**Comment by brettlangdon** [comment]
:+1:

Want me to leave this issue open? Or else we can modify the title to be more applicable "Login failed with minified HTML" or something.

Also, signed up for beta, thanks! :)

**Comment by di72nn** [comment]
Created a separate issue.
