### ISSUE TITLE
Text to Speech (android)

### ISSUE THREAD

**Issue by nicosomb** [wallabag/android-app#5]
It really needs text to speech option . This is my favourite feature of pocket on android. Great to listen to articles at the gym. TTS engines like IVONA are really very fluent these days and can read very humanly with excellent intonation.

See https://github.com/wallabag/wallabag/issues/263

**Comment by tyndare** [comment]
I started to work on this
https://github.com/tyndare/android-app/commits/tts-support

**Comment by nicosomb** [comment]
It's done :+1:
