### ISSUE TITLE
Better name for user ID to avoid confusions (Was : List Articles does not synchronize)

### ISSUE THREAD

**Issue by bugabinga** [wallabag/android-app#50]
Tested on Nexus5 with CM11 and Nexus 10 with Android 5.

Hitting **_List articles**_ and **_Synchronize**_ do not update the list. Web interface works fine.
Also, Sharing with **_Bag it!**_ works on both devices.

[logcat](http://paste.debian.net/132384/)

**Comment by michaelcadilhac** [comment]
Same for me here; I put my username and password as UserID and token, then took a few minutes to see if there was a newer version of the app on GitHub.  I believe simple modifications could help the user to input the correct info.  In particular, if UserID is not a number, a message such as "Your UserID does not look like one.  Make sure it matches that from the config page of your wallabag." can be prompted.  Cheers, and happy hacking!

**Comment by holocronweaver** [comment]
I did the same as above, mistaking user ID, for, well, a user ID. I think "User Number" would be more clear, but using the user name instead of a number makes the most sense.

**Comment by tcitworld** [comment]
Yeah, you're right, but since the next major version 2.0 will completely change the system, I don't think we will change this now.

**Comment by di72nn** [comment]
Legacy version is no longer supported.
