### ISSUE TITLE
Add article title when using "share" options

### ISSUE THREAD

**Issue by El-Gavy** [wallabag/android-app#500]
Could it be possible to automatically add the title of the article / Item when shared to Twitter, Facebook, or other ? (done this way for News apps like Le Monde for instance).

![screenshot_2017-04-06-12-20-35](https://cloud.githubusercontent.com/assets/26960332/24749500/9230dba4-1ac3-11e7-98d0-0a8c93cdd12d.png)

**Comment by di72nn** [comment]
Probably the same as #284.

To everyone: if we just add a title to the shared text, it won't break anyone's workflow, will it? We already append the `via @wallabagapp` part, so if someone needs the URL, they have to parse it anyway.

**Comment by di72nn** [comment]
Which text format is desired?
 * `Title URL`.
 * `Title - URL`.
 * `Title\nURL`.
 * Something else.


cc @Simounet

**Comment by El-Gavy** [comment]
If \nURL works everywhere, i think it is the best. If not sure, go with just the space (thinking about Twitter's 140 characters limitation).

**Comment by Simounet** [comment]
Title URL seems to be fine to me. We can rework after that but all we need is the info.

**Comment by nicosomb** [comment]
Not sure if `\n` is OK everywhere.

Title URL is ok for me.

**Comment by di72nn** [comment]
Everyone concerned please see #536.
