### ISSUE TITLE
Inadequate error message in case of server-side error

### ISSUE THREAD

**Issue by sallirom** [wallabag/android-app#517]
Hi, 

this is a strange issue, I will try to explain the problem here.

From one day to the next, my app won't sync. I have deleted the database of articles, uninstalled and installed again, even went backwards trying earlier versions. I just does not work. I've been using it for years, with no issues whatsoever.

I go through the installation wizard and everything reads ok. I get the token, the user, everything. It says all is good, but when I try to sync I get the "please, configure your app first" message.

I run cyanogenmod on a rooted device but, as I said, I've been using the app smoothly with no issues, so I don't think there is a connection with that. I just happened after the last upgrade.

Note that when I bag an article from my cellphone it appears on the web if I connect with the browser on my pc. It's crazy.

Thanks for your time.

**Comment by di72nn** [comment]
I presume you're using one of the v1.12.* versions (not the v2 beta). Is it correct?

Which server version are you using? If self-hosted, please also specify installation method.

**Comment by sallirom** [comment]
yes, sorry, I didn't give you enough information

I am using wallabag 1.12.2 from f-droid

the service is hosted at framabag (https://framabag.org/) a free service located in France

**Comment by di72nn** [comment]
No error notifications appear in the notification area?

Can you go to Settings -> Connection, press "Autofill" and check that it finishes successfully (with "Parameters filled" Toast message)?

Have you changed your wallabag account password recently?

**Comment by Strubbl** [comment]
Framabag is using wallabag 1.9.1 and not v2 yet.

**Comment by sallirom** [comment]
Hi,

yes, I get one error in the notification area. It says "incorrect configuration"

(a caption)
https://lut.im/MUjFAx8ubk/iUYjDuE3wLFF7nIw.png

I've already tried  "auto-fill" and it says everything is ok, but then there is no synchronization.

I logged into my account using the browser, I even changed my user token. Then I used "auto-fill" on my phone. The token changed to the one I saw in the browser, but I still couldn't synchronize. 

I used the first-time wizard again, and got the same result (but confirmed there is no problem with the password).

https://lut.im/gallery#qaA0oS02CD/gjQWlDCaM6Lary34.png

After closing the app and opening it again, it says something amiss happened with the connection, and asks to reconfigure. I do this and it says the parameters are correct, but still no synchronization.

https://lut.im/BKrCTbY40N/eHCrYFOm7uZWHWpX.png


thanks for your time.

**Comment by di72nn** [comment]
Can you access the RSS feeds from you browser (links are available on the config page)?

**Comment by sallirom** [comment]
that's it!

favorites and archive are ok, but unread gives me this error:


ERROR 500 - Internal Server Error!
The following error occurred:

The requested URL caused an internal server error.

If you get this message repeatedly please contact the webmaster.


I am sorry to have wasted your time, since there is no issue related to the app, the error is on the server side.

Thank you so much for your help.

**Comment by di72nn** [comment]
The app should show a different type of error, so it's good that we found that problem.

Anyway, framabag will be updated to wallabag v2 eventually.

**Comment by di72nn** [comment]
Fixed in `v1_legacy`.
