### ISSUE TITLE
Problème de connection après la dernière mise à jour

### ISSUE THREAD

**Issue by Eliesemoule** [wallabag/android-app#528]
Bonjour,

Depuis la dernière mise à jour (2.0.0) sur mon Nexus 5X en version 7.1.2 (Build N2G47O), je ne peux plus me connecter à mon instance Wallabag personnel (2.2.2) alors que cela fonctionnait très bien avant la mise à jour de l'application. J'obtiens l'erreur "Impossible d'accéder à l'API : '"error":"access_denied","error_description":"OAuth2 authentication required"} lors du test de l'API. Le problème est reproduction sur Nvidia SHIELD Tablet K1 en version 7.0 (Build NRD90M)

Si vous avez besoin de plus de renseignements ou que je fasse des tests n'hesitez pas à me le dire.

Sinon super appli. Merci !

**Comment by di72nn** [comment]
Hi.

In the web UI go to "API clients management" (or "Developer \<something\>" - it was renamed in one of recent versions). Check if there is "Android app - #*x*" under "Existing clients" on that page.

Also, which installation method did you use to set up your wallabag server?

**Comment by Eliesemoule** [comment]
Hi,

Yes, Android app exist under existing client. I use the recommended way on dedicated web server to install my server (https://doc.wallabag.org/en/admin/installation/installation.html). I created a virtual with the same documentation.

**Comment by di72nn** [comment]
Have you tried any other client that works via API (for example [wallabagger extension for web browsers](https://wallabag.org/#applications))? If you haven't, can you try it out? Depending on whether it works, we can decide on the further course of actions.

**Comment by Eliesemoule** [comment]
I tried with Wallabager for Chrome and I can't save page. After configuring extension, "Wallabag API token" is Granted when I click "Get token" button but if I reopen extension page "Wallabag API token" is expired. I don't know why

**Comment by di72nn** [comment]
The problem seems to be caused by the server. You should probably [create an issue in the main wallabag repo](https://github.com/wallabag/wallabag/issues).

"OAuth2 authentication required" was mentioned in wallabag/wallabag#2768, but it may be something else.

**Comment by di72nn** [comment]
A server-side issue.
