### ISSUE TITLE
SSL Cert.Validation error

### ISSUE THREAD

**Issue by St0bsel** [wallabag/android-app#531]
On version 2 of the App I Recive the error

> unknown error: java.security,cert,CertPathValidatorException: Trust anchor for certification path not found.

In version 1 I could have set "accept all SSL Certs." Please add this setting in the new version. Because without you can't use wallabag with a cheap SSL cert.

**Comment by tcitworld** [comment]
> a cheap SSL cert.

Let's Encrypt certificates are free...

**Comment by tcitworld** [comment]
And if needed, just add your certificate to Android and you're good to go.

**Comment by di72nn** [comment]
See #516 for the fix: you need to configure your server properly.

See #532 regarding "accept all SSL Certs" option.

If you need further assistance, reopened the issue.
