### ISSUE TITLE
Freeze on low connectivity

### ISSUE THREAD

**Issue by Simounet** [wallabag/android-app#540]
Hi there,
Since the last app update, the app freezes when I mark an article as read on low device connectivity. I tried to reproduce that with the emulator but doesn't seems to work.

**Comment by di72nn** [comment]
Does it happen when there is a background update operation?

**Comment by Simounet** [comment]
Yes, it is.

**Comment by di72nn** [comment]
The update operation blocks all DB write attempts until it is finished. Unfortunately, a lot of actions depend on writing to DB, so everything freezes.
Before v2 ever read access was be blocked too, so you wasn't even able to open article list.

Anyway, all those long operations (update and sync) should be rewritten to use shorter transactions.

**Comment by di72nn** [comment]
Changes are still queued in a non-reliable service (#974), but the UI no longer freezes (#931).
