### ISSUE TITLE
Add "untagged items" filter

### ISSUE THREAD

**Issue by pVesian** [wallabag/android-app#547]
Hi.

Please add "untagged items" to the tag list, to filter items by it.
Thanks!

**Comment by ngosang** [comment]
+1

**Comment by NWuensche** [comment]
I'm going to try adding this feature.

**Comment by NWuensche** [comment]
Is it a good idea to try adding a "fake" tag that you use to append the returned list of `getItems()` in the TagListFragment?

**Comment by di72nn** [comment]
That is probably ok.

**Comment by NWuensche** [comment]
Which id should I use to create the tag? Can you help me there please?

**Comment by NWuensche** [comment]
Can someone please help me?

**Comment by jalcine** [comment]
@NWuensche perhaps making a "phony", fixed ID? Can you point me to some code showing what you're looking at? If it's an Android ID, it could just be "R.id.tagsPhony".

**Comment by di72nn** [comment]
Done.
