### ISSUE TITLE
Dark with high contrast theme: Active menu item is not readable

### ISSUE THREAD

**Issue by pVesian** [wallabag/android-app#558]
Hi,

Please look at the "tags" link below. 
Thanks ! 

![tmp_10556-screenshot_20170612-1237272097911482](https://user-images.githubusercontent.com/3509962/27030414-69b2c1be-4f6c-11e7-9c5f-5c15e56f63b1.png)

**Comment by ngosang** [comment]
Duplicate of #552

**Comment by di72nn** [comment]
Thanks for reporting. Added this screenshot to #552.
