### ISSUE TITLE
Reduce header height on article

### ISSUE THREAD

**Issue by pVesian** [wallabag/android-app#569]
Hi,
Since I'm used to Pocket, I'm going to suggest a feature they have: when reading an article, a tap will hide everything, the menu & even the Android notification bar. I think they do a fullscreen. That way there is much more content on screen. It reappears on a tap or when scrolling up.
Related to #442, but this is for article only.
Thanks!

**Comment by Strubbl** [comment]
I guess, this is a duplicate of #114

**Comment by pVesian** [comment]
#114 doesn't seem specific to an article. @tcitworld, thoughts?

**Comment by tcitworld** [comment]
#114 should mostly be on article view for comfort, on the rest it's not that important.

**Comment by pVesian** [comment]
@Strubbl So it appears indeed to be a duplicate. Can you please close it?
