### ISSUE TITLE
Issue with the wallabag's 2.3 branch

### ISSUE THREAD

**Issue by Simounet** [wallabag/android-app#577]
Hi there,
I'm using the 2.3 branch and I'm encountering a strange issue. I added [this entry](http://www.lemonde.fr/m-perso/article/2017/06/25/antoine-de-caunes-je-veux-avoir-le-droit-de-tatonner_5150728_4497916.html) to wallabag then get it on the Android app. If I try to mark it as read, I've got an error on https://github.com/wallabag/wallabag/blob/2.3/src/Wallabag/CoreBundle/Helper/ContentProxy.php#L107 .
```
"Type error: DateTime::__construct() expects parameter 1 to be string, object given" at /wallabag/src/Wallabag/CoreBundle/Helper/ContentProxy.php
```
I don't have any issue from the web view.

**Comment by nicosomb** [comment]
I wonder why this function is called when you only mark the entry as read (I didn't dive into the code to check what's happened). @di72nn any idea? 

Do you have the same behavior with the web app?

**Comment by Simounet** [comment]
I don't have any issue with the web app.

**Comment by di72nn** [comment]
Server log entry from gitter chat: `PATCH /api/entries/6806.json HTTP/1.1" 500 3720 "-" "okhttp/3.6.0`.

**Comment by di72nn** [comment]
Moved to wallabag/wallabag.
