### ISSUE TITLE
Dark theme issue: text selection

### ISSUE THREAD

**Issue by ngosang** [wallabag/android-app#599]
In dark theme (high contrast), you can't distinguish selected text because background is black.
![screenshot_2017-07-01-08-53-47](https://user-images.githubusercontent.com/10577978/27759886-23b239b4-5e3b-11e7-9629-2525f10eb806.png)

Related to dark theme: #552

**Comment by aryanshar** [comment]
I believe i can fix this issue. I have started working on it !

**Comment by NWuensche** [comment]
I will close this issue as #808 fixed it. If i was wrong and the issue still persists please reopen or create a new issue.
