### ISSUE TITLE
Adding multiple servers

### ISSUE THREAD

**Issue by aurora-potter** [wallabag/android-app#604]
Provide support for adding multiple wallabag servers.

**Comment by di72nn** [comment]
What's the use case for this? I think that it is easier to install a second instance of the app to achieve similar result.

**Comment by aurora-potter** [comment]
I case a server is down, people could be able to use an alternative server.

It's a good idea if the synchronisation is done with one server and that server sends of a copy of that data to another server..

**Comment by Strubbl** [comment]
> if the synchronisation is done

when will that be done?

**Comment by di72nn** [comment]
Oh, now I can see what you mean.

It's not supported in the wallabag server. Even if it would, such a feature can be implemented using server-side load balancing, so there would be no need for client-side changes.

**Comment by aurora-potter** [comment]
Exactly. It just sends the command to the sever for a 'support sync'
