### ISSUE TITLE
Customisable database directory

### ISSUE THREAD

**Issue by aurora-potter** [wallabag/android-app#605]
Provide an option to explicitly specify the wallabag database location in the system.

**Comment by Strubbl** [comment]
What is the use case here? Why should anybody want to do that? 
I do not care where the db is located on the phone.

**Comment by aurora-potter** [comment]
@Scrubbl
If the app is uninstalled, the user wouldn't have to download all the data again.

I don't know why you don't catch anything.

**Comment by Strubbl** [comment]
if i uninstall the app, i want every data of it to be gone. It makes more sense to easily backup and import essentienal files.

**Comment by aurora-potter** [comment]
Alright. despite not having much time. I'll grab a copy of the source and develop the features I need.

You go welll.

**Comment by di72nn** [comment]
For the record: there is no UI for this, but the app should work with custom path if it is manually set in the preferences file (in the app data directory; probably requires root access). It may lack the permission to access external storage, though.

**Comment by aurora-potter** [comment]
I'm a reverse engineer. I got it.

**Comment by Strubbl** [comment]
> I'll grab a copy of the source and develop the features I need.

We welcome your PR.

> I'm a reverse engineer. I got it.

You already have the source. It should be easier now.
