### ISSUE TITLE
Search icon disappears after deleting saved articles

### ISSUE THREAD

**Issue by Xzenia** [wallabag/android-app#607]
While searching for and deleting some articles, the search icon disappears after going back to the unread tab. 

Recreating the bug:
1. Type in a keyword in the search bar.
2. Delete an article.
3. Press the back arrow icon or the back button on your phone.

![bug](https://user-images.githubusercontent.com/29501999/27869724-63bd647a-61d3-11e7-8605-104bd9a27b98.png)

**Comment by di72nn** [comment]
Thanks for the report.

I think it was fixed with #584 (not released yet).
