### ISSUE TITLE
Do you use code quality analysers?

### ISSUE THREAD

**Issue by aurora-potter** [wallabag/android-app#608]
check out https://github.com/marketplace/category/code-quality

**Comment by Strubbl** [comment]
no. and there are several lint issue still open. We welcome pull requests

**Comment by aurora-potter** [comment]
All of the code quality testing services above are free for open source projects.

**Comment by Strubbl** [comment]
Yes i know. It would be nice if you could improve this app with the help of them.

**Comment by aurora-potter** [comment]
@Scrubbl
I wanna be in the developement group of Wallabag.

**Comment by Strubbl** [comment]
What do you mean?

**Comment by tcitworld** [comment]
Not yet. Do some things and we'll see. I leave the choice of the tools to the rest of the team.

**Comment by aurora-potter** [comment]
Alright. I'll develop some code related to features I want and give it to you.

**Comment by Strubbl** [comment]
That would be helpful. You can leave the issue open until then if you want.
