### ISSUE TITLE
How to setup Wallabag Android when using Framabag?

### ISSUE THREAD

**Issue by pierrrrrrre** [wallabag/android-app#61]
Hi,

I just set up an account on Framabag, and wanted to use the Android app on my device... except I have no idea how to configure it, and I could not find any documentation anywhere to help me do so.

So, if using Framabag, what do I have to put in the different fields (`Wallabag URL`, `User ID`, `Token`)?

It would be good to explain this in Wallabag documentation as well I think...

Thanks in advance for your feedback!

**Comment by tcitworld** [comment]
I think it's planned to put this into documentation. The values you must enter are displayed in the config page of Framabag/Wallabag.

**Comment by pierrrrrrre** [comment]
Thanks!

I found how to use it:

1. in Wallabag Config page, under the Feeds section, press the link to generate a token
2. the token and user ID information will be displayed and can be used in the Android app.

I was confused because of the meaning of "Feeds"...
