### ISSUE TITLE
Getting HTTP 403 after archiving article

### ISSUE THREAD

**Issue by koichirose** [wallabag/android-app#617]
I'm logged in to my wallabag instance (I see Android App as a listed client on the web app).
It correctly performs the first update and if I add a new article from the website, the app then correctly fetches it.

If I archive an article from the app, I get a "UnsuccesfulResponseException: HTTP response: 403 forbidden" and the archived article of course is not synced back to the server.
Also I can't even fetch new articles anymore after this, I have to run the connection wizard again and re-sync everything.

My wallabag instance is on HTTP, not HTTPS, could that be an issue?
Even so, it should not allow my to login at all...

How can I fix this?

Edit:
app version: 2.0.1 (105)
backend: 2.2.3 (commit 82307d8)

**Comment by Strubbl** [comment]
Currently i have no idea yet, why this happens. Is it possible for you to create a log (e.g. via `adb logcat`)?

**Comment by di72nn** [comment]
I'm only aware of a single type of action that results with 403: trying to access articles of a different user.

@koichirose can you try the following:
 * Go to "API clients management" (http://your.instance/developer) and remove all the clients there.
 * Wipe the Android app's data.
 * Use the connection wizard to connect to your server.
 * Test if that error still happens.

HTTP/HTTPS probably shouldn't matter for that, but I would advise to use HTTPS anyway.

**Comment by koichirose** [comment]
@di72nn I tried, same issue.
This also happens on another device connected to the same instance.

I can only see one "Android App" client at /developer, even though I'm connected with two of them. Is this right?

What else can I do?
More info: I have a single user, no 2FA, everything works via web.

@Strubbl do you still need the logcat? I think it's more server related.

**Comment by di72nn** [comment]
You can try wallabagger ([firefox](https://addons.mozilla.org/en-US/firefox/addon/wallabagger/), [chrome](https://chrome.google.com/webstore/detail/wallabagger/gbmgphmejlcoihgedabhgjdkcahacjlj)). If it happens there, then we can be sure it is a server side issue.

**Comment by koichirose** [comment]
Posting here again not to leave this issue open, but I'll now reference this in the server-side repo, as it doesn't seem android-app-related.
I just tried the Chrome extension. I can save articles, but then I can't edit them.

Here's an example, when I click the wallabag:
```
Request URL: http://mywallabag/api/entries.json
Request Method: POST
Status Code: 200 OK
Response:
{"is_archived":0,"is_starred":0,"user_name":"koichirose".....etc.}
```

Then, if I try to delete it:
```
Request URL: http://mywallabag/api/entries/1297.json
Request Method: DELETE
Status Code: 403 Forbidden
```

The response preview shows the default Apache 403 forbidden page. I thought I had some issues with URL rewrites but the /api/entries.json endpoint works, so I'd exclude that.

**Comment by koichirose** [comment]
Sorry, turns out it was an Apache issue.
I missed the bit where it says that on Apache 2.4 the VirtualHost config is a little different.
https://doc.wallabag.org/en/admin/installation/virtualhosts.html#configuration-on-apache

**Comment by tcitworld** [comment]
Yeah, we should put this in the default one now. \#todo
