### ISSUE TITLE
Bug in text selection/text copy

### ISSUE THREAD

**Issue by ngosang** [wallabag/android-app#619]
Wallabag app master branch
Android 6.0.1
If i select some text, the copy menu looks ugly:
![screenshot_2017-08-08-22-20-40-706_fr gaulupeau apps inthepoche debug](https://user-images.githubusercontent.com/10577978/29093325-be339b56-7c89-11e7-9c93-d71118883c55.png)

**Comment by NWuensche** [comment]
I will close this issue as #730 should have fixed the big black box and #808 fixed the black highlight color. If i was wrong and the issue still persists please reopen this issue or create a new issue.
