### ISSUE TITLE
[Nginx] unable to find my server

### ISSUE THREAD

**Issue by jribal** [wallabag/android-app#622]
Hi,

I have a working self hosted docker install with nginx redirection.

My nginx server does not listen to port 443. The project basic configuration gives me bad redirection
`failed to connect to mywallag.com/myexternalip (port 1443) after 10000ms`
So I tweaked a bit and I added `proxy_set_header Host $host`; 
Which fix this issue but the android app now shows me "Fail Wallabag service not found; check URL"

How can I find a way to connect the app ?
```
server {
listen 1443 ssl http2;
server_name mywallabag;

ssl_certificate           /etc/letsencrypt/live/*****/fullchain.pem;
ssl_certificate_key       /etc/letsencrypt/live/****/privkey.pem;
ssl_trusted_certificate   /etc/letsencrypt/live/*****/fullchain.pem;
ssl_dhparam               /etc/ssl/dhparam.pem;
ssl_session_cache  shared:SSL:2000m;
ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
ssl_session_timeout 360m;
ssl_stapling on;
ssl_stapling_verify on;
ssl on;
ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:ECDHE-RSA-AES128-GCM-SHA256:AES256+EECDH:DHE-RSA-AES128-GCM-SHA256...
server_tokens off;
add_header X-XSS-Protection "1; mode=block";
add_header X-Content-Type-Options nosniff;
add_header Strict-Transport-Security "max-age=31536000; includeSubdomains; ";

location / {
        proxy_pass http://localhost:8084;
        proxy_set_header X-Forwarded-Host $server_name;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $remote_addr;
  }

location ^~ /register {
    deny all;
    return 403;
  }
}
```

**Comment by Strubbl** [comment]
Maybe you need to add a trailing slash to your config line

before
`        proxy_pass http://localhost:8084;`

after
`        proxy_pass http://localhost:8084/;`
?

**Comment by jribal** [comment]
Thanks for the quick replies.

I have this :
```
curl -I https://mywallabag

HTTP/1.1 302 Found
Server: nginx
Date: Mon, 21 Aug 2017 14:37:27 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
X-Powered-By: PHP/7.1.5
Set-Cookie: PHPSESSID=f1709856c71d2886598c445cd04c6d72; path=/; HttpOnly
Cache-Control: private, must-revalidate
Location: http://mywallabag/login
pragma: no-cache
expires: -1
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Strict-Transport-Security: max-age=31536000; includeSubdomains;
```
Code 302, a redirection indeed.

I would like to be able to visit http://mywallabag/ and be redirected to login/unread page while having the android app functionnal.

**Comment by jribal** [comment]
@Strubbl 
Thanks for your input but it does not fix my issue. It makes no difference for me.

**Comment by jribal** [comment]
I checked my /varl/log/nginx/error.log.
```
open() "/usr/share/nginx/html/login" failed (2: No such file or directory), client: *.*.*.*, server: play.myserver.com, request: "GET /login HTTP/1.1", host: "save.myserver.com"
```
And dumb me I forgot a ';' in my nginx config redirection from http to https.
I don't know why it worked fine everywhere but within the app.

Now it works with or without trailing slash, thanks for your support.
Android app works great now.

**Comment by di72nn** [comment]
I'm glad to hear you sorted this out. Can you give some more details on how you fixed it? Similar cases come up from time to time - it would be good to have answers to some frequent problems.

**Comment by jribal** [comment]
Ok, It's a dumb error. I hope nobody will make the same.
I had this redirection:
```
server {
    listen 80;

    server_name play.myserver.com;
    server_name save.myserver.com

    return 301 https://$host$request_uri;
}
```
There is a missing ';' after save.myserver.com.
Android app fails with this weird configuration when anything else works fine.

**Comment by di72nn** [comment]
Thanks for the details.

**Comment by milomindrbindr** [comment]
Having the same issue, but my site config seems to be fine according to the previous error. Any help would be appreciated!

`server {
    listen 80;
    server_name wall.server.com;
    return 301 https://$host$request_uri;
}
# main server block
server {
        listen 443 ssl http2;

        server_name wall.server.com;

client_max_body_size 0;

        location / {
                proxy_pass http://192.168.1.111:8888;
                include /config/nginx/proxy.conf;
        }
`

**Comment by Strubbl** [comment]
you are missing a closing curly bracket before the second "server"
