### ISSUE TITLE
Give an option to hide articles with label from default list

### ISSUE THREAD

**Issue by severo** [wallabag/android-app#631]
One way to organize the articles is to assign them labels. This way they appear in the dedicated view, selecting the label. It would help a lot to have them disappear, at the same time, from the default view, in a "zero inbox" logic.
I imagine there could be a configuration option to change the default view to "label-free" view.

**Comment by Strubbl** [comment]
Sorry, i do not get the full use case. What speaks against the default way to mark articles as read?

Or do you just want a menu option in the sidebar, which is called "not labeled" and shows all articles without labels?

**Comment by severo** [comment]
Yes, the second option is OK.

**Comment by severo** [comment]
The second option would be ideal.

**Comment by di72nn** [comment]
I guess something like #563 should cover this case. Unfortunately, it is not even in development yet.

**Comment by severo** [comment]
It's a particular case of #563 indeed.

**Comment by di72nn** [comment]
There's an "untagged" list now (selectable from the tag list).

**Comment by severo** [comment]
Thanks!
