### ISSUE TITLE
Voice read doesn't work without Internet connection

### ISSUE THREAD

**Issue by eemantsal** [wallabag/android-app#634]
I'm a recent user of your app, and so far I'm loving it. I think I especially love the voice sintesyzer: I can hear my saved articles while I'm working out at the park or doing the weekly shopping or any of those routinary tasks that don't require much concentration but don't allow us to be reading our mobile's screen for many minutes. Now I can do more than just listening music (which is great, of course, but sometimes I like to know from my favoriute columnists or heard that blog post I hadn't the time to read the other day). Is fantastic.

But the downside is that it requires an Internet connection, and consumes a nice amount of data: about 10 min. took almost 5 MB from my data plan (I normally use the voice sintezyser at 170% speed; don't know if higher speed makes more data to be up/downloaded per minute).
Well, AFAIK both the sintesyzer software and the voice files are installed in our android devices by default, so, why the Internet connection? Couldn't all the process be done locally, on the device, keeping our data plans intact and also keeping what we hear private?
There's also the privacy issue I've mentioned: If I'm sending to Google's servers the articles I'm hearing, Google is associating what I listen with my device ID, IP address, SIM card serial number, location, and all those permissions that Android doesn't report but if we use some app like Xprivacy we "discover". Well, if an Internet connection is indispensable because the process can't be done only on the device, could you switch Google's servers for some other that are fairly good in regards to service's quality, but it's also privacy friendly, and, if possible, FLOSS?

Regards.

**Comment by di72nn** [comment]
Feel free to reopen if you have something to add.
