### ISSUE TITLE
scrolling with PAGE_UP/PAGE_DOWN keys only works with second keypress

### ISSUE THREAD

**Issue by silberzwiebel** [wallabag/android-app#636]
related to #620 and https://github.com/silberzwiebel/wallabag-android/pull/1#issuecomment-334997482 / #623 

After opening an article, the first keypress of a PAGE_UP or PAGE_DOWN is "catched" by the left back-button on the upper actionbar and not used to scroll the content. From the second keypress everything is working fine. Also replicable with the android emulator when sending keycodes 92 / 93 via `adb shell input keyevent 93`.

This does not happen with different keycodes (e.g. CAMERA, 27) which is kind of weird.

**Comment by di72nn** [comment]
First `KeyEvent` with `PAGE_UP`/`PAGE_DOWN` keycode and `ACTION_DOWN` action is consumed by system.

Maybe if we replace current actionbar with something newer, it will stop happening.
