### ISSUE TITLE
image cache: mark as nomedia

### ISSUE THREAD

**Issue by shtrom** [wallabag/android-app#641]
Perhaps a duplicate of #640. The cached images show up in the stock AOSP gallery, making a bit of a mess.

The image cache, or maybe the whole application data directory should be marked as non-media (e.g, by adding a `.nomedia` file in it), to prevent indexation.

**Comment by di72nn** [comment]
`<sdcard>/Android/data/` (or something like that) should already have a `.nomedia` file.

**Comment by shtrom** [comment]
On Sun 29 Oct 2017 at 09:41:41 +0000, Dmitriy Bogdanov wrote:
> `<sdcard>/Android/data/` (or something like that) should already have a `.nomedia` file.

Hum, mine doesn't. But it's probably as old as CM 11, so it might not have been
there at the time.

-- 
Olivier Mehani <shtrom@ssji.net>
PGP fingerprint: 4435 CF6A 7C8D DD9B E2DE  F5F9 F012 A6E2 98C6 6655
Confidentiality cannot be guaranteed on emails sent or received unencrypted.

**Comment by di72nn** [comment]
I have it on CM 11.

**Comment by shtrom** [comment]
On Sun 29 Oct 2017 at 04:13:03 -0700, Dmitriy Bogdanov wrote:
> I have it on CM 11.

Ok, I must have messed up my data at some point. I think this issue can
be closed.

-- 
Olivier Mehani <shtrom@ssji.net>
PGP fingerprint: 4435 CF6A 7C8D DD9B E2DE  F5F9 F012 A6E2 98C6 6655
Confidentiality cannot be guaranteed on emails sent or received unencrypted.
