### ISSUE TITLE
HTTP response: 500 Internal Server Error

### ISSUE THREAD

**Issue by pixelyo** [wallabag/android-app#649]
this is the error I get on my android phone when i am trying to sync with my wallabag server - [wallabag docker-compose](https://github.com/wallabag/docker#docker-compose):
```
Server error
Error: com.di72nn.stuff.wallabag.apiwrapper.exceptions.UnsuccessfulResponseException: HTTP response: 500 Internal Server Error
```
this is the corresponding server log message:
```
"POST /api/entries.json HTTP/1.0" 500 72 "-" "okhttp/3.8.1"
```

Can you help me here?

**Comment by Strubbl** [comment]
Looks like a server misconfiguration. Maybe you can also try with another client, e.g. with https://github.com/wallabag/wallabagger

**Comment by pixelyo** [comment]
@Strubbl it seems to be working with [wallabagger](https://github.com/wallabag/wallabagger), just seems to be a problem with the android app

**Comment by Strubbl** [comment]
Please have a look in your wallabg server log. It can be found in wallabag's folder under var/logs/prod.log
error 500 indicates that the server is not properly configured.

**Comment by pixelyo** [comment]
i think i have found the corresponding server log message:
```
"POST /api/entries.json HTTP/1.0" 500 72 "-" "okhttp/3.8.1"
```

after reinstalling the android app it seems to be working again, i will see if i can recreate the issue

**Comment by Strubbl** [comment]
Okay, thanks for the feedback. Please feel free to reopen if you can reproduce the error.
