### ISSUE TITLE
Take notes within wallabag

### ISSUE THREAD

**Issue by biva** [wallabag/android-app#650]
As suggested by @nicosomb (https://twitter.com/nicosomb/status/923495121697562624), I'd like to see a similar feature as the "Highlight" of Pocket (https://getpocket.com/blog/2017/10/introducing-continuous-playback-for-listen-and-highlighting-on-android/).

The idea is to select a text in an article, and save it as a note for a future use (sharing, remember, interesting part, ...)

Maybe something is needed on Server side?

**Comment by Strubbl** [comment]
@biva do you think this is a duplicate of #115?

**Comment by biva** [comment]
It looks like, yes! Sorry for the duplicate.
