### ISSUE TITLE
Unable to update application due to Parse error [Replicant 6.0/F-Droid]

### ISSUE THREAD

**Issue by Asara** [wallabag/android-app#652]
Currently have version 2.0.1 installed.  When trying to update to 2.0.2, I get an error saying: Parse error.  There was a problem parsing the package.

**Comment by Strubbl** [comment]
Hello Asara, thanks for reporting. Is the error thrown by the F-Droid app?

**Comment by Asara** [comment]
I'm currently using the newest version of F-Droid and have been experiencing this problem for quite some time now to be honest. I am able to side load wallabag and upgrade it that way (which I've done for the past few versions), but updating it through F-Droid throws that error.

After uninstalling and trying to reinstall it, I get the same error.

I want to say none of those causes (except possibly changes to the app's manifest file?) would be the problem.  I don't have problems installing any other apps from F-Droid, definitely have unknown sources enabled, and the app is compatible I assume, since I can sideload it.

**Comment by di72nn** [comment]
> I am able to side load wallabag and upgrade it that way

Where do you get an APK from?

You should extract an APK from F-Droid data directory and compare checksums.

**Comment by Asara** [comment]
@di72nn So just to find out, I tried to install the app via F-droid on the app which failed.  I proceeded to run:
```
adb root
adb pull /data/data/org.fdroid.fdroid/files/wallabag-2.0.2.apk
adb kill-server
adb install wallabag-2.0.2.apk
```

Which ran successfully and installed the app.  So I also don't think it is an incomplete package/broken apk problem.

**Comment by Strubbl** [comment]
Which F-Droid version are you running? I just saw they made the jump from 0.x to 1.0 etc.

**Comment by Asara** [comment]
I am now using 1.X, but was having this issue with 0.X as well.

I first noticed this issue (as per my IRC logs) around March of this year, when I upgraded from Replicant 4.2 to Replicant 6.0.  R6.0 is built with a base of LineageOS if that matters.

**Comment by di72nn** [comment]
Reopen if relevant.
