### ISSUE TITLE
Issue with html entities rendering

### ISSUE THREAD

**Issue by Kdecherf** [wallabag/android-app#655]
Wallabag for Android 2.0.2 does not render html entities correctly:

![screenshot_2017-11-20-22-41-10-696](https://user-images.githubusercontent.com/226063/33043144-a2effb98-ce44-11e7-87a7-b2259e39b274.jpeg)

And the same article from Wallabag web:

![2017-11-20-224152_1920x1080](https://user-images.githubusercontent.com/226063/33043149-aa3096c4-ce44-11e7-8439-fb980533cd23.png)

**Comment by NWuensche** [comment]
I tried out this article by 1) adding it via web and then 2) adding it via share in Android. In both cases, the title is displayed correctly. Therefore, I will close this issue. 
If this problem still occurs, please open a new issue.
