### ISSUE TITLE
Synchronisation incomplète de l'application sous android

### ISSUE THREAD

**Issue by AnyRoka** [wallabag/android-app#656]
J'utilise la version 2.0.2 de l'application android et un compte wallabag.it

Après connexion à l'app via l'assistant une partie des articles se synchronise mais il manque les 13 articles les plus anciens (48 / 61).

Lorsque je supprime un article sur l'app puis que je lance une synchronisation j'obtiens le message suivant : 
![084e909de02867a2](https://user-images.githubusercontent.com/33878059/33093116-59fe5aa2-cefc-11e7-8490-3cf7d6cf0ab1.png)

**Comment by di72nn** [comment]
Are you comparing "Unread" lists?

There is already an issue regarding deleting: #646.

**Comment by Strubbl** [comment]
@AnyRoka i am not very good in understanding french

**Comment by j0k3r** [comment]
Duplicate of https://github.com/wallabag/android-app/issues/646
