### ISSUE TITLE
PROTOCOL_ERROR when updating articles

### ISSUE THREAD

**Issue by techexo** [wallabag/android-app#667]
Hi,

Application side: Wallabag 2.0.2 (106) app installed via FDroid on Android 7.1.2 (LineageOS)
Server side: Wallabag 2.2.3 running on Debian 9 Stretch with Nginx 1.10.3 (HTTP/2 support enabled by default)

When I try to update articles on the wallabag 2.0.2 (106) app, I have sometimes the following error:
> Erreur: okhttp3.internal.http2.StreamResetException: stream was reset: PROTOCOL_ERROR

I am not absolutely sure that it is a wallabag error _per se_, as a similar issue was reported some time ago on okhttp's repository (https://github.com/square/okhttp/issues/1897) and it was an incompatibility of some kind between okhttp and nginx 1.9.5. However, I am running nginx 1.10.3 (with http2 support) and I checked in the package's sources that the fix (http://hg.nginx.org/nginx/rev/0e37389c0bd5) had actually been implemented.

My Nginx logs:

> [05/Dec/2017:22:58:43] "GET /api/entries.json?sort=updated&page=1&order=asc&since=1512483516&perPage=30 HTTP/2.0" 401 278 "-" "okhttp/3.8.1"
[05/Dec/2017:22:58:43] "POST /oauth/v2/token HTTP/2.0" 200 358 "-" "okhttp/3.8.1"
[05/Dec/2017:22:58:43] "GET /api/entries.json?sort=updated&page=1&order=asc&since=1512483516&perPage=30 HTTP/2.0" 200 534 "-" "okhttp/3.8.1"
[05/Dec/2017:22:58:43] "GET /api/entries.json?sort=created&page=1&order=desc&since=0&perPage=1 HTTP/2.0" 200 6301 "-" "okhttp/3.8.1"
**[05/Dec/2017:22:58:44] "-" 000 0 "-" "-"
[05/Dec/2017:22:58:44] "-" 000 0 "-" "-"**
[05/Dec/2017:23:16:41] "GET /api/entries.json?sort=updated&page=1&order=asc&since=1512483516&perPage=30 HTTP/2.0" 200 534 "-" "okhttp/3.8.1"
[05/Dec/2017:23:16:41] "GET /api/entries.json?sort=created&page=1&order=desc&since=0&perPage=1 HTTP/2.0" 200 6301 "-" "okhttp/3.8.1"
**[05/Dec/2017:23:16:41] "-" 000 0 "-" "-"
[05/Dec/2017:23:16:41] "-" 000 0 "-" "-"**
[05/Dec/2017:23:16:55] "GET /api/tags.json HTTP/2.0" 200 388 "-" "okhttp/3.8.1"
[05/Dec/2017:23:16:55] "GET /api/entries.json?sort=created&page=1&order=asc&since=0&perPage=30 HTTP/2.0" 200 295182 "-" "okhttp/3.8.1"

The `"-" 000 0 "-" "-"` entries seem to match pretty well when the android app is showing the error.

Do you have any idea what the problem could be or how I could give you more information about the issue?

Thanks!

**Comment by Strubbl** [comment]
> I have sometimes the following error

When do the errors occur? Are they reproducible? Or what means sometimes?

Do you have any messages in your wallabag log? It can be found in the servers install dir in var/logs/prod.log

**Comment by techexo** [comment]
Actually I am not able to reproduce this error after purging the database in the app.

It was probably a misconfiguration in the app following the server "upgrade" from HTTP/1 to HTTP/2.

Sorry for the wasted time!

**Comment by Strubbl** [comment]
Thanks for the feedback. I am closing the issue now

**Comment by techexo** [comment]
I think I managed to reproduce the error!

The error occurs when the app try to clean-up "remotely removed" articles ("nettoyer les articles supprimés", in French) after a fast sync or when selecting the option in the menu.
As it should, the error disappears when unchecking in the sync parameters automatic clean-up after a fast sync ("activer le nettoyage des articles supprimés après une synchronisation rapide"). The error is not triggered when doing a full sync.

Knowing that, I am able to reproduce the error anytime by deleting an article via the web interface on the server then trying to clean the removed articles on the app.

I hope this info can help to re-open the ticket :)

**Comment by di72nn** [comment]
Do you have something unusual in the server logs for `/api/exists*`?

**Comment by techexo** [comment]
When no change have been made on the server (deletion-wise), I have the following request in nginx's access logs:
> "GET /api/entries.json?sort=created&page=1&order=desc&since=0&perPage=1 HTTP/2.0" 200 74751 "-" "okhttp/3.8.1"

When an article has been deleted on the server:
>"GET /api/entries.json?sort=created&page=1&order=desc&since=0&perPage=1 HTTP/2.0" 200 74751 "-" "okhttp/3.8.1"
"-" 000 0 "-" "-"
"-" 000 0 "-" "-"

I grep'd my logs for `/api/exists` without any result (can I assume that it should be there instead of the "-" 000 0 "-" "-" ;) ?)

**Comment by techexo** [comment]
@di72nn & @Strubbl, I finally sorted it out. After putting nginx's logs at debug level, I saw the following error

> client exceeded http2_max_field_size limit while processing HTTP/2 connection

Rising the values in the configuration to `http2_max_field_size 16k; http2_max_header_size 32k;`, the error disappears!

**Comment by Strubbl** [comment]
Thank you very much @techexo for reporting back what fixed your issue. 👍
