### ISSUE TITLE
Text-to-speech start and stop

### ISSUE THREAD

**Issue by ntnsndr** [wallabag/android-app#670]
This is a relatively minor issue, but here's something that comes up for me while listening to Wallabagged articles using the text-to-speech feature.

Expected: *During playback, when I press the on/off button on my headphones, it pauses. When I press it again, playback begins again where I left off.*

Actual: *During playback, when I press the on/off button on my headphones, it pauses. When I press it again, playback begins at the beginning of the article.*

Is there any way to make the behavior reflect the Expected?

**Comment by di72nn** [comment]
#939.
