### ISSUE TITLE
Add author and date in the article (wallabag 2.3.0)

### ISSUE THREAD

**Issue by ngosang** [wallabag/android-app#671]
In Wallabag 2.3.0 author and publication date are available. Please show them in the app.

![imagen](https://user-images.githubusercontent.com/10577978/34177551-4ba9ce64-e504-11e7-8266-6e664c366639.png)

**Comment by silberzwiebel** [comment]
If I understood the app code correctly, it is using [this API wrapper](https://github.com/di72nn/wallabag-api-wrapper) written by @di72nn. So, first the API wrapper needs to have these new fields, then one can add this to the app (which shouldn't be that hard).

**Comment by xfilesee** [comment]
This is still an issue. Is it hard to fix?

**Comment by di72nn** [comment]
Done.
