### ISSUE TITLE
Cannot log into wallabag.it when 2 factor is enabled

### ISSUE THREAD

**Issue by betsythefc** [wallabag/android-app#685]
Wallabag.it supports 2FA over email. When logging in with the app, I get the error "Unknown page after signin". In order to log in I can't have 2fa enabled.

**Comment by Strubbl** [comment]
Yes, this is a known issue: #359
Closing this one as duplicate of #359

**Comment by betsythefc** [comment]
@Strubbl, whoops, I searched and didn't find a duplicate, thanks for linking.

**Comment by Strubbl** [comment]
no problem :)
