### ISSUE TITLE
feature : show password

### ISSUE THREAD

**Issue by Grummfy** [wallabag/android-app#696]
Hello,
I mainly use generated apssword like this "Qk/3 ge?]z4N}vr!8zcHI`ew$h2{WVn92", so when you need to enter it in a mobile is like a nightmare. But if you do a mistake, most of the time, you just click on show password button. Unfortunatelly wallabag doesn't have this option, is it possible to add it?

thanks

**Comment by Xenios91** [comment]
The code for this issue is implemented " app:passwordToggleEnabled="true"" this should probably be marked resolved.

**Comment by Strubbl** [comment]
Thanks for the reminder.

Yes issue has been resolved with PR #725
