### ISSUE TITLE
Apply full material design

### ISSUE THREAD

**Issue by aurora-potter** [wallabag/android-app#698]
There're plenty of libraries, design guidelines, fonts, icons and background all freely available that could make beautify wallabag.

**Comment by Strubbl** [comment]
Of course you are right. An app can always be more beautiful, shinier or easier to use. Unfortunately, this generic issue does not provide any concrete measures to help us to improve the app. If you could split up your issue "Apply full material design" into several more concrete ideas and proposals, e.g. supported by some screenshots or graphics or source code (pull request) that would help much more. It is easier to continuously improve the app in small steps.

Also i do not think it is good idea to arbitrarily pull in new dependencies in form of libraries if they are only used to make the app more beautiful. We should stick to the options and support libraries of Google. There has to be a good reason to introduce a new library as dependency, which we have to maintain in future. 

Finally i am closing this issue. If you have a good, concrete idea how we can improve the app, please check the [open list of UI improvement ideas](https://github.com/wallabag/android-app/issues?q=is%3Aopen+is%3Aissue+label%3AUI) and if needed feel free to open a new issue.
