### ISSUE TITLE
Android app: automatic sync

### ISSUE THREAD

**Issue by nicosomb** [wallabag/android-app#7]
Currently people need to manually synchronize their Poche. This should be automatic in the background. If at all, something like pull-to-refresh in the list.

Also, the list of the actual articles should be the primary view, since that’s the important part.

See https://github.com/wallabag/wallabag/issues/404

**Comment by anarcat** [comment]
shouldn't the be closed? auto-sync seems to be implemented already...

**Comment by di72nn** [comment]
Outdated. See also #360.
