### ISSUE TITLE
UI: Display list of articles by default, move front buttons to menu

### ISSUE THREAD

**Issue by shtrom** [wallabag/android-app#70]
Once configured, one will more generally start the app to read articles. The front screen with the buttons is therefore a bit useless, and delays accessing the articles.

I think it would make sense to move these buttons to the soft menu of the article list (maybe with the sync button in the ActionBar), and present that first.

**Comment by kevmeyer** [comment]
I agree with you.  
Maybe we could also use a pull-to-refresh functionality to trigger the sync, if everyone is happy with it.

**Comment by tcitworld** [comment]
I totally with you two.

>  Maybe we could also use a pull-to-refresh functionality to trigger the sync, if everyone is happy with it.

Also, automatic sync when connection settings are saved. :)

**Comment by shtrom** [comment]
:+1: to Pull-to-refresh (:

**Comment by tcitworld** [comment]
Pull To Refresh is available. And the rest seems ok.
