### ISSUE TITLE
"DELETE /api/entries/100.json HTTP/1.1" 403

### ISSUE THREAD

**Issue by gr01d** [wallabag/android-app#701]
Hi, I am having problems in updating entries/adding/removing entries in wallabag android app v 2.0.2 (F-Droid release). In the server, I have enabled **apache-ultimate-badbot-blocker** and **modsecurity** with default settings before having this problem, logging has also been disabled in the server before this happened so this may be happening a while before I even installed those security tools. I have also tested wallabag after removing those two tools but it is still not working.

Here is the error in the server log: (apache)
**xxxx.net - - [11/Mar/2018:13:26:12 +0800] "DELETE /api/entries/100.json HTTP/1.1" 403 610 "-" "okhttp/3.8.1"**

in the android app:
**Error: Unknown Error: Error:com.di72nn.stuff.wallabag.apiwrapper.exceptions.UnsuccessfulResponseException:HTTP response: 403 Forbidden**

I also harden my Apache server by using **X-XSS protection**, **x-frame-options sameorigin**, and others. I am using SSL own instance of wallabag, the API can get new keys and client_ids but whenever I add/remove article, refresh it then it shows 403 error. I have the Require all granted in the wallabag.conf in the server.

After wiping the database of my android app wallabag, I can see the new articles I used in the web extension/addon of wallabag. But I cannot add new articles in the app unless I wipe the database and perform fullupdate again.

**Comment by Strubbl** [comment]
What wallabag server release version are you using?

**Comment by gr01d** [comment]
I've just git clone the master branch,it is the latest release. I followed this this tutorial: https://raspiblog.noblogs.org/post/2018/01/31/self-hosting-your-wallabag-to-your-raspberry-pi/

**Comment by Strubbl** [comment]
Okay, no problem. What is the hash of your current  commit in that repo? (just cd to the git repo and paste back the output of command `git log -1`.

**Comment by gr01d** [comment]
user@debian:/var/wallabag$ git log -1 

commit b1b4ae6f86bfe6fa2dca9abc879cd5c307b9626e
Author: Jeremy Benoist <jeremy.benoist@gmail.com>
Date:   Mon Jan 22 10:10:02 2018 +0100

    Release wallabag 2.3.2

**Comment by gr01d** [comment]
So, I again disabled the modsecurity and it worked! I now get **200** response code, however the app has a new erro message:` Error: com.squareup.moshi.JsonDataException: Expected an int b ut was NULL at path $.id`

I am now attempting to add whitelist rule for modsecurity, I also need what methods wallabag uses such as **GET, POST, DELETE, PATCH** so I can add a LimitException to my apache configuration:
```

<LimitExcept <wallabag PATCH GET DELETE POST...>
deny from all
</LimitExcept>
```
