### ISSUE TITLE
Erreur : okhttp3.internal.http2.StreamResetException: stream was reset : INTERNAL_ERROR

### ISSUE THREAD

**Issue by Ptiom** [wallabag/android-app#706]
Hello,

I have the following error when I try to synchronize the app with my own wallabag server : `okhttp3.internal.http2.StreamResetException: stream was reset : INTERNAL_ERROR`
The issue might not be due to my server because a friend doesn't have the same problem on the same server (just not the same account)
The difference are our phones and our android versions. I have an honor 7 with android 6.0 and my friend has a Samsung S7 with android 7.0.

The first synchronization works well but when I try to refresh, I get this error.

Thank you for your help,

Alexis.

**Comment by Strubbl** [comment]
What is the log of wallabag server saying? any error messages in var/logs/prod.log?

**Comment by Ptiom** [comment]
Hi,
I tried again this morning and I got these logs : 
`[2018-03-21 10:17:43] request.INFO: Matched route "api_get_entries". {"route":"api_get_entries","route_parameters":{"_controller":"Wallabag\\ApiBundle\\Controller\\EntryRestController::getEntriesAction","_format":"json","_route":"api_get_entries"},"request_uri":"https://wallabag.ptiom.fr/web/api/entries.json?order=asc&page=1&perPage=30&since=1521568867&sort=updated","method":"GET"} []
[2018-03-21 10:17:43] app.ERROR: Authentication failure for user "", from IP "80.12.37.37", with UA: "okhttp/3.8.1". [] []`

**Comment by Strubbl** [comment]
Unfortunately those log lines are ususal from wallabag server. I also have several ones like this, but my app sync is working. 

Which version of the app are you using?
Did you install the app via F-Droid, Google Play or manually?

Do you use nginx? Can you set nginx's logs to debug level and watch out for any issues with nginx? 
We had a kind of similar issue in #667.

**Comment by Ptiom** [comment]
Hi,
I use apache v2.4.29 on a shared wed hosting service (o2switch).
I install the app via Play Store. I have some friends who use my server and don't have the same problem.
That's why I don't think the problem comes from the server but from the client.
Differences are our mobiles phones, our Android versions and the fact that I use the admin account of my wallabag instance when they use "additional" accounts.

Hope it can help you.

Thank you for your time !

Alexis.

**Comment by kermorgant** [comment]
Hi @Ptiom 

Did you solve your issue ? 
I've just installed wallabag (2.3.6 on o2switch, like you) and face the same pb (android 7 device)

**Comment by di72nn** [comment]
Reopen if the issue still exists.
