### ISSUE TITLE
Set origin_url when adding articles from an article

### ISSUE THREAD

**Issue by Kdecherf** [wallabag/android-app#711]
When you click on a link in an article, wallabag offers you two options: _add to wallabag_ or _open in browser_.

It could be cool to forward the original article url when clicking _add to wallabag_ using the field `original_url`.

**Comment by Strubbl** [comment]
What is `original_url` about?

**Comment by Strubbl** [comment]
I cannot see a use of the original_url being saved in the database. Is that field anyhow evaluated or used? Did i overlook something in wallabag web?
Is it possible to view the original_url in a UI or use it in a tool?

**Comment by di72nn** [comment]
I don't know how to set it not via API, but that's how it looks in the web UI:
![Screenshot_2020-03-07_11-36-47](https://user-images.githubusercontent.com/1114779/76139327-27463800-6068-11ea-941c-b071bfa96ec6.png)

**Comment by Kdecherf** [comment]
Maybe we should rework this part, you can edit the `origin_url` from the web ui by using the _edit title_ form (_the blue pencil seen on the screenshot_)
