### ISSUE TITLE
Bug in deletion of articles

### ISSUE THREAD

**Issue by ngosang** [wallabag/android-app#719]
# Issue details
### Actual behaviour
- When I delete some article, the article is indeed deleted in the app and in the server but I get that notification.
![screenshot_2018-07-31-07-50-05-322_com miui home](https://user-images.githubusercontent.com/10577978/43468611-bd825ce6-94e4-11e8-954b-bd0ef71417e1.png)

### Expected behaviour
- Same behaviour but without the error notification

# Environment details
- **wallabag app version**: master branch
- **wallabag server version**:  2.3.2

**Comment by Kdecherf** [comment]
Duplicates #646
