### ISSUE TITLE
java.net.SocketException when internet connection stops while downloading an article

### ISSUE THREAD

**Issue by NWuensche** [wallabag/android-app#727]
# Issue details

When I download an article and the internet connection crushes while doing this, I get  " Error: java.net.SocketException: Software caused connection abort" as a notification.

### Duplicate?
Have you searched the issues of this repository if your issue is already known? yes

### Actual behaviour
- Tell us what happens

See the Issue details.

### Expected behaviour
- Tell us what should happen

There should be a notification that clarifies what went wrong, not an exception. 

# Steps to reproduce the issue
1. Add a big article (with photos) to the wallabag server
2. Start syncing
3. Shut down WiFi

# Environment details
- **wallabag app version**: 2.0.2-DEBUg (106)
- **wallabag app installation source** (e.g. Gplay, F-Droid, manual): GitHub Master
- **Android OS version**: 7.1.2
- **Android ROM** (e.g. stock, LineageOS, SlimRom,…): LineageOS
- **Android hardware**: Moto G2 (thea)
- **wallabag server version**: Can't find the version number, but it is self-hostet

# Logs
## wallabag server
Please paste relevant wallabag server logs here (from file `<wallabag>/var/logs/prod.log`):

## Web server
Please paste relevant web server logs (e.g. from nginx, Apache, …) here:

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here!

# Your experience with wallabag Android app
Have you had any luck using wallabag Android app before? (Sometimes we get tired of reading bug reports all day and a lil' positive end note does wonders)
Yup, works super fine when it is set up :) Never had any critical issues.

**Comment by Strubbl** [comment]
Thank you for reporting this issue.
If i understand your issue correctly, it is an edge case, because one usually does not shut down internet during wallabag syncing, or?

Are there any further consequences of that sync abort?

You can find the version info in the URL `/about`. You can get there via the links in the footer on every page.

**Comment by NWuensche** [comment]
Thank you for responding. Yes, you understood it correctly. However, the error sometimes happens to me when I'm in an area with bad mobile internet. 
I created the PR #728 for this. But I don't know right now how to send the notification to the user without the Context. Maybe you can help me there.
