### ISSUE TITLE
TTS Enable/Disable Bug

### ISSUE THREAD

**Issue by bezmi** [wallabag/android-app#735]
I am building the master branch via android studio. If I disable TTS while it is talking, the article disappears and we revert back to the article list screen. This does not happen in the version that is available on the app stores.

**Comment by Strubbl** [comment]
Sorry, i cannot reproduce your issue. Playing and stopping TTS works fine without issues. 
It would be nice if you can give more information like the one which is asked by the issue template.

**Comment by bezmi** [comment]
I'm on android 8.1, wallabag app version 2.0.2-DEBUG(106).
Steps to reproduce:
1. Open article
2. From top right menu, enable TTS
3. From same menu, disable TTS while it is speaking (without pressing stop)

Actual behaviour:
Article exits back to the article list after hanging on black screen for a second

Expected behaviour:
TTS stops and the TTS bar disappears without closing article

**Comment by bezmi** [comment]
So I tested on an emulator running api 25 and one on api 27. The bug is present on the api 27 device but not on 25. 

I ran a `git bisect` and found the commit that the bug first popped up in: c4e9a1de938f6012477b8893cf5e10ac59ff2525

I narrowed down the changes to the sdk version in gradle (26 -> 27) to be causing the bug. As soon as I reverted to sdk 26 on this commit, the bug disappeared.

**Comment by Strubbl** [comment]
Thank you very much for the analysis. Maybe our TTS expert @tyndare still follows the android development and has an idea how we can fix this issue?

**Comment by tyndare** [comment]
Thanks for the repport and notification. I have no idea for now, I'll try to look at it next WE.

**Comment by tyndare** [comment]
I hope I have found the problem and the solution here: https://stackoverflow.com/questions/47531742/startforeground-fail-after-upgrade-to-android-8-1
