### ISSUE TITLE
Wallabag Service Not Found - Check URL (Android APP)

### ISSUE THREAD

**Issue by andre-faria** [wallabag/android-app#737]
Issue details
Can't connect to Wallabag server with Android App, Using the browser it work as usual, I'm using a self-signed certificate (installed locally at my android too).

Environment
2.1.6-1201-g0f5c15d
via git clone
N/A
7.0.32
Ubuntu 16.04.5
Dedicated
MySQL
Android, with App version 2.0.2 (106)

Steps to reproduce/test case
Testing connection in Wallabag App via connection wizard or Autofill (Test connection and fill in client ID and client secrer).

**Comment by Strubbl** [comment]
Which webserver are you using? Do you minify the login page?

There were already several issues w.r.t to that error message. Did you check them? https://github.com/wallabag/android-app/search?q=Wallabag+Service+Not+Found+-+Check+URL+%28Android+APP%29&unscoped_q=Wallabag+Service+Not+Found+-+Check+URL+%28Android+APP%29&type=Issues

**Comment by andre-faria** [comment]
I'm using Apache Webserver.

What do you mean with minifying? I did't anything, I just followed the steps in this link:
https://www.linuxbabe.com/ubuntu/install-wallabag-ubuntu-16-04

**Comment by Strubbl** [comment]
The problem is, that our regex for the logo detection searches for:

`alt=\"wallabag logo\" ?/?>`

but finds in your page:

`alt="wallabag logo" class="typo-logo" />`

So our regex does not match. We need to adjust the regex in https://github.com/wallabag/android-app/blob/29231f9021323a5674576fc7d4b80848654312f0/app/src/main/java/fr/gaulupeau/apps/Poche/network/WallabagWebService.java#L32 accordingly.

Thank you for reporting the bug.

**Comment by andre-faria** [comment]
But this can break others users access???? Because if you made your rege to detect alt=\"wallabag logo\" ?/?> was because it was working.

**Comment by Strubbl** [comment]
it works fine with recent versions of wallabag server. Recent version use

`            <div class="center"><img src="https://wallabag.blabla.de/wallassets/themes/_global/img/logo-other_themes.png" alt="wallabag logo" /></div>`

**Comment by Strubbl** [comment]
But where does the `class="typo-logo"` come from if it is not default. It is also not seen on https://app.wallabag.it/login

Ah, I see, it is from the change of @Simounet in https://github.com/wallabag/wallabag/commit/4c78612eb47b235bc75a90d0aa7df51d654be0c7 which is not in an official release yet.

**Comment by Simounet** [comment]
Hello,
If you don't mind to install npm, you can launch `npm run build:prod`.

**Comment by andre-faria** [comment]
Got error messages when launch nmp run build:prod
`
> wallabag@2.3.3 build:prod /var/www/wallabag
> webpack --env=prod

sh: 1: webpack: not found

npm ERR! Linux 4.4.0-127-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build:prod"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! wallabag@2.3.3 build:prod: `webpack --env=prod`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the wallabag@2.3.3 build:prod script 'webpack --env=prod'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the wallabag package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --env=prod
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs wallabag
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls wallabag
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/wallabag/npm-debug.log
`

**Comment by Simounet** [comment]
Did you do a `npm install` before that?

**Comment by andre-faria** [comment]
> Did you do a `npm install` before that?

I did the command as root and it worked, well the problem really was that I was using the old version of wallabag, this can be closed, sorry for the spent time!

I cloned again using 'sudo git clone --branch 2.3.3 repo'
