### ISSUE TITLE
Android app empty, while server is full of article

### ISSUE THREAD

**Issue by klorydryk** [wallabag/android-app#738]
Android app : 2.02 (106)
Wallabag server: 2.3.2

After having manually transferred data from the android app to a fresh installation of Wallabag, I'm not able anymore to display anything in the android application. The application stays empty.
First time I synchronized (after fresh server installation and this manual importation), all articles disappeared. Now, if I'm able to *add* a new article, it never show up on Android app, but it appears in the Wallabag server web page.

How can I clean this mess, keeping my article list safe?
Thanks!

**Comment by Strubbl** [comment]
The android app syncs the articles from the web application. So if you can see all articles in the web app, you are fine to wipe your wallabag android app or reinstall it.

**Comment by klorydryk** [comment]
I've done that, tryning to remove the wallabag android app then reinstall it with the connection wizard. Connection is working fine. Then I'm on the interface... empty forever.

**Comment by m-strasser** [comment]
Same here, the issue seems to be the following:
Setting up the app via the Connection Wizard, everything seems to work fine, but the server logs state the following
```
request.INFO: Matched route "api_get_version". {"route":"api_get_version","route_parameters":{"_controller":"Wallabag\\ApiBundle\\Controller\\UserRestController::getVersionAction","_format":"json","_route":"api_get_version"},"request_uri":"https://my.instance/api/version.json","method":"GET"} []
app.ERROR: Authentication failure for user "", from IP "XXX.XXX.XXX.XXX", with UA: "okhttp/3.8.1". [] []
```

Server version is 2.3.3, app version is 2.0.2 (installed via F-Droid).

**Comment by Strubbl** [comment]
just for reference, in #739 the user was empty, too. but there it helped to rerun the assistant

please give some more information about your environment:

- **Android OS version**: 
- **Android ROM** (e.g. stock, LineageOS, SlimRom,…): 
- **Android hardware**: 
- **Do you have Two-Factor-Authentication enabled?**: yes/no

**Comment by klorydryk** [comment]
Android OS version: 8.1.1
    Android ROM (e.g. stock, LineageOS, SlimRom,…): LineageOS
    Android hardware: Oneplus One
    Do you have Two-Factor-Authentication enabled?: no

**Comment by di72nn** [comment]
There was probably some error that wasn't displayed due to broken notifications. #794.
