### ISSUE TITLE
Wallabag Service Not Found - Check URL (in Android App)

### ISSUE THREAD

**Issue by msebald** [wallabag/android-app#744]
# Issue details

### Duplicate?
Have you searched the issues of this repository if your issue is already known? Yes, and I found it several times, but old or not matching issues. Like #737 and #495.

### Actual behaviour
- Cannot log into Wallabag using the Android app, works with browsers, Wallabagger Chrome addon and also iOS app.

### Expected behaviour
- Login working with Android app also.

# Steps to reproduce the issue
1. I try to login into Wallabag through Android app
2. "Wallabag Service Not Found - Check URL" appears

# Environment details
- **wallabag app version**: 2.0.2
- **wallabag app installation source**: Gplay
- **Android OS version**: 8.1.0
- **Android ROM**: Stock ROM
- **Android hardware**: Xiaomi Mi A2
- **wallabag server version**: Github origin/master (up-to-date, made "git pull" today), self hosted server, HTTPS, did not activate minify
- **Do you have Two-Factor-Authentication enabled?**: no

# Logs
## Web server
pxxxxxxxx.dip0.t-ipconnect.de - - [12/Nov/2018:11:25:41 +0100] "GET / HTTP/1.1" 302 5386 "-" "okhttp/3.8.1"
pxxxxxxxx.dip0.t-ipconnect.de - - [12/Nov/2018:11:25:41 +0100] "GET /login HTTP/1.1" 200 1932 "-" "okhttp/3.8.1"

# Your experience with wallabag Android app
It worked without problems with Wallabag v1, but this is quite a while ago. As I cannot even log into the server I cannot say more about the app at the moment.

# Special Setup here
I am rewriting the urls to let it look nice. I do not want to see the web directory here. Also I disabled the register page as I do not want to have people registering accounts on my instance here.
The following setup is used in the Apache webserver:

RewriteCond %{HTTP_HOST} ^wallabag\.domain\.tld$ [NC]
RewriteRule !^web/ /web%{REQUEST_URI} [L,NC]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^(.*)$ app.php [QSA,L]
<FilesMatch ".*register$">
Order Allow,Deny
Deny from all
</FilesMatch>

I am happy to provide further information about my setup, problem, whatsoever. Unfortunally the lack of a working Android client stops me using Wallabag at all. I need to get it working. :-)

**Comment by Strubbl** [comment]
Thanks for opening this issue

The change of Simounet in wallabag/wallabag@4c78612 which is not in an official release yet, breaks our login page detection. I mentioned this in https://github.com/wallabag/android-app/issues/737#issuecomment-428340150 but forgot about it.

This issue can be fixed if the regex for login page detection is adjusted accordingly. So that it is compatible with the upcoming release, but also with older versions.

Until this is fixed, you can use the most recent release, which shall work.

**Comment by msebald** [comment]
Thank you @Strubbl, so I need to get the version before current master from Git? How? Sorry, I am not a developer, so my knowledge of Git is very very limited. Unfortunally.

**Comment by msebald** [comment]
Or the other way around, would it be a big deal to release a new version of the Android app with the regex adjustment? I am sure a lot of other people run in the same problem as I did.

**Comment by msebald** [comment]
Ok, I did the follow with some fellow help:

_src/Wallabag/UserBundle/Resources/views/layout.html.twig_ line 14 from:
<div class="center"><img src="{{ asset('wallassets/themes/_global/img/logo-wallabag.svg') }}" **alt="wallabag logo" class="typo-logo"** /></div>
to:
<div class="center"><img src="{{ asset('wallassets/themes/_global/img/logo-wallabag.svg') }}" **class="typo-logo" alt="wallabag logo"** /></div>

And the I deleted the Twig cache: _php bin/console cache:clear --env=prod_

Android app works now. :-)

Should I make a pull request with this change?

**Comment by Strubbl** [comment]
I do not know if we should fix the issue in the android app or at the server. And it does not matter, because for me both solutions are fine.

If you could make a pull request with that change against the server repo https://github.com/wallabag/wallabag/ that would be very good. Then, the wallabag core team can decide.

**Comment by j0k3r** [comment]
I merged the fix but I found it ugly to parse the webpage to determine stuff.
Maybe we should add these information in the API? (I haven't checked what you extracted btw)

**Comment by lockntross** [comment]
From the official docker repo:
https://hub.docker.com/r/wallabag/wallabag/builds/bmfyk43wc8ejmemwwpjcysb/

This is what my page is producing: 
<div class="center"><img src="https://wallabag.holtzweb.com/wallassets/themes/_global/img/logo-wallabag.svg" alt="wallabag logo" class="typo-logo" /></div>

Mobile App Cannot Find My Server :/
Same As Above.... I'd love to just update the docker image, making any changes will break upon update.
