### ISSUE TITLE
warn: removing resource without required default value

### ISSUE THREAD

**Issue by Strubbl** [wallabag/android-app#745]
# Issue details

### Duplicate?
Have you searched the issues of this repository if your issue is already known? no

### Actual behaviour
When building with travis the following warnings appear

```
warn: removing resource fr.gaulupeau.apps.InThePoche:string/downloadPdfArticleDownloaded without required default value.
warn: removing resource fr.gaulupeau.apps.InThePoche:string/downloadPdfArticleDownloadedDetail without required default value.
warn: removing resource fr.gaulupeau.apps.InThePoche:string/downloadPdfPathStart without required default value.
warn: removing resource fr.gaulupeau.apps.InThePoche:string/downloadPdfProgress without required default value.
warn: removing resource fr.gaulupeau.apps.InThePoche:string/downloadPdfProgressDetail without required default value.
warn: removing resource fr.gaulupeau.apps.InThePoche:string/downloadPdfTouchToOpen without required default value.
warn: removing resource fr.gaulupeau.apps.InThePoche:string/menuDownloadPdf without required default value.
```

e.g. for reference https://travis-ci.org/wallabag/android-app/builds/458614245#L2241

### Expected behaviour
no warning

# Steps to reproduce the issue
build with gradle wrapper

# Environment details
- **wallabag app version**:  b59d5d13a63af129d68dd3443a44c388f6fad704
- **wallabag app installation source** (e.g. Gplay, F-Droid, manual): 
- **Android OS version**: 
- **Android ROM** (e.g. stock, LineageOS, SlimRom,…): 
- **Android hardware**: 
- **wallabag server version**: 
- **Do you have Two-Factor-Authentication enabled?**: yes/no

# Logs
## wallabag server
none

## Web server
none

**Comment by di72nn** [comment]
[Doesn't seem to be an issue anymore.](https://travis-ci.org/github/wallabag/android-app/builds/722647100)
