### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by Perflyst** [wallabag/android-app#749]
Is it planned to release a new version? Last release was in October 2017 and since than there are more than 150 new commits.

**Comment by Strubbl** [comment]
Yes, that would be awesome.

@tcitworld can you please release a new version? 
I have drafted a release note "Version 2.0.3", please see https://github.com/wallabag/android-app/releases

**Comment by tcitworld** [comment]
Just published 2.1.0-beta here and on Play Store

**Comment by tcitworld** [comment]
Also here https://github.com/wallabag/android-app/releases/tag/2.1.0-beta

**Comment by Perflyst** [comment]
Will -beta work with F-Droid?

**Comment by klorydryk** [comment]
> 
> 
> Also here https://github.com/wallabag/android-app/releases/tag/2.1.0-beta

Do we need to remove the release before to install the beta? I get an error message "application not installed" when trying to install this version.

**Comment by tcitworld** [comment]
> Will -beta work with F-Droid?

@Perflyst That's up to the F-Droid people to handle the tags properly. Last time I checked they didn't, but maybe just it takes is to ping them about it.

**Comment by klorydryk** [comment]
> 
> @klorydryk Did you install from the .apk provided on the release page or through Google Play ?

Through F-Droid I assume.

**Comment by tcitworld** [comment]
@klorydryk Then you can only get versions from F-Droid unless you uninstall the app.

**Comment by tcitworld** [comment]
I guess I can close this specific issue.

**Comment by tcitworld** [comment]
> Then you can only get versions from F-Droid unless you uninstall the app.

And this should be over soon btw https://f-droid.org/en/docs/Reproducible_Builds/
