### ISSUE TITLE
Sync fails silently - show error message and debug logs

### ISSUE THREAD

**Issue by kai11** [wallabag/android-app#751]
# Issue details
I had prpblem with lots of shared urls - they werent uploaded to WB server.
I checked server logs and discovered 30 seconds php execution timeout errors.
I updated max_execution_time to bigger value and all ny urls were uploaded.
However, I did not saw any indication that sync was failed anywhere.

### Duplicate?
Have you searched the issues of this repository if your issue is already known?
yes
Similar error - silent failure on authentication - was in comments but I cannot find it now. 

### Actual behaviour
- If sync fails it fails silently. No toast, no notification and no logs.

### Expected behaviour
- Error message in notification area if connection timed out (or any other error occur)
- Sync logs in debug menu

# Steps to reproduce the issue
1. update server to small php timeout
2. add lots of urls
3. sync them all to server
4. Server will display errors in logs, but app wont.

# Environment details
- **wallabag app version**: 2.0.2
- **wallabag app installation source** (e.g. Gplay, F-Droid, manual): gplay
- **Android OS version**: 8
- **Android ROM** (e.g. stock, LineageOS, SlimRom,…): stock (motorola more or less is bare bones android)
- **Android hardware**: Moto Z Play
- **wallabag server version**: 2.3.1
- **Do you have Two-Factor-Authentication enabled?**: no

# Logs
## Web server
Please paste relevant web server logs (e.g. from nginx, Apache, …) here:
[Sun Dec 09 19:14:28.745703 2018] [php7:error] [pid 17431] [client 213.183.56.156:47572] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /ebs/wallabag/vendor/j0k3r/php-readability/src/Readability.php on line 734

# Your experience with wallabag Android app
overall is good because I often can see internals and make them work my way.

**Comment by di72nn** [comment]
Fixed with #794.
