### ISSUE TITLE
Connection test failed - wallabag service not found - check URL

### ISSUE THREAD

**Issue by kmlucy** [wallabag/android-app#752]
# Issue details

I'm using the official Docker image, but am not able to connect to the Android app. I get this error:
```
Connection test failed - wallabag service not found - check URL
```

I'm not sure whether this is an app issue, a Docker issue, or a server issue. I also opened https://github.com/wallabag/docker/issues/133.

# Environment details
- **wallabag app version**: 2.0.2
- **wallabag app installation source** (e.g. Gplay, F-Droid, manual): Google Play
- **Android OS version**: 9 (5 December 2018)
- **Android ROM** (e.g. stock, LineageOS, SlimRom,…): Stock
- **Android hardware**: Pixel
- **wallabag server version**: 2.3.3 (from Docker)
- **Do you have Two-Factor-Authentication enabled?**: yes

# Logs
## wallabag server
[2018-12-06 22:30:16] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /login/"" at /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 128 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /login/\" at /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:128, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/wallabag/var/cache/prod/appProdProjectContainerUrlMatcher.php:1012)"} []

## Web server
172.18.0.15 - - [06/Dec/2018:17:33:48 -0500] "GET / HTTP/1.1" 302 213 "-" "okhttp/3.8.1"
172.18.0.15 - - [06/Dec/2018:17:33:48 -0500] "GET /login HTTP/1.1" 200 1183 "-" "okhttp/3.8.1"
172.18.0.15 - - [06/Dec/2018:17:33:48 -0500] "GET / HTTP/1.1" 302 213 "-" "okhttp/3.8.1"
172.18.0.15 - - [06/Dec/2018:17:33:49 -0500] "GET /login HTTP/1.1" 200 1184 "-" "okhttp/3.8.1"
172.18.0.15 - - [06/Dec/2018:17:33:49 -0500] "GET /login/ HTTP/1.1" 404 300 "-" "okhttp/3.8.1"

**Comment by TinkerFu** [comment]
Same issue.  
Xperia x compact
Android 7.1.1
App from play store
Self hosted manual install - cloned from git a week ago
No two factor

Behind apache2 via https.  This was a working setup before upgrading to the 2.0.x version.  
Web interface works fine. 
DocumentRoot is correct  .../wallabag/web

**Comment by Strubbl** [comment]
Are you sure that you are using wallabag server 2.3.3? Because i would have expected this issue to occur starting with 2.3.4

i guess your issue is duplicate with #744 or #737 in which you can find more hints why this fails

I already started an issue to fix the root cause https://github.com/wallabag/wallabag/issues/3808

**Comment by kmlucy** [comment]
It is 2.3.4, my mistake.

**Comment by Strubbl** [comment]
I am sorry to tell you that this issue is only going to be fixed with server version 2.3.5 (not released yet). Or you can still use 2.3.3 and below.

**Comment by Strubbl** [comment]
2.3.5 has been released. https://github.com/wallabag/wallabag/releases/tag/2.3.5

**Comment by kmlucy** [comment]
Looks good, it's working with 2.3.5.

**Comment by ErikMonten** [comment]
I still have this issue today on my Samsung A40 , Android 9, self hosted wallabag version 2.3.8. On my laptop everything works fine. I have filled client id and client secret on my mobile and use my username and password, but still have error "connection test failed - wallabag service not found - check url".

**Comment by di72nn** [comment]
@ErikMonten you'd better create a new issue.

Anyway, have you tried using the connection wizard? Do you use any kind of web page minification on your server?
