### ISSUE TITLE
Wallabag 2.1.0 crashes when switching to another app while tts is running

### ISSUE THREAD

**Issue by ronnac** [wallabag/android-app#760]
# Issue details

### Duplicate?
Have you searched the issues of this repository if your issue is already known? yes

### Actual behaviour
- Wallabag 2.1.0 crashes when switching to another app while tts is running. Error message:

### Expected behaviour
- no crash

# Steps to reproduce the issue
1. Open any article in Wallabag Android 
2. Press the play button 
3. Press the "recent applications" button

# Environment details
- **wallabag app version**: 2.1.0
- **wallabag app installation source** (e.g. Gplay, F-Droid, manual): I tried both gplay and github 
- **Android OS version**: oreo 8.1.0
- **Android ROM** (e.g. stock, LineageOS, SlimRom,…): stock, Samsung Experience 9.5
- **Android hardware**: samsung J5  2018 SM-J530F
- **wallabag server version**: framabag
- **Do you have Two-Factor-Authentication enabled?**: don't know 

# Logs
## wallabag server
Please paste relevant wallabag server logs here (from file `<wallabag>/var/logs/prod.log`):
- bug not not related to wallabag server.

## Web server
Please paste relevant web server logs (e.g. from nginx, Apache, …) here:
- N/A
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here!

# Your experience with wallabag Android app
Have you had any luck using wallabag Android app before? (Sometimes we get tired of reading bug reports all day and a lil' positive end note does wonders)
- It works fine with the previous official release (no bug).

Logcat:

(I ran "logcat *.* | grep -i fr.gaulupeau.apps.Poche")

01-25 12:44:29.648  2992 12794 I ActivityManager: START u0 {act=android.intent.action.MAIN typ=null flg=0x10300000 cmp=ComponentInfo{fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.MainActivity}} from uid 10176
01-25 12:44:29.721  2992 12794 I ActivityManager: Start proc 5602:fr.gaulupeau.apps.InThePoche/u0a584 for activity fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.MainActivity
01-25 12:44:29.802  2992  3266 D GameManagerService: handleForegroundChange(). pkgName: fr.gaulupeau.apps.InThePoche, clsName: fr.gaulupeau.apps.Poche.ui.MainActivity,FgActivityName:fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.MainActivity
01-25 12:44:29.940  2992  3102 D MdnieScenarioControlService:  packageName : fr.gaulupeau.apps.InThePoche    className : fr.gaulupeau.apps.Poche.ui.MainActivity
01-25 12:44:30.107  5602  5602 I zygote  :   at void fr.gaulupeau.apps.Poche.ui.MainActivity.onCreate(android.os.Bundle) (MainActivity.java:112)
01-25 12:44:30.108  5602  5602 I zygote  :   at void fr.gaulupeau.apps.Poche.ui.MainActivity.onCreate(android.os.Bundle) (MainActivity.java:112)
01-25 12:44:30.109  5602  5602 I zygote  :   at void fr.gaulupeau.apps.Poche.ui.MainActivity.onCreate(android.os.Bundle) (MainActivity.java:112)
01-25 12:44:30.109  5602  5602 I zygote  :   at void fr.gaulupeau.apps.Poche.ui.MainActivity.onCreate(android.os.Bundle) (MainActivity.java:112)
01-25 12:44:30.110  5602  5602 I zygote  :   at void fr.gaulupeau.apps.Poche.ui.MainActivity.onCreate(android.os.Bundle) (MainActivity.java:112)
01-25 12:44:30.110  5602  5602 I zygote  :   at void fr.gaulupeau.apps.Poche.ui.MainActivity.onCreate(android.os.Bundle) (MainActivity.java:112)
01-25 12:44:30.549  2638  2638 I SurfaceFlinger: id=6002 createSurf (720x1280),1 flag=404, fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.MainActivity[5602]#0
01-25 12:44:31.046  2992  3552 D WindowManager: finishDrawingWindow: Window{d34691c u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.MainActivity} mDrawState=DRAW_PENDING
01-25 12:44:31.065  2992  3018 D PersonaManagerService: notifyActivityDrawn:u0:fr.gaulupeau.apps.Poche.ui.MainActivity
01-25 12:44:31.069  2992  3018 I ActivityManager: Displayed fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.MainActivity: +1s365ms
01-25 12:44:31.083  2638  2638 D SurfaceFlinger:        HWC | e7466b40 | 0000 | 0020 | 00 | 0100 | RGBA_8888   |    0.0,    0.0,  720.0, 1280.0 |    0,    0,  720, 1280 | fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.MainActivity[5602]#0
01-25 12:44:31.093  2992  3552 D WindowManager: finishDrawingWindow: Window{d34691c u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.MainActivity} mDrawState=HAS_DRAWN
01-25 12:44:31.770  5602  5629 I zygote  : Deoptimizing fr.gaulupeau.apps.Poche.data.dao.entities.Article fr.gaulupeau.apps.Poche.data.dao.ArticleDao.readEntity(android.database.Cursor, int) due to JIT inline cache
01-25 12:44:38.323  2992  6257 I ActivityManager: START u0 {act=null typ=null flg=0x0 cmp=ComponentInfo{fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ReadArticleActivity}} from uid 10584
01-25 12:44:38.353  2992  3266 D GameManagerService: handleForegroundChange(). pkgName: fr.gaulupeau.apps.InThePoche, clsName: fr.gaulupeau.apps.Poche.ui.ReadArticleActivity,FgActivityName:fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ReadArticleActivity
01-25 12:44:39.123  2638  2638 I SurfaceFlinger: id=6003 createSurf (720x1280),1 flag=404, fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ReadArticleActivity[5602]#0
01-25 12:44:39.309  2992  3102 D MdnieScenarioControlService:  packageName : fr.gaulupeau.apps.InThePoche    className : fr.gaulupeau.apps.Poche.ui.ReadArticleActivity
01-25 12:44:39.334  2992  3266 D GameManagerService: handleForegroundChange(). pkgName: fr.gaulupeau.apps.InThePoche, clsName: fr.gaulupeau.apps.Poche.ui.ReadArticleActivity,FgActivityName:fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ReadArticleActivity
01-25 12:44:39.442  2992 12794 D WindowManager: finishDrawingWindow: Window{bdeb25b u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ReadArticleActivity} mDrawState=DRAW_PENDING
01-25 12:44:39.473  2638  2638 D SurfaceFlinger:        HWC | e7467740 | 0000 | 0020 | 00 | 0100 | RGBA_8888   |    0.0,    0.0,  720.0, 1280.0 |    0,    0,  720, 1280 | fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ReadArticleActivity[5602]#0
01-25 12:44:39.495  2992  3018 D PersonaManagerService: notifyActivityDrawn:u0:fr.gaulupeau.apps.Poche.ui.ReadArticleActivity
01-25 12:44:39.551  2992  3552 D WindowManager: finishDrawingWindow: Window{bdeb25b u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ReadArticleActivity} mDrawState=HAS_DRAWN
01-25 12:44:39.640  2992  3552 E WindowManager: win=Window{d34691c u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.MainActivity} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=false win.mRemoveOnExit=false win.mViewVisibility=8, caller=com.android.server.wm.WindowManagerService.tryStartExitingAnimation:2851 com.android.server.wm.WindowManagerService.relayoutWindow:2590 com.android.server.wm.Session.relayout:267 android.view.IWindowSession$Stub.onTransact:288 com.android.server.wm.Session.onTransact:191 
01-25 12:44:39.640  2992  3552 I WindowManager: Destroying surface #fb19e6c: Surface(name=fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.MainActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2617 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:1026 com.android.server.wm.WindowState.destroyOrSaveSurfaceUnchecked:3821 com.android.server.wm.WindowState.destroySurface:3767 com.android.server.wm.WindowManagerService.tryStartExitingAnimation:2851 com.android.server.wm.WindowManagerService.relayoutWindow:2590 com.android.server.wm.Session.relayout:267 android.view.IWindowSession$Stub.onTransact:288 
01-25 12:44:39.640  2638  2649 I SurfaceFlinger: id=6002 Removed fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.MainActivity[5602]#0 (3/9)
01-25 12:44:39.640  2638  2649 I SurfaceFlinger: id=6002 Removed fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.MainActivity[5602]#0 (-2/9)
01-25 12:44:39.654  2638  2638 I Layer   : id=6002 onRemoved fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.MainActivity[5602]#0 
01-25 12:44:39.790  2992  3102 D MdnieScenarioControlService:  packageName : fr.gaulupeau.apps.InThePoche    className : fr.gaulupeau.apps.Poche.ui.ReadArticleActivity
01-25 12:44:40.706  2992 12794 I MediaFocusControl: requestAudioFocus() from uid/pid 10584/5602 clientId=android.media.AudioManager$68f82b0fr.gaulupeau.apps.Poche.tts.TtsService$90c7529 callingPack=fr.gaulupeau.apps.InThePoche req=1 flags=0x0 sdk=28
01-25 12:44:42.040  2992 12794 W ActivityManager:   Force finishing activity fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ReadArticleActivity
01-25 12:44:42.132  2638  2638 D SurfaceFlinger:       GLES | e7467800 | 0000 | 0020 | 00 | 0100 | RGBA_8888   |    0.0,   47.0,  720.0,  515.0 |   49,  876,  671, 1280 | fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ReadArticleActivity[5602]#0
01-25 12:44:42.166  2638  2638 D SurfaceFlinger:       GLES | e7467800 | 0000 | 0020 | 00 | 0100 | RGBA_8888   |    0.0,   47.0,  720.0,  515.0 |   49,  876,  671, 1280 | fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ReadArticleActivity[5602]#0
01-25 12:44:42.226  2992  3061 E WindowManager: win=Window{bdeb25b u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ReadArticleActivity EXITING} destroySurfaces: appStopped=true win.mWindowRemovalAllowed=false win.mRemoveOnExit=false win.mViewVisibility=4, caller=com.android.server.wm.AppWindowToken.destroySurfaces:748 com.android.server.wm.AppWindowToken.destroySurfaces:732 com.android.server.wm.WindowState.onExitAnimationDone:5523 com.android.server.wm.AppWindowAnimator.stepAnimationLocked:517 com.android.server.wm.AppWindowToken.stepAppWindowsAnimation:1745 
01-25 12:44:42.227  2992  3061 I WindowManager: Destroying surface #40459fb: Surface(name=fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ReadArticleActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2617 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:1026 com.android.server.wm.WindowState.destroyOrSaveSurfaceUnchecked:3821 com.android.server.wm.WindowState.destroySurface:3767 com.android.server.wm.AppWindowToken.destroySurfaces:748 com.android.server.wm.AppWindowToken.destroySurfaces:732 com.android.server.wm.WindowState.onExitAnimationDone:5523 com.android.server.wm.AppWindowAnimator.stepAnimationLocked:517 
01-25 12:44:42.227  2638  2649 I SurfaceFlinger: id=6003 Removed fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ReadArticleActivity[5602]#0 (4/11)
01-25 12:44:42.229  2638  2638 I Layer   : id=6003 onRemoved fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ReadArticleActivity[5602]#0 
01-25 12:44:42.229  2638  2649 I SurfaceFlinger: id=6003 Removed fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ReadArticleActivity[5602]#0 (-2/11)
01-25 12:44:44.653  2992 12794 W ActivityManager:   Force finishing activity fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ReadArticleActivity
01-25 12:44:44.688  2992 12794 W ActivityManager:   Force finishing activity fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.MainActivity

**Comment by tyndare** [comment]
I'll try to look for what could be wrong, but I haven't received any feedback on my previous pull request for tts fix: https://github.com/wallabag/android-app/pull/741

**Comment by tyndare** [comment]
I made a test on android 8.1.0 simulator and integrating the pull request https://github.com/wallabag/android-app/pull/741 seems to correct this bug.

**Comment by ronnac** [comment]
I can't compile myself, but if you can provide me with an apk that includes the pull request #741 then I can test it on my phone if that's useful.

**Comment by tcitworld** [comment]
@ronnac Here's a link to a debug signed APK (you should be able to install it alongside the release one): https://framadrop.org/r/lURlsRQu4b#+VdPzgVEnq53A+Q8BdKeroW0XT38KHxmEhkESUVqLMQ=

**Comment by ronnac** [comment]
Indeed, the bug is resolved with this apk. I will use it some more and let you know if any other problems come up.

**Comment by tcitworld** [comment]
It only contains the #741 changes on top of the latest release.

**Comment by ronnac** [comment]
I've been using this version for several days without problems.

**Comment by Strubbl** [comment]
This issue is fixed with PR #741
