### ISSUE TITLE
More black theme issues

### ISSUE THREAD

**Issue by BNolet** [wallabag/android-app#773]
# Issue details
Inconsistency in black theme for Android app

### Duplicate?
Have you searched the issues of this repository if your issue is already known? yes

### Actual behaviour
Everything should be white on black

### Expected behaviour
Not everything is white on black

* Three-dots menu in Article list view

# Steps to reproduce the issue
1. Have App v2.2.0
2. Go to list view and open three-dot menu
3. Go to article view and head to complete bottom

# Environment details
- **wallabag app version**: 2.2.0
- **wallabag app installation source** (e.g. Gplay, F-Droid, manual): FDroid
- **Android OS version**: 8.0
- **Android ROM** (e.g. stock, LineageOS, SlimRom,…): stock
- **Android hardware**: Moto Z^2 Play
- **wallabag server version**: 2.3.7
- **Do you have Two-Factor-Authentication enabled?**: no

# Logs
## wallabag server
None relevant

## Web server
None relevant

# Your experience with wallabag Android app
Have you had any luck using wallabag Android app before? (Sometimes we get tired of reading bug reports all day and a lil' positive end note does wonders)

Loving the app, and seeing the progress being made :)

**Comment by BNolet** [comment]
Screenshots: 

Three-dots menu:
![image](https://user-images.githubusercontent.com/10198484/54089869-2c34b680-4344-11e9-99f8-c0b276201223.png)

Mark as read area:
![image](https://user-images.githubusercontent.com/10198484/54089861-1d4e0400-4344-11e9-9582-26fb59278da8.png)

**Comment by Strubbl** [comment]
hello @NWuensche , since you helped fixing an issue with the black theme, maybe you can help here, too?

**Comment by BNolet** [comment]
Heh the weird part is that this fix created these problems ;) 

Such is life 🤷‍♂️

**Comment by Strubbl** [comment]
I can reproduce the first screenshot, but not the second one:

![nsmail](https://user-images.githubusercontent.com/97055/54312794-16d7ba80-45d8-11e9-9d8f-24e60295a77b.jpg)

The only difference between our setups is the Android version. I currently run Android 9.

**Comment by BNolet** [comment]
Seems like the second one is fixed with a data clear. I'll remove it from the original post

**Comment by ngosang** [comment]
I can confirm the "white menu" problem was caused by #730
Please, we need a fix, the menu is not usable because it's not readable.

**Comment by ngosang** [comment]
After the last release this is a mess. The menu is unusable (white text in white background). I also found that the favorite (star) is not visible in the list (back over black background).

**Comment by NWuensche** [comment]
Sorry that I haven't done anything about this, I will try to fix this in the next couple of days.
