### ISSUE TITLE
Support TLSv1.3

### ISSUE THREAD

**Issue by Patricol** [wallabag/android-app#778]
# Issue details

### Duplicate?
Have you searched the issues of this repository if your issue is already known? **yes**

### Actual behaviour
- Handshake fails when connecting to a server that only allows using TLSv1.3.
- Handshake succeeds when that server is configured to also allow TLSv1.2.
  - (no other changes)

### Expected behaviour
- Handshake should not fail when only TLSv1.3 is allowed.

# Steps to reproduce the issue
1. Early-adopt TLSv1.3 a little too eagerly
2. Settings -> Connection -> Autofill
3. Observe popup

# Environment details
- **wallabag app version**: 2.2.0
- **wallabag app installation source** (e.g. Gplay, F-Droid, manual): Gplay
- **Android OS version**: 8.1
- **Android ROM** (e.g. stock, LineageOS, SlimRom,…): Stock
- **Android hardware**: Nexus 5X
- **wallabag server version**: 2.3.7
- **Do you have Two-Factor-Authentication enabled?**: no

# Your experience with wallabag Android app
While I haven't used the android app much yet; wallabag has been a fantastic boon for me; and an integral part of a month-long bookmark assimilating project I undertook a while ago. Thank you so much for supporting it and improving it!

**Comment by di72nn** [comment]
Thanks for the report!
TLS 1.3 is only supported by [Android Q](https://developer.android.com/preview/features#tls-1.3).
(In theory, some [GMS tricks](https://developer.android.com/training/articles/security-gms-provider.html) may help in the future, but these are probably proprietary).

**Comment by Patricol** [comment]
Thank you for the information; I didn't realize that the other applications I use that work with TLSv1.3 weren't relying on the standard libraries.

**Comment by di72nn** [comment]
Oh, can you name some of these applications that support TLS 1.3 so we can look into it?

**Comment by Patricol** [comment]
Upon more direct inspection, it seems that most apps besides Google Chrome appear to be working via webviews.

Setting up direct connections in [ControlR](https://play.google.com/store/apps/details?id=io.jbrodriguez.controlr), [UniFi](https://play.google.com/store/apps/details?id=com.ubnt.easyunifi), and [Tiny Tiny RSS](https://play.google.com/store/apps/details?id=org.fox.ttrss) fails without TLSv1.2 support.

Google Chrome does still work though.

**Comment by di72nn** [comment]
I didn't look into it, but web browsers may as well have their own crypto implementations. Chrome and Firefox for Android are [reported to support TLS 1.3](https://caniuse.com/#feat=tls1-3) since December. I guess that means no TLS 1.3 for simple apps anytime soon.
Thanks for the details.
