### ISSUE TITLE
Ability to use without a server

### ISSUE THREAD

**Issue by bquistorff** [wallabag/android-app#779]
# Issue details
If one does not care about syncing across multiple devices then it would be very convenient for the user to be able to use the android app in completely local (severless) way. Adding links would download and convert pages and then store them locally.

### Duplicate?
Have you searched the issues of this repository if your issue is already known? yes

**Comment by Strubbl** [comment]
This sounds like a nice idea. But it would be out of the scope of this project. The app would have to reimplement everything the wallabag server does.
If you start a such project, which does that, please let us know.
