### ISSUE TITLE
Get error "301: Moved permanently" while synchronising to Framabag

### ISSUE THREAD

**Issue by etnadji** [wallabag/android-app#78]
Setting:

Wallabag url: http://framabag.org/u/USERNAME
User ID: 1
Token: (Token from Settings page, regenerated)

Leads to "301: Moved permanently" error pop-up.

**Comment by tcitworld** [comment]
Thanks. Can you access the URL http://framabag.org/u/USERNAME?feed&type=home&user_id=1&token=TOKEN in your browser?

**Comment by etnadji** [comment]
Yes.

**Comment by tcitworld** [comment]
Are you using some kind of proxy or something like that ?

**Comment by kevmeyer** [comment]
could you try to use https instead of http in the url?

**Comment by etnadji** [comment]
*Are you using some kind of proxy or something like that ?*
Not really. My FAI use a captive portal (pff).

*could you try to use https instead of http in the url?*
It seems that https://framabag.org/u/USER/ **works**!

**Comment by tcitworld** [comment]
Yeah so framabag enforces the secure connexion but the app doesn't follows the redirection.

**Comment by di72nn** [comment]
Obsolete (partially fixed; discussed in other issues).
