### ISSUE TITLE
app.ERROR: Authentication failure for user

### ISSUE THREAD

**Issue by Pitstopper** [wallabag/android-app#789]
### Issue details
Hi! I noticed strange things in the prod.log. When I add an article via a mobile browser or with another mobile application to Wallabag, I see the following in the logs:
```
# #[2018-01-25 12:51:04] request.INFO: Matched route "api_get_version". {"route":"api_get_version","route_parameters":{"_controller":"Wallabag\\ApiBundle\\Controller\\UserRestController::getVersionAction","_format":"json","_route":"api_get_version"},"request_uri":"https://my_hostname/api/version.json","method":"GET"} []
//$

[2018-01-25 12:51:04] app.ERROR: Authentication failure for user "", from IP "ip_address", with UA: "okhttp/3.8.1".

```
When I do this from the desktop - everything is ok, no log entries. 
I use Android 7.1.2 and the latest mobile Wallabag app.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.1 - 2.3.8
* How did you install wallabag? Via `git clone` or by downloading the package? - git clone
* Last wallabag version that did not exhibit the issue (if applicable): 2.3.0
* php version: PHP 7.3.5
* OS: Debian 9
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite

**Comment by di72nn** [comment]
Hey, thanks for the report!

I added a clarification in wallabag/wallabag#3575.

I have the impression that this is the correct behavior, but it should be looked into if the error messages are too frequent. How often does it happen? Does the error message always follow the `"api_get_version"` access?
You're not using any other API client (wallabagger extension or iOS app) at the moment?

**Comment by Pitstopper** [comment]
Hey. These log entries do not always appear. The only pattern that I discovered is that this happens if you do not use the mobile application for a long time, and then add an article to it or simply update the list of articles. Errors resemble each other, only the date changes. I use only the app Wallabag for android.

**Comment by di72nn** [comment]
Ok then, seems like a legitimate behavior. The logging can be improved as the server issue.
