### ISSUE TITLE
f-droid FAQ link is broken

### ISSUE THREAD

**Issue by Strubbl** [wallabag/android-app#796]
reported in the chat

> 07:07 <doctor-owl> Just wanted to let you know the link to the FAQ on FDroid is broken. Sends me to a blank page that says "whoops, looks like this page doesn't exist." This is the link in question: https://www.wallabag.org/frequently-asked-questions

currently the fdroid text is: 

> Optionally you can find a hosting
> service in the [https://www.wallabag.org/frequently-asked-questions/ FAQ].

https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/fr.gaulupeau.apps.InThePoche.txt

I guess the hosted service wallabag.it should be linked here? i do not know if it is allowed in f-droid descriptions?

**Comment by di72nn** [comment]
Fixed.
