### ISSUE TITLE
Android app: outdated interface

### ISSUE THREAD

**Issue by nicosomb** [wallabag/android-app#8]
The app looks like it was made for Android 2.x – maybe better use the Holo stuff to make it look current. ;)

See https://github.com/wallabag/wallabag/issues/403

**Comment by tcitworld** [comment]
Still work to do. About the compatibility with android<3.0, it seems people don't care any more, is that right ? https://framadate.org/D52nxggEifrZ14ae

**Comment by di72nn** [comment]
Outdated.
