### ISSUE TITLE
Error doing handshake TLSv1.3

### ISSUE THREAD

**Issue by techexo** [wallabag/android-app#800]
Hi everyone,

Sorry to not make a very detailed issue ticket, but I'm doing it from my mobile phone. 

After upgrading my nginx configuration on my server to use by default TLSv1.3, it seems that the wallabag app is no longer able to use https connection to the server, with the following message:

`javax.net.SSLHandshakeException: Handshake failed`

There might be a dependency to upgrade to support TLSv1.3?

# Environment details
- **wallabag app version**: 2.2.2 (212)
- **wallabag app installation source** (e.g. Gplay, F-Droid, manual): gplay
- **Android OS version**: 9
- **Android ROM** (e.g. stock, LineageOS, SlimRom,…): lineageos
- **Android hardware**: oneplus3t
- **wallabag server version**: 2.3.8
- **Do you have Two-Factor-Authentication enabled?**: no

## Web server

TLS configuration from nginx (inspired by https://cipherli.st/):
```
ssl_protocols TLSv1.3;
ssl_ciphers "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256";
ssl_prefer_server_ciphers on;
ssl_session_cache shared:SSL:10m;
ssl_dhparam /etc/ssl/private/dh4096.pem;
```

**Comment by tcitworld** [comment]
Doesn't Android 1.3 requires Android Q (10)?

**Comment by techexo** [comment]
I think TLSv1.3 will be activated by default on Android Q. Does that necessarily mean it can't be used on Android P?

**Comment by techexo** [comment]
It seems indeed that Android Q will be needed for TLSv1.3, and I didn't activate fallback on v1.2 on nginx. Upgrade of okhttp (which I reckon is a dependency of the app?) should take care of this issue.

Feel free to close the issue or wait to upgrade. 😊

**Comment by di72nn** [comment]
I need to take a closer look, but I think we should include [Conscrypt](https://github.com/square/okhttp/blob/master/CHANGELOG.md#version-3100) to support more protocols and cipher suites independently from Android. It would be a good idea (or ever a requirement) to also remove "custom SSL options".

**Comment by tcitworld** [comment]
Conscrypt sounds nice indeed.

**Comment by techexo** [comment]
I'm not competent to help you more, but I'm sure I'm leaving this issue in good hands. Don't hesitate to ping me if more information is required 🙂
