### ISSUE TITLE
Video support

### ISSUE THREAD

**Issue by Poorchop** [wallabag/android-app#81]
First of all, thanks for this application.

I saved a YouTube video and I can watch it wallabag via the web browser, but when I try to watch it via the Android application, I get an "Unable to execute Javascript" error. It would be really nice if the application supported inline video so that I don't have to open the web browser to view them.

**Comment by tcitworld** [comment]
Note for devs : 
I thought enabling javascript in the [ReadArticle.java](https://github.com/wallabag/android-app/blob/master/app/src/main/java/fr/gaulupeau/apps/Poche/ReadArticle.java)
```
webViewContent.getSettings().setJavaScriptEnabled(true);
```
file would do it, but it seems [it's a little harder though](http://stackoverflow.com/questions/17706580/youtube-video-not-playing-in-webview).

**Comment by tcitworld** [comment]
Would try to test it myself, but I don't have a decent computer to compile anything at the moment. ;)

**Comment by tcitworld** [comment]
Now available in beta builds.
