### ISSUE TITLE
Error performing complete update (master)

### ISSUE THREAD

**Issue by ngosang** [wallabag/android-app#818]
# Issue details
I built the apk from master (to test #811) and when I perform a complete update in the app. I see this error.

![Screenshot_2019-08-25-23-09-04-683_fr gaulupeau apps InThePoche debug](https://user-images.githubusercontent.com/10577978/63655881-d33fca00-c78d-11e9-8f35-d2e58ef209e4.png)

# Environment details
- **wallabag app version**: 2.3.8
- **wallabag app installation source** Custom build fro master, include #811

**Comment by ngosang** [comment]
@tcitworld I think this is important, I can't use the app because I can't update. I'm going to a previous version by now. I will test again if you release some fix.

**Comment by di72nn** [comment]
That's a long shot, but can you run this on your server?
```SQL
select id, published_by from wallabag_entry where published_by like '%;a:%';
```

**Comment by ngosang** [comment]
bingo!

id = 629
url = https://www.newyorker.com/magazine/2016/02/29/a-new-generation-of-airships-is-born?mbid=rss
published_by = a:1:{i:0;a:1:{i:0;s:19:"Jeanne Marie Laskas";}}	

Btw, in wallabag web I see just Array
![image](https://user-images.githubusercontent.com/10577978/63709972-51f14180-c838-11e9-877a-a5e95c5786ef.png)

**Comment by Kdecherf** [comment]
Could be related to https://github.com/wallabag/wallabag/issues/3867

By the way, the `Array` does not show up anymore on current server master

**Comment by di72nn** [comment]
I guess the extraction was fixed.

To make the error searchable: `Error: com.squareup.moshi.JsonDataException: Expected a string but was BEGIN_ARRAY at path $._embedded.items[29].pubulished_by[0]`.

Thanks for the report, maybe it'll help someone else!

**Comment by ngosang** [comment]
@di72nn is fixed in wallabag app or in wallabag web?

**Comment by di72nn** [comment]
That just shouldn't happen. Refetch the article (on the server) and the problem should be gone.

**Comment by ngosang** [comment]
@di72nn how is that? I have my own server, if I don't update the server or something I get the same result, Array...

**Comment by di72nn** [comment]
The entry in question was fetched with older server version (in the early 2017), if you refetch it with 2.3.8, the field should update with the correct value.
