### ISSUE TITLE
Favorite and Archive icons are not visible with black theme (high contrast)

### ISSUE THREAD

**Issue by ngosang** [wallabag/android-app#819]
# Issue details
This problem is still present in master. I opened the same issue in the past but was closed #415 
Look at the favorite start in light and dark themes.
![imagen](https://user-images.githubusercontent.com/10577978/63655940-988a6180-c78e-11e9-91a4-914b795b24b2.png)
![imagen](https://user-images.githubusercontent.com/10577978/63655943-9cb67f00-c78e-11e9-8bde-fc6630d815bc.png)

# Environment details
    wallabag app version: 2.3.8
    wallabag app installation source Custom build from master

**Comment by Strubbl** [comment]
I can confirm this issue. even in dark theme the symbols are black although they should be white.
