### ISSUE TITLE
uncomplet note fails to sync 

### ISSUE THREAD

**Issue by foxmask** [wallabag/android-app#83]
after having importing note from pocket, so of them are not completly imported, so when i use the android app to finish to sync the notes i failed because of my proxy settings. As i'm using Tor (to say everything;) we cant sync note without dealing with proxy

**Comment by foxmask** [comment]
After shutting down tor i have the same behavior

**Comment by foxmask** [comment]
The app says "impossible de charger la page web a l'adresse file:///Android_asset?import" en tant que :
net::ERR_FILE_NOT_FOUND

**Comment by tcitworld** [comment]
It seems to be specific to how Tor handles connections. Will have to test that but Tor doesn't currently run on my phone (bug with CM nightly)

**Comment by foxmask** [comment]
I installed the app on nexus10, the behavior is the same. And the href juste contains "./?import" which to be the problem and not related to tor finally

**Comment by di72nn** [comment]
Reopen if it is still reproducible.
