### ISSUE TITLE
com.squareeup.moshi.JsonDataException after Factory Reset

### ISSUE THREAD

**Issue by bigretromike** [wallabag/android-app#836]
# Issue details
I can't sync with my self-hosted server, this error happens at begging of full performing full update
`Error: com.squareeup.moshi.JsonDataException: Expected an int but was NULL at path $._embedded.items[14].reading_time`

### Duplicate?
Have you searched the issues of this repository if your issue is already known? yes

### Actual behaviour
- Tell us what happens
Can't sync anything from server

### Expected behaviour
- Tell us what should happen
Able to sync from server

# Steps to reproduce the issue
1. factory reset
2. install wallabag on android
3. open wallabag, perform sync

# Environment details
- **wallabag app version**: 2.2.4
- **wallabag app installation source** (e.g. Gplay, F-Droid, manual): Gplay
- **Android OS version**: 7.0
- **Android ROM** (e.g. stock, LineageOS, SlimRom,…): stock
- **Android hardware**: 
- **wallabag server version**: 2.3.8
- **Do you have Two-Factor-Authentication enabled?**: no

# Logs
## wallabag server
Please paste relevant wallabag server logs here (from file `<wallabag>/var/logs/prod.log`):

## Web server
Please paste relevant web server logs (e.g. from nginx, Apache, …) here:

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here!

# Your experience with wallabag Android app
Have you had any luck using wallabag Android app before? (Sometimes we get tired of reading bug reports all day and a lil' positive end note does wonders)
It did work before factory reset

**Comment by di72nn** [comment]
Most likely it's a server-side issue: https://github.com/wallabag/android-app/issues/793#issuecomment-502748129
Try to run this query on your server DB:
```SQL
select * from wallabag_entry where reading_time is NULL;
```
If you find something, you can either refetch the problem articles or run something like this:
```SQL
update wallabag_entry set reading_time=0 where reading_time is NULL;
```

**Comment by bigretromike** [comment]
yeah, had 2 articles with `NULL` entry. both from 2017 year. strange.

But thanks a lot.
