### ISSUE TITLE
Can't call out the top bar in fullscreen mode?

### ISSUE THREAD

**Issue by klemperer** [wallabag/android-app#837]
Excuse me, but it seems that the top bar will not show in any ways while in fullscreen mode. It would be better to call out the top bar while reading, so that we can make the article archived or favorited.

Thanks.

**Comment by di72nn** [comment]
Hey!

Yeah, current implementation is not fully functional. There is a long standing issue about fullscreen mode: #114.

There's a chance #809 will do something about this situation.
Meanwhile you may continue the discussion in #114.
