### ISSUE TITLE
Be able to see (YouTube) Videos in Fullscreen

### ISSUE THREAD

**Issue by NWuensche** [wallabag/android-app#841]
I use Wallabag sometimes to save YouTube videos and to replay them later (e.g. https://www.youtube.com/watch?v=jNQXAC9IVRw ). I can replay them in Wallabag (of course with Internet ) , but the fullscreen button in the video bar is disabled.
It would be nice if we can make it possible to enable the fullscreen button for the video. 

I would like to work on this, but I don't really know where to start. I searched for `video` and `youtube` inside the project, but couldn't find anything relevant. I also thought about doing this in the `ReadArticleActivity`, but I don't really know where to do this there too. 
Maybe someone can help me with how a YouTube video is stored in Wallabag, which player is used to play the video and where I can change its video bar.

**Comment by di72nn** [comment]
It's just an embedded player in an `iframe`. If you run a debug build of the app you can see it in the logs:
```
D/ReadArticleActivity: getHtmlContent() htmlContent: Estimated reading time: &lt; 1 min<iframe id="video" width="480" height="270" src="https://www.youtube.com/embed/XYZ123?feature=oembed" frameborder="0" allowfullscreen="allowfullscreen">[embedded content]</iframe>
```
A quick search for `android webview youtube fullscreen` shows that that's a well-known problem. I haven't tried out any solution.

**Comment by NWuensche** [comment]
Thank you for the information!
