### ISSUE TITLE
syncOfflineQueue() IOException: unexpected end of stream on http://wallabag.example.de

### ISSUE THREAD

**Issue by Strubbl** [wallabag/android-app#856]
# Issue details

### Duplicate?
Have you searched the issues of this repository if your issue is already known? yes

### Actual behaviour
On opening the app the local changes do not get synced with the server. I get a generic error message notification.

### Expected behaviour
I want the local changes to be synced with the server without an error.

# Steps to reproduce the issue
1. add one article offline
1. get internet connection and let the it sync. the internet connection is so slow, that syncing offline changes is not yet finished
2. add another article offline
3. get messed up local changes

# Environment details
- **wallabag app version**: debug master branch commit 7ec239acecbeb0a2a0a8c49e3fb0aed905bd2eea
- **wallabag app installation source** (e.g. Gplay, F-Droid, manual): manual
- **Android OS version**: 9
- **Android ROM** (e.g. stock, LineageOS, SlimRom,…): stock
- **Android hardware**: Samsung S9
- **wallabag server version**: 2.3.8
- **Do you have Two-Factor-Authentication enabled?**: no

# Logs
## Logcat from the start/resume to the error:
https://gist.github.com/Strubbl/9cd4023546a21485e7e41b22a127c129

So the error starts near the end of the log: https://gist.github.com/Strubbl/9cd4023546a21485e7e41b22a127c129#file-java-io-ioexception-unexpected-end-of-stream-on-log-L506

## wallabag server
Please paste relevant wallabag server logs here (from file `<wallabag>/var/logs/prod.log`):

```
[2019-10-26 16:16:07] request.INFO: Matched route "api_post_entries". {"route":"api_post_entries","route_parameters":{"_controller":"Wallabag\\ApiBundle\\Controller\\EntryRestController::postEntriesAction","_format":"json","_route":"api_post_entries"},"r
equest_uri":"https://wallabag.example.de/api/entries.json","method":"POST"} []
[2019-10-26 16:16:08] app.ERROR: Authentication failure for user "", from IP "2a02:820d:1500:113d::::", with UA: "okhttp/4.2.2". [] []
```

**Comment by Strubbl** [comment]
This is crazy. I have moved the database to the external storage and pulled it from there to my PC. Then i opened it with sqlitebrowser and the table QUEUE_ITEM is empty - not a single line. Where does this error come from?

Besides /storage/21DC-539E/Android/data/fr.gaulupeau.apps.InThePoche.debug/files/wallabag
i have two additional files in the folder: wallabag-shm and wallabag-wal. Is any of that files relevant for the offline queue?

**Comment by di72nn** [comment]
I'm not sure I understand the problem correctly. Specifically, this part:
> 4. get messed up local changes

I'll share what I think is going on, so you can correct me.
1. You add an article (or make any change) while being offline.
1. When you get online the app tries to sync and shows an error because of the IOE.
AFAIK, this is completely normal and does not cause any data loss (except maybe duplicate requests to the server).
*This should be suppressed as with other IOExceptions in `IntentServiceBase.processException(...)`.*
1. You make more offline changes.
1. Eventually the app manages to sync up.
As a result, the offline queue is empty. Or are you still getting the same error after inspecting the DB?

// `wallabag-shm` and `wallabag-wal` are SQLite's shared-memory and write-ahead log files. Generally, nothing to see there.

**Comment by Strubbl** [comment]
The error comes from the link i want to add, because the link contains a semi-colon (";").

I remember i already opened an issue for that: https://github.com/wallabag/wallabag/issues/4117

**Comment by Strubbl** [comment]
I pushed some changes to analyze this issue to a new branch: https://github.com/Strubbl/wallabag-android-app/tree/analyze-issue-856
I would suppose to merge this debug output to master if that's okay?

**Comment by di72nn** [comment]
> I would suggest to merge this debugging helper lines to master if that's okay?

Yeah, seems ok.

> I still get the error although the db was empty.

Something should be in the DB if the offline changes survive app restart. Maybe try extracting the DB again. Also, if you have root, you can open it via `adb` in `/data/...`.

BTW, double check that you didn't mix up debug and release builds if you have both installed.

**Comment by di72nn** [comment]
Actually, maybe you do need these `wallabag-shm` and `wallabag-wal` files. I usually just do `sqlite3 wallabag` in the directory with all these files, maybe in that case all the files are taken into account.

**Comment by Strubbl** [comment]
Yes, that helped. I also copied the shm and wal file and now i see both queue entries. 

So we need to wait for release 2.4, in which the wallabag server issue is closed and finally this issue can be closed.

Despite the error in the server software, does it make sense to catch such exceptions and proceed with working on the remaining queue items? 
This would leave only the queue item causing the error in the queue. It might cause race conditions when there are more actions on a single article, where one of the first action fails and the other may not.

**Comment by di72nn** [comment]
So the `IOException` + `EOFException` had nothing to do with network, but with the server not being able to produce an answer?

> does it make sense to catch such exceptions and proceed with working on the remaining queue items

The `ADD_LINK` items *can* be skipped in case of errors, but this would make it significantly harder to detect such errors. So far my answer to that always was "fix the server".

**Comment by di72nn** [comment]
The only question here is whether to suppress
`java.io.IOException: unexpected end of stream on https://wallabag.example.de/... Caused by: java.io.EOFException: \n not found: limit=0 content=…`.
The answer is unclear, so leaving it as it is for the time being.

**Comment by Strubbl** [comment]
just for reference, i opened an issue at wallabag server for this: https://github.com/wallabag/wallabag/issues/4117
