### ISSUE TITLE
flicker during scroll in e-ink mode

### ISSUE THREAD

**Issue by anarcat** [wallabag/android-app#862]
# Issue details

There are too many animations in the Android app, particularly when scrolling pages, which leaves artifacts on the screen and generally makes the app harder to use. I suspect it also uses more battery than it should that way.

### Actual behaviour

When "scrolling" (tapping on the right side) an article in "e-ink" mode, the page correctly scrolls by the specified amount (95% by default), but it does so with an animation. in e-ink based readers, this creates some flicker and leaves artefacts on the screen after the process is over.

### Expected behaviour

There shouldn't be an "animation": the page shouldn't "scroll up", it should just "display the next page", so to speak.

This also affects other parts of the application, for example the left "hamburger menu" triggers animations as well, which provokes significant flickering. It's pretty confusion for people not used to dealing with those problems, and new users might think this is a problem in the software or hardware.

To be fair, maybe it's also the OS's job to disable all such animations at the Android level, but I haven't found out how to do so, and this hardware doesn't do it on its own. So I'm wondering if there's a toggle that could be added to the app instead.

# Steps to reproduce the issue
1. Install and configure Wallabag on an Android e-reader
2. Go into the left "Hamburger menu", choose "Settings", then "UI", "App theme" and set it to "For e-ink displays"
3. Load an article
4. scroll to the next page
5. observe how the page slowly scrolls up, flashing multiple times

# Environment details
- **wallabag app version**: 2.2.4 (214)
- **wallabag app installation source** F-Droid
- **Android OS version**: 6
- **Android ROM**: ? 
- **Android hardware**: Onyx Note Pro
- **wallabag server version**: ?
- **Do you have Two-Factor-Authentication enabled?**: no

# Logs

N/A

# Your experience with wallabag Android app

It's really awesome to *have* a e-ink theme at all, I gotta say. :) The "tap to scroll" feature is especially important, and otherwise works well enough. Thanks for your work!

**Comment by anarcat** [comment]
oh and i forgot to mention i'd be happy to provide videos of the behavior if the above description is insufficient. i'm also available for testing alpha/beta packages if that's necessary.

**Comment by di72nn** [comment]
Have you tried unchecking the "Use smooth scrolling" option in the UI settings? It disables smooth scrolling for "tap-to-scroll" and volume buttons scrolling.
I would think the manufacturer should have preconfigured this already, but if you have "Developer settings" and `adb` access, you might check the "animation scale" settings (mentioned [here](https://stackoverflow.com/a/43861179) among other things).

On related note, we actually have the e-ink theme [enabled by default for some Nook devices](https://github.com/wallabag/android-app/blob/d3b11d90179b20870ad4d43268139ebbac445ee8/app/src/main/java/fr/gaulupeau/apps/Poche/data/Settings.java#L131). I think we should also disable smooth scrolling and maybe enable tap-to-scroll by default. And detect more e-ink devices.

**Comment by anarcat** [comment]
> Have you tried unchecking the "Use smooth scrolling" option in the UI settings? It disables smooth scrolling for "tap-to-scroll" and volume buttons scrolling.

I have *not* tried that! It does seem to fix the problem here!! So I guess that's it, just either a documentation or auto-detection issue? Maybe that setting should flip when I pick the e-ink theme?

>  I would think the manufacturer should have preconfigured this already, but if you have "Developer settings" and adb access, you might check the "animation scale" settings (mentioned here among other things).

Those three settings are greyed out and marked as "off" so I am guessing they *are* turned off... 

> On related note, we actually have the e-ink theme enabled by default for some Nook devices. I think we should also disable smooth scrolling and maybe enable tap-to-scroll by default. And detect more e-ink devices.

Agreed. For what it's worth, I do have the e-ink theme enabled here, but it wasn't detected by default...

Feel free to close this if you don't believe there's anything else...

**Comment by di72nn** [comment]
Added more points to the original e-ink issue.
