### ISSUE TITLE
"Unknown Error" during sync

### ISSUE THREAD

**Issue by markwaters** [wallabag/android-app#887]
# Issue details
I had been using version 2.3.0 for a while without a problem but then started seeing an error notification saying "Unknown Error"
I first cleared all the app data , then entered my credentials and tried to sync from scratch - same error.
Uninstalled app , switched from f-droid version to play store version - same error , I cannot add new articles and cannot see any previously saved articles as the Sync never finishes.
Switched back to f-droid , using previous 2.2.4 version - no error , working perfectly.

### Duplicate?
Have you searched the issues of this repository if your issue is already known? yes
### Actual behaviour
Seeing "Unknown Error" during sync

### Expected behaviour
Successful Sync

# Steps to reproduce the issue
1. Install wallabag android app 2.3.0
2. Sync - fail.

# Environment details
- **wallabag app version**: 2.3.0
- **wallabag app installation source** (e.g. Gplay, F-Droid, manual): F-Droid and GooglePlay
- **Android OS version**: 9
- **Android ROM** (e.g. stock, LineageOS, SlimRom,…):  stock
- **Android hardware**: Samsung SM-T510 Tablet
- **wallabag server version**: 2.3.8
- **Do you have Two-Factor-Authentication enabled?**: no

# Logs
## wallabag server
Please paste relevant wallabag server logs here (from file `<wallabag>/var/logs/prod.log`):

## Web server
Please paste relevant web server logs (e.g. from nginx, Apache, …) here:

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here!

# Your experience with wallabag Android app
Have you had any luck using wallabag Android app before? (Sometimes we get tired of reading bug reports all day and a lil' positive end note does wonders)

**Comment by di72nn** [comment]
Can you check whether the error notification is expandable? If it is, it may contain some extra information that would help.

Version 2.3.0 adds support for the article `authors` field that may cause an error if the server returns incorrect data (there's a precedent). Can you check the articles which you added about the time the error started to occur? If the `authors` field looks incorrect, you may try to temporarily remove such an article. Also if the problem is caused by the authors field, it is most likely that the error notification is expandable.

If this doesn't help, we're gonna need logcat output for further debugging.

**Comment by markwaters** [comment]
Hi @di72nn ,
I have upgraded back to version 2.3.0 via f-droid.
At this point I could do a manual sync without a problem.
Next I nuked the database via the settings page and started a new sync.
The sync got about 60% through before stopping with the same "Unknown Error" notification which i was able to expand , it shows this :-
Error: com.squareup.moshi.JsonDataException: Expected a string but was BEGIN_ARRAY at path $._embedded.items[28].published_by[0]

**Comment by di72nn** [comment]
Same as #818. Try to run an SQL query from [this comment](https://github.com/wallabag/android-app/issues/818#issuecomment-524797208), it should show you the offending article. You can try to refetch it (via the web UI). If refetching doesn't help, you can just update `published_by` (setting to `null` should probably work - I don't remember the default value).

If refetching doesn't help, please file a "site config" issue [for the server](https://github.com/wallabag/wallabag/issues) or at least post the problem URL here.

**Comment by markwaters** [comment]
Awesome , thanks @di72nn
I ran the SQL query , it showed seven entries.
I searched and found each one in the web interface and re-fetched the content.
This changed the author name from 'Array' to the authors name.
One of the posts I cannot find but it doesn't seem to be causing the issue.
I can now sync correctly with the latest 2.3.0 version.
Thank you!
