### ISSUE TITLE
Content is null on some articles

### ISSUE THREAD

**Issue by Strubbl** [wallabag/android-app#895]
# Issue details

### Duplicate?
Have you searched the issues of this repository if your issue is already known? yes

### Actual behaviour
- Article view displays "null" as content (title, reading time, preview image is fine)
- Articles are fine at wallabag web

### Expected behaviour
- Article view shall display content instead of "null"

# Steps to reproduce the issue
1. Go through article list and open articles
2. Some show the content
3. some don't

# Environment details
- **wallabag app version**: current git master HEAD (9a80bdf349b231cf73711a3b4e6bb773eb3d19ec)
- **wallabag app installation source** (e.g. Gplay, F-Droid, manual): android studio compiled
- **Android OS version**: 9
- **Android ROM** (e.g. stock, LineageOS, SlimRom,…): stock
- **Android hardware**: samsung s9
- **wallabag server version**: 2.3.8
- **Do you have Two-Factor-Authentication enabled?**: no

# Logs
## adb
`2020-01-05 19:57:20.318 2123-2123/fr.gaulupeau.apps.InThePoche.debug D/ReadArticleActivity: getHtmlContent() htmlContent: Geschätzte Lesezeit: 1 min<br><img src="https://wallabag.linux4tw.de/assets/images/asdf.jpeg"/>null`

## wallabag server
not relevant i guess

## Web server
not relevant i guess

**Comment by Strubbl** [comment]
I have not wiped the db yet to see if that helps. Will try that later.

**Comment by di72nn** [comment]
I take it you upgraded from a previous version?
Is the content `null` for particular articles or does it just randomly show `null` from time to time (like on the same article across restarts)?

**Comment by di72nn** [comment]
Also, is there a chance you had a "dirty" upgrade over some other non-master build? I didn't give it much thought, but there is a possibility of DB migration incompatibility.

**Comment by Strubbl** [comment]
null is always shown for the same articles. 


Yes, dirty uprade might be possible. I switched back and forth with branches etc. I cannot reproduce the branch switching anymore. 

I tried the "full upgrade", which recovered the article content of the articles which were affected. --> closing
