### ISSUE TITLE
App crashes when during start

### ISSUE THREAD

**Issue by gerroon** [wallabag/android-app#896]
Hi

I am moving the bug entry from #890 to here. 

Environment details

    wallabag app version:
    2.3.0

    wallabag app installation source (e.g. Gplay, F-Droid, manual):
    Fdroid

    Android OS version:
    LineageOS 14.1

    Android ROM (e.g. stock, LineageOS, SlimRom,…):
    LineageOS 14.1

    Android hardware:
    Samsung

    wallabag server version:
    Version: 2.3.8

    Do you have Two-Factor-Authentication enabled?: yes/no
    No

The app keeps crashing afterward a full sync, even when it is a fresh new setup. I was able to load all the articles and browse couple articles. Then I restart the app now it constantly crashes.

I tracked this issue down to huge articles I added recently. Deleting those articles from the server makes the app stable again. Please see the link below for the article list, I do not know which one causing it, but by removing those from my instance I was able to make the app work properly again.  beware, some of those articles are very large.

App logs

https://paste.debian.net/hidden/442fe10b/

Url list (use `wallabagapp` as the password)

https://bin.privacytools.io/?bf06ba86a3e2cd6d#xxek7y9/M5XBnhclOb1qANzznvUHMRBLR4N6L31JOQY=

**Comment by di72nn** [comment]
For searchability: `java.lang.IllegalStateException: Couldn't read row 0, col 0 from CursorWindow`.

Yeah, this looks exactly like #413, except this time there's a bit more logs available.

Unfortunately, I don't think there's much can be done until recent changes get released.

Were these large articles near each other in the lists? There's a chance that it won't crash if they are dispersed a little.

**Comment by gerroon** [comment]
Yeah they were added sequentially.

**Comment by di72nn** [comment]
Mostly likely fixed with #874.
