### ISSUE TITLE
Missing 301 redirect handling?

### ISSUE THREAD

**Issue by tcitworld** [wallabag/android-app#899]
Received through Google Play email contact.

Maybe related to #277, but it's probably Chrome doing something odd.

> Hello,
>
> First of all thank you for your app & happy new year ;)
>
> I'd like to report a bug on Android wallabag application.
>
> Once you search e.g. In Chrome Android browser in Google, Google seems to add /wrap real URL with their Google url.
> 
> So that url e.g.:
https://databox.com/google-my-business-seo
>
> Is wrapped too :
https://www.google.com/url?sa=t&source=web&rct=j&url=https://databox.com/google-my-business-seo&ved=2ahUKEwiP-eu9x-LmAhVVxMQBHdRDDMwQFjABegQIAhAB&usg=AOvVaw1aBaNZBAs1MvqxLus1ZJGa
>
> ![image](https://user-images.githubusercontent.com/2197836/71785941-e9944700-3005-11ea-8b69-46d4f1c1b932.png)
>
> Using context menu in Google search and "share link" - > "wallabag" then wallabag application cannot read title nor article its just saying "url" (see second & 3rd attachment). 
>
> I assume it might not follow the http 301 redirect? 
>
> Could you fix it? 
>
> ![image](https://user-images.githubusercontent.com/2197836/71785959-07fa4280-3006-11ea-808d-901f0912a591.png)
> ![image](https://user-images.githubusercontent.com/2197836/71785961-0d578d00-3006-11ea-8c88-67852c1a7af5.png)

**Comment by di72nn** [comment]
That's actually HTTP 200: google serves a web page with a redirecting script.
So no, I would rather not have a redirection resolver in the app - the server should handle it.

**Comment by tcitworld** [comment]
@di72nn Do they at least have a fallback `<meta>` redirection that we can try to handle in server ?

**Comment by di72nn** [comment]
Yes: `<meta content="0;url=https://databox.com/google-my-business-seo" http-equiv="refresh">`.

**Comment by tcitworld** [comment]
If I read https://github.com/j0k3r/graby/issues/198 properly, it seems meta refresh is already handled. Will investigate.

**Comment by mwoz123** [comment]
Hello everyone. 

> it's probably Chrome doing something odd

I noticed exactly same results on Opera (mobile).

With Firefox mobile I was also not able to read the article - for unknown for me reason (I'm not German speaking/reading person) some German text where instead of article : 
![Screenshot_20200116-191639](https://user-images.githubusercontent.com/4487025/72553112-78bc1d00-3898-11ea-8316-6aea823ec00c.png) 


With Dolphin browser after selecting "wallabag", popups "added" as usual, but no new article is in wallabag.

**Comment by di72nn** [comment]
The original issue has nothing to do with the browser: the problem is that wallabag server doesn't follow google's redirection for some reason.

> but no new article is in wallabag

Isn't it a wallabag error notification icon I see on your screenshot?

**Comment by mwoz123** [comment]
ok should I then create issue on https://github.com/wallabag/wallabag ? 
or not necessarily as it's already reported, and you did a quick analysis here? 

>Isn't it a wallabag error notification icon I see on your screenshot?

Might be, not sure. I don't know German.

**Comment by di72nn** [comment]
> ok should I then create issue on https://github.com/wallabag/wallabag ?

You probably should, if there isn't one for that.

> > Isn't it a wallabag error notification icon I see on your screenshot?
> 
> Might be, not sure. I don't know German.

I meant the triangle with an exclamation mark in the status bar.

**Comment by mwoz123** [comment]
Server issue created: https://github.com/wallabag/wallabag/issues/4259 

I assume this clilent ticket should be closed then?

**Comment by di72nn** [comment]
> With Dolphin browser after selecting "wallabag", popups "added" message as usual, but no new article is in wallabag.

Can you retry that and check whether there will be an error notification? There still might be a different issue to deal with.

**Comment by mwoz123** [comment]
Great thanks for resolving in such short time issue!! You're great Guys:) 


> Can you retry that and check whether there will be an error notification? There still might be a different issue to deal with.

There might be something wrong but with that browser itself. 
Just a disclaimer : I'm not using it daily, even rarely this browser - just installed to test this case;)

I installed it again and after few more tests its share via function looks  @strange. 

Most of the context menu displays data:image/png.. As link : 

![Screenshot_20200123-222709](https://user-images.githubusercontent.com/4487025/73025334-b2100200-3e2f-11ea-985a-638b5397854c.png)

But now for those 6 articles I checked now (in Google search results) 
- 2 said "application cannot handle this link" (might be it tried to pass this, "data:image.." as link
- 4 were successfully added to wallabag

**Comment by di72nn** [comment]
Ok then, you may create a new issue if you ever encounter it again.
