### ISSUE TITLE
Doesn't work in Google Translate

### ISSUE THREAD

**Issue by Agrotsa** [wallabag/android-app#900]
Visit whatever page and use your browsers addon to translate web pages or do it manually in Gtranslate website. Now add the translated page to your Wallabag. Nothing is saved. Well, just a few inutile lines from Google and read time estimation, not a word from the article.

I'm using Wallabag 2.3.0 from Fdroid. Server version, 2.3.3 (Framabag)

# Your experience with wallabag Android app
Have you had any luck using wallabag Android app before?
I'm a recent user, but no, Google Translated pages have never worked in these few weeks I'm using Framabag, sorry.

In case it could be of any help or give some ideas, there's a nice open source Firefox complement to save pages that does work in Gtranslated pages. Maybe you could check what mechanisms it uses to be able to read Gtanslated pages and perhaps reproduce it for WB? Just a suggestion.
You can check its code here:
https://github.com/gildas-lormeau/SingleFileZ

**Comment by Strubbl** [comment]
This issue is a problem with the wallabag server. The Android app does not crawl any website you add via the app. It is done by the server and the app just syncs with the server.

Can you please open an issue in wallabag server https://github.com/wallabag/wallabag/ ?
