### ISSUE TITLE
share sites to wallabag from firefox in android - no poster image.

### ISSUE THREAD

**Issue by GitJamz** [wallabag/android-app#902]
Hi,
It seems that the wallabagger addon doesnt work for firefox (fennec) right? I cant click check when I type my url. Nothing happens.
So I guess the way people do it is when browsing in firefox, click "share" and pick wallabag app.
When I do that the main image that becomes the "poster" of the article does not follow.
Does anyone else have this problem? Is there a workaround?

**Comment by di72nn** [comment]
Hi,

> It seems that the wallabagger addon doesnt work for firefox (fennec) right? I cant click check when I type my url. Nothing happens.

You need to ask here: https://github.com/wallabag/wallabagger.

> When I do that the main image that becomes the "poster" of the article does not follow.
Does anyone else have this problem? Is there a workaround?

Saving a URL via the app is equivalent to adding a URL via wallabag web UI. So if the web UI doesn't show the image, you should address https://github.com/wallabag/wallabag.
If the web UI shows the image, but the Android app doesn't, please provide an example.

**Comment by GitJamz** [comment]
@di72nn Hey m8. Thanks for responding. You were totally right, I was in the wrong place.
https://github.com/wallabag/wallabagger/issues/179
Apparently this issue was right in top of the issues there and confirmed that others have same problem.

**Comment by prcmt** [comment]
@GitJamz, since it looks like you are using the app, can you give any examples of articles that have don't have an image when saved via the share action? I tried a couple of pages just now and images were fetched fine.

**Comment by GitJamz** [comment]
@prcmt Well none were.. I tried couple different. But the exact same was saved with the image when saved through the wallabagger extension in firefox on my desktop.
For example: 
https://www.sweclockers.com/nyhet/28872-silverstone-fardigstaller-kompakta-chassit-sugo-sg14
Also if you want to test this and tell me if you can clip this site either with share function in app or with the wallabagger extension in desktop:
https://www.sweclockers.com/marknad/178740-lg-55-oled-b9
I am unable to get this last link to work at all. Fetching error nomatther what I do.. On all the articles in this forum which is under the /marknad for example

**Comment by prcmt** [comment]
**Note:** both of these pages redirect to separate mobile versions so Wallabag will be seeing different markup on phones.

That said, the first page is fetched fine with images in both cases for me (desktop + desktop version and Android app + mobile version)

![Screenshot_2020-01-09 Unread entries – wallabag](https://user-images.githubusercontent.com/59378788/72085333-0928b980-32fd-11ea-9b50-978246052c48.png)

The mobile version of the second page is again fine for me, but the desktop version does fail to fetch (f43.me fails too).

**Comment by GitJamz** [comment]
> **Note:** both of these pages redirect to separate mobile versions so Wallabag will be seeing different markup on phones.
> 
> That said, the first page is fetched fine with images in both cases for me (desktop + desktop version and Android app + mobile version)
> 
> ![Screenshot_2020-01-09 Unread entries – wallabag](https://user-images.githubusercontent.com/59378788/72085333-0928b980-32fd-11ea-9b50-978246052c48.png)
> 
> The mobile version of the second page is again fine for me, but the desktop version does fail to fetch (f43.me fails too).

AHh your your right. Its a difference between mobile version and desktop version in the first example. The desktop version also fetched the email on my android with the share function, correct.

However in example 2, the desktop site that refused to fetch. If you go in to this forum and chose basically any forum thread on the right side you will get the same problem. It just wont clip it with the wallabagger extension. This is a big issue... You know what is wrong?
The same site if you clip their "articles" which is not a forum thread but more of a news article, then everything is fine..

**Comment by GitJamz** [comment]
*misclicked on close and commend instead of comment :D

**Comment by prcmt** [comment]
Wallabag uses the same parsing backend as f43.me so you can use their test tool at [f43.me/feed/test](https://f43.me/feed/test) to check these pages. Looks like it also fails to parse them.

This isn't particularly surprising to me since these pages are forum threads, and Wallabag and the underlying parse library [graby](https://github.com/j0k3r/graby) are designed to extract articles.

**Comment by GitJamz** [comment]
> Wallabag uses the same parsing backend as f43.me so you can use their test tool at [f43.me/feed/test](https://f43.me/feed/test) to check these pages. Looks like it also fails to parse them.
> 
> This isn't particularly surprising to me since these pages are forum threads, and Wallabag and the underlying parse library [graby](https://github.com/j0k3r/graby) are designed to extract articles.

Ok I see m8..
But I mean these days information can come a lot from forum threads as well, and also reddit. I have learned so much by good forum threads and reddit subs over the last months that Im really sad that wallabag has problems clipping them.. Could this not be fixed you think?

**Comment by prcmt** [comment]
Maybe. Feel free to give it a go. 😊

**Comment by GitJamz** [comment]
I havent done any type of coding in my life. Just getting this container running took me 3 days.. about 12 hours spent...

You mean wallabag will not be able to clip forumposts or resditposts unless someone like me fix it?
Damn this project is abandoned or what..?

**Comment by prcmt** [comment]
I'm just a rando like you ^^

If you take the wallabag.it front page you'll see the word article in most sentences, so I think it's safe to say that that's the goal of the project. I don't know how much work it would be supporting forum threads etc. but I imagine it'll be a lot unless there's an existing tool out there like graby.

**Comment by di72nn** [comment]
> You mean wallabag will not be able to clip forumposts or resditposts unless someone like me fix it?
> Damn this project is abandoned or what..?

It's not abandoned, but I guess the priorities are different.
There was a brief discussion of saving comment threads here: wallabag/wallabag#3644
