### ISSUE TITLE
Self-hosted instance - application always tries to connect port 80 even if HTTPS or port 443 is manually specified

### ISSUE THREAD

**Issue by Maxiride** [wallabag/android-app#911]
**TL;DR**
Apps tries to connect on port 80 regardless of the scheme specified in the settings, be ut https://... or port :443

***

I'm running a self-hosted instance of Wallabag with Docker.

The instance is served on the WAN using Caddy to establish a reverse proxy from the Docker host. As of now I can use without issues wallabag from the browser **and** the internet.

I wanted to try the android app but upon entering the public URL and the credentials I get the error:

```
Unknown error: failed to connect to wallabag.mydomain.dev
```

I'd love to update with more debugging infos but it's all I have now.

**Comment by Strubbl** [comment]
Sounds like a web server configuration mistake. Can you check what redirections you have, e.g. with `curl -I wallabag.mydomain.dev`?

**Comment by Maxiride** [comment]
> Sounds like a web server configuration mistake. Can you check what redirections you have, e.g. with `curl -I wallabag.mydomain.dev`?

Now the cause it is more clear, it gives me connection refused on port 80.
`curl: (7) Failed to connect to wallabag.mydomain.dev port 80: Connection refused
`
I had only the external port 443 forwarded and not also the 80.

Oddly enough, however, I noticed that the application tries to connect to port 80 also if the URL specified in the configuration is `https`, maybe this is something that should be fixed? Or does the development team _assume_ that every webserver has a redirect 80 -> 443 for SSL connections?

I fixed my case by adding the port 80 forwarding rule and I am marking the issue as closed.

***

> Also, what does you webserver and caddy's error log say?

Nothing to report here as the connection was previously blocked at firewall level and never reached the webserver.

**Comment by Strubbl** [comment]
> Oddly enough, however, I noticed that the application tries to connect to port 80 also if the URL specified in the configuration is `https`, maybe this is something that should be fixed? Or does the development team _assume_ that every webserver has a redirect 80 -> 443 for SSL connections?

No, we should check this. if https is defined it should not check port 80 at first.

**Comment by Maxiride** [comment]
> 
> 
> > Oddly enough, however, I noticed that the application tries to connect to port 80 also if the URL specified in the configuration is `https`, maybe this is something that should be fixed? Or does the development team _assume_ that every webserver has a redirect 80 -> 443 for SSL connections?
> 
> No, we should check this. if https is defined it should not check port 80 at first.

Oh ok so I've tried the following without success to use https, in the configuration wizard I've set:

- domain.tld:443 — no success
- https://domain.tld:443 — no success
- https://domain.tld — no success

In all these cases, upon checking the firewall logs I found that the application was always trying to connect to the public ip on port 80.

If I can provide anything more, let me know.

**Comment by di72nn** [comment]
Trying both protocols (and also checking for redirects) is a feature of the configuration wizard (IIRC incorrect protocol or the lack thereof was a common problem in manual configuration).
So, for example, if user enters HTTP, but the app discovers that HTTPS is available, the app suggests to change URL to an HTTPS variant.

Do I understand correctly, that the app fails with `Unknown error` if you have wallabag on HTTPS-only, but somehow works if there is a redirect from HTTP to HTTPS?

**Comment by Maxiride** [comment]
> Do I understand correctly, that the app fails with `Unknown error` if you have wallabag on HTTPS-only, but somehow works if there is a redirect from HTTP to HTTPS?

Yes that's correct.
My webserver (Caddy) was exposing Wallabag on port 443 and HTTPS only.


> Trying both protocols (and also checking for redirects) is a feature of the configuration wizard (IIRC incorrect protocol or the lack thereof was a common problem in manual configuration).
> So, for example, if user enters HTTP, but the app discovers that HTTPS is available, the app suggests to change URL to an HTTPS variant.

The issue presented itself both using the wizard **and** the manual configuration.

If more infos are needed I'd be glad to provide anything.

**Comment by di72nn** [comment]
> The issue presented itself both using the wizard **and** the manual configuration.

The app suggests to test connection (when you go to the main screen) after manual changes in connection settings. Did the error happen during that connection test?

**Comment by Maxiride** [comment]
It **also**  happened there.

To recap the events in the order they happened:

- I installed the app (xD)
- on first startup I run the wizard, received the above mentioned errors (using the scheme https://wallabag.domain.tld)
- I then tried to change the settings again manually in settings menu, still same error
- from now on I tried the various combinations of scheme in the manual configuration setting page

If more debugging is needed I can revert the webserver changes and replicate error, if needed I can setup a new Wallabag instance for the devs to test.

**Comment by g33kdad** [comment]
I have wallabag running in docker behind a traefik firewall. I can't use https either. I believe there is a problem hard coded in the official wallabag/wallabag image on Docker Hub. I also have a bunch of art assets missing because they link to the wrong place.  I'm happy to share my docker-compose, if it would help.

Thanks,
M

**Comment by Maxiride** [comment]
@g33kdad 
> I also have a bunch of art assets missing because they link to the wrong place

Did you correctly set the `SYMFONY__ENV__DOMAIN_NAME` environment variable in your Wallabag docker installation? Or are the assets not displaying **only** in mobile?

**Comment by g33kdad** [comment]
I don't think I know what symphony is... I'll have to dig into it more.

M

**Comment by Maxiride** [comment]
> 
> I don't think I know what symphony is... I'll have to dig into it more. M

Check out [the wallabag docker readme](https://github.com/wallabag/docker), which is unrelated to the Wallabag Android app BTW.

**Comment by di72nn** [comment]
@Maxiride 

I double-checked the app code - it shouldn't try `http` if `https` is specified (unless there is an `https->http` redirection).

> if needed I can setup a new Wallabag instance for the devs to test

That may help, because I can't seem to reproduce it on my own.

@g33kdad
I can't say anything about your situation at the moment. We'll have to deal with the main issue first.
I know there were other people who had problems with docker installation (and who eventually solved their issues).

**Comment by Maxiride** [comment]
@di72nn 
Any private channel where I can share you the details?

**Comment by g33kdad** [comment]
Thanks

**Comment by g33kdad** [comment]
Thanks

**Comment by di72nn** [comment]
@Maxiride email me: `<my github nickname>@gmail.com`.

**Comment by di72nn** [comment]
> curl  -I https://wallabag.mydomain.dev
> **HTTP/1.1 302 Found**
> ...
> Location: **http**://wallabag.mydomain.dev/login

I should have noticed this earlier.
The app is following the redirect exactly as it is instructed to (unlike web browsers that don't usually downgrade to http).

#292
#622 
https://github.com/wallabag/wallabag/issues/2273#issuecomment-297864907

Since the 80 port is closed, this results in this error:
```
2020-02-06 20:03:53.848 12208-12401/fr.gaulupeau.apps.InThePoche.debug I/TestConnectionTask: IOException while trying to detect redirection; url: https://wallabag.example.com
    java.net.SocketTimeoutException: failed to connect to wallabag.example.com/remote_ip (port 80) from /local_ip (port 41100) after 10000ms

2020-02-06 20:04:04.469 12208-12401/fr.gaulupeau.apps.InThePoche.debug D/TestConnectionTask: Connection test: Exception
    java.net.SocketTimeoutException: failed to connect to wallabag.example.com/remote_ip (port 80) from /local_ip (port 41102) after 10000ms
```

**Comment by Maxiride** [comment]
> I should have noticed this earlier.

Welp, indeed I missed that too.

**Not an app issue then**
