### ISSUE TITLE
App crashes immediately if installed on SD card

### ISSUE THREAD

**Issue by norweeg** [wallabag/android-app#918]
Version 2.3.0 crashes immediately if it is installed on the SD card, but functions normally otherwise.  I have tried clearing cache, clearing data, uninstalling/reinstalling the app, and changing the database location in settings.  I don't know where to find logs, otherwise I would include them.  Device is a Samsung Galaxy Tab A with SD card, Android 9.

**Comment by di72nn** [comment]
> installed on the SD card

Are you talking about "adoptable storage"? Or is the old "move to SD card" still a thing?

**Comment by norweeg** [comment]
@di72nn move to SD card.  Samsung disables the adoptable storage feature, unfortunately

**Comment by di72nn** [comment]
So far I wasn't able to test it on an emulator and I don't have any modern device with an SD card.

It seems that you'll have to get "logcat" output.

**Comment by norweeg** [comment]
@di72nn how do I do that?

**Comment by di72nn** [comment]
I guess the simplest option is to use [Android Studio](https://developer.android.com/studio) on a PC.
You'll also need to [enable USB debugging](https://developer.android.com/studio/debug/dev-options#enable) on your Android device.
After that you apparently need to open any project (you can probably start a new project or "Import an Android code sample") in Android Studio and [open the logcat tool window](https://developer.android.com/studio/intro#the_user_interface).

**Comment by norweeg** [comment]
@di72nn I'm going to need a little more guidance here.  I am not an android developer, just a user trying to make a bug report.  I have usb debugging enabled, I have android studio, but the instructions for logcat aren't doing it.  There is no logcat where it says I should find it

**Comment by norweeg** [comment]
nevermind.  I found another way, ironically from the [pocket app's bug report instructions](https://help.getpocket.com/article/1073-retrieving-a-pocket-crash-log-on-android)

`------ SYSTEM LOG (logcat -v threadtime -v printable -v uid -d *:v) ------
--------- beginning of crash
02-13 20:03:59.235  5555   616   616 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xcbe80920 in tid 616 (auditd), pid 616 (auditd)
02-13 20:03:59.443  5555  8891  8891 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
02-13 20:03:59.444  5555  8891  8891 F DEBUG   : Build fingerprint: 'Verizon/gtasliteltevzw/gtasliteltevzw:9/PPR1.180610.011/T387VVRS2BSK2:user/release-keys'
02-13 20:03:59.444  5555  8891  8891 F DEBUG   : Revision: '5'
02-13 20:03:59.444  5555  8891  8891 F DEBUG   : ABI: 'arm'
02-13 20:03:59.444  5555  8891  8891 F DEBUG   : pid: 616, tid: 616, name: auditd  >>> /system/bin/auditd <<<
02-13 20:03:59.444  5555  8891  8891 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xcbe80920
02-13 20:03:59.444  5555  8891  8891 F DEBUG   :     r0  abe8091c  r1  07ffffff  r2  ffffffff  r3  80000000
02-13 20:03:59.444  5555  8891  8891 F DEBUG   :     r4  ac05c9c8  r5  abf007f0  r6  00000000  r7  cbe80918
02-13 20:03:59.444  5555  8891  8891 F DEBUG   :     r8  00000007  r9  abe8b008  r10 abf00040  r11 abf007f0
02-13 20:03:59.444  5555  8891  8891 F DEBUG   :     ip  00000031  sp  bea795e0  lr  ac05cb68  pc  ac013696
02-13 20:03:59.473  5555  8891  8891 F DEBUG   : 
02-13 20:03:59.473  5555  8891  8891 F DEBUG   : backtrace:
02-13 20:03:59.473  5555  8891  8891 F DEBUG   :     #00 pc 00078696  /system/lib/libc.so (je_arena_malloc_hard+738)
02-13 20:03:59.473  5555  8891  8891 F DEBUG   :     #01 pc 0008984d  /system/lib/libc.so (je_malloc+116)
02-13 20:03:59.473  5555  8891  8891 F DEBUG   :     #02 pc 000606c1  /system/lib/libc.so (strdup+12)
02-13 20:03:59.473  5555  8891  8891 F DEBUG   :     #03 pc 0000337d  /system/bin/auditd (parse_header_data+348)
02-13 20:03:59.473  5555  8891  8891 F DEBUG   :     #04 pc 00003479  /system/bin/auditd (do_filter+96)
02-13 20:03:59.473  5555  8891  8891 F DEBUG   :     #05 pc 000015fb  /system/bin/auditd (audit_to_misc+82)
02-13 20:03:59.473  5555  8891  8891 F DEBUG   :     #06 pc 0000138b  /system/bin/auditd (main+1074)
02-13 20:03:59.473  5555  8891  8891 F DEBUG   :     #07 pc 7020656c  <unknown>
02-15 10:05:19.362 10497 23443 23443 E AndroidRuntime: FATAL EXCEPTION: main
02-15 10:05:19.362 10497 23443 23443 E AndroidRuntime: Process: fr.gaulupeau.apps.InThePoche, PID: 23443
02-15 10:05:19.362 10497 23443 23443 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: couldn't map "/mnt/asec/fr.gaulupeau.apps.InThePoche-QqFWulganA7nxkhM/split_config.armeabi_v7a.apk!/lib/armeabi-v7a/libconscrypt_jni.so" segment 1: Permission denied
02-15 10:05:19.362 10497 23443 23443 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
02-15 10:05:19.362 10497 23443 23443 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1669)
02-15 10:05:19.362 10497 23443 23443 E AndroidRuntime: 	at org.conscrypt.NativeCryptoJni.init(NativeCryptoJni.java:28)
02-15 10:05:19.362 10497 23443 23443 E AndroidRuntime: 	at org.conscrypt.NativeCrypto.<clinit>(NativeCrypto.java:63)
02-15 10:05:19.362 10497 23443 23443 E AndroidRuntime: 	at org.conscrypt.NativeCrypto.checkAvailability(NativeCrypto.java:80)
02-15 10:05:19.362 10497 23443 23443 E AndroidRuntime: 	at org.conscrypt.Conscrypt.checkAvailability(Conscrypt.java:111)
02-15 10:05:19.362 10497 23443 23443 E AndroidRuntime: 	at org.conscrypt.Conscrypt.newProvider(Conscrypt.java:125)
02-15 10:05:19.362 10497 23443 23443 E AndroidRuntime: 	at fr.gaulupeau.apps.Poche.App.onCreate(App.java:28)
02-15 10:05:19.362 10497 23443 23443 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1158)
02-15 10:05:19.362 10497 23443 23443 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6304)
02-15 10:05:19.362 10497 23443 23443 E AndroidRuntime: 	at android.app.ActivityThread.access$1200(ActivityThread.java:241)
02-15 10:05:19.362 10497 23443 23443 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1807)
02-15 10:05:19.362 10497 23443 23443 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-15 10:05:19.362 10497 23443 23443 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
02-15 10:05:19.362 10497 23443 23443 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7156)
02-15 10:05:19.362 10497 23443 23443 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-15 10:05:19.362 10497 23443 23443 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
02-15 10:05:19.362 10497 23443 23443 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
02-15 10:24:29.558 10497  2311  2311 E AndroidRuntime: FATAL EXCEPTION: main
02-15 10:24:29.558 10497  2311  2311 E AndroidRuntime: Process: fr.gaulupeau.apps.InThePoche, PID: 2311
02-15 10:24:29.558 10497  2311  2311 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: couldn't map "/mnt/asec/fr.gaulupeau.apps.InThePoche-QqFWulganA7nxkhM/split_config.armeabi_v7a.apk!/lib/armeabi-v7a/libconscrypt_jni.so" segment 1: Permission denied
02-15 10:24:29.558 10497  2311  2311 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
02-15 10:24:29.558 10497  2311  2311 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1669)
02-15 10:24:29.558 10497  2311  2311 E AndroidRuntime: 	at org.conscrypt.NativeCryptoJni.init(NativeCryptoJni.java:28)
02-15 10:24:29.558 10497  2311  2311 E AndroidRuntime: 	at org.conscrypt.NativeCrypto.<clinit>(NativeCrypto.java:63)
02-15 10:24:29.558 10497  2311  2311 E AndroidRuntime: 	at org.conscrypt.NativeCrypto.checkAvailability(NativeCrypto.java:80)
02-15 10:24:29.558 10497  2311  2311 E AndroidRuntime: 	at org.conscrypt.Conscrypt.checkAvailability(Conscrypt.java:111)
02-15 10:24:29.558 10497  2311  2311 E AndroidRuntime: 	at org.conscrypt.Conscrypt.newProvider(Conscrypt.java:125)
02-15 10:24:29.558 10497  2311  2311 E AndroidRuntime: 	at fr.gaulupeau.apps.Poche.App.onCreate(App.java:28)
02-15 10:24:29.558 10497  2311  2311 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1158)
02-15 10:24:29.558 10497  2311  2311 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6304)
02-15 10:24:29.558 10497  2311  2311 E AndroidRuntime: 	at android.app.ActivityThread.access$1200(ActivityThread.java:241)
02-15 10:24:29.558 10497  2311  2311 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1807)
02-15 10:24:29.558 10497  2311  2311 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-15 10:24:29.558 10497  2311  2311 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
02-15 10:24:29.558 10497  2311  2311 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7156)
02-15 10:24:29.558 10497  2311  2311 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-15 10:24:29.558 10497  2311  2311 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
02-15 10:24:29.558 10497  2311  2311 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)`

**Comment by di72nn** [comment]
Native libraries are not available for some reason. There's a couple of reports like that in Google Play Console (all on Android 9 and 10).

Apparently there are some [App Bundle](https://issuetracker.google.com/issues/123070510) related [issues](https://issuetracker.google.com/issues/127691101) with native libraries when apps are moved to SD card.

@norweeg can you try installing the app from F-Droid? I'm pretty sure it should work ok.

**Comment by norweeg** [comment]
@di72nn the f-droid version works, but I'd rather not have two app stores...  The bug report you linked is a duplicate of a fixed bug.  https://issuetracker.google.com/issues/127691101

Can a similar fix work for the Google play version?

**Comment by di72nn** [comment]
Apparently [newer](https://github.com/google/bundletool/releases/tag/0.10.0) tools should be used to prepare next Google Play release.

Here are stacktraces for searchability.
Android 9:
```
java.lang.UnsatisfiedLinkError: 
  at java.lang.Runtime.loadLibrary0 (Runtime.java:1016)
  at java.lang.System.loadLibrary (System.java:1669)
  at org.conscrypt.NativeCryptoJni.init (NativeCryptoJni.java:28)
  at org.conscrypt.NativeCrypto.<clinit> (NativeCrypto.java:63)
  at org.conscrypt.NativeCrypto.checkAvailability (NativeCrypto.java:80)
  at org.conscrypt.Conscrypt.checkAvailability (Conscrypt.java:111)
  at org.conscrypt.Conscrypt.newProvider (Conscrypt.java:125)
  at fr.gaulupeau.apps.Poche.App.onCreate (App.java:28)
  at android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1158)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:6304)
  at android.app.ActivityThread.access$1200 (ActivityThread.java:241)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1807)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:7156)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:494)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:975)
```
Android 10:
```
java.lang.UnsatisfiedLinkError: 
  at java.lang.Runtime.loadLibrary0 (Runtime.java:1067)
  at java.lang.Runtime.loadLibrary0 (Runtime.java:1007)
  at java.lang.System.loadLibrary (System.java:1667)
  at org.conscrypt.NativeCryptoJni.init (NativeCryptoJni.java:28)
  at org.conscrypt.NativeCrypto.<clinit> (NativeCrypto.java:63)
  at org.conscrypt.NativeCrypto.checkAvailability (NativeCrypto.java:80)
  at org.conscrypt.Conscrypt.checkAvailability (Conscrypt.java:111)
  at org.conscrypt.Conscrypt.newProvider (Conscrypt.java:125)
  at fr.gaulupeau.apps.Poche.App.onCreate (App.java:28)
  at android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1190)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:6540)
  at android.app.ActivityThread.access$1400 (ActivityThread.java:220)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1883)
  at android.os.Handler.dispatchMessage (Handler.java:107)
  at android.os.Looper.loop (Looper.java:224)
  at android.app.ActivityThread.main (ActivityThread.java:7520)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:539)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:950)
```

**Comment by norweeg** [comment]
this is now resolved.  I accidentally moved my app to the SD card and didn't notice because the app is no longer crashing when moved to sd card
