### ISSUE TITLE
Remember position in partially read article

### ISSUE THREAD

**Issue by mkollaro** [wallabag/android-app#92]
Often, I decide to stop reading in the middle of a long article and look at something else (in wallabag). But when I go back to the long article, it opens it at the beginning, not in the middle. I guess it's not possible to have this synced with the server, but it would be nice if it was at least local on the phone.

**Comment by tcitworld** [comment]
We intend to sync it with the server in the future.

**Comment by tcitworld** [comment]
See https://github.com/wallabag/wallabag/issues/1336

**Comment by tcitworld** [comment]
Now available in latest builds (beta versions, click [here](https://play.google.com/apps/testing/fr.gaulupeau.apps.InThePoche) to test on Play Store - F-Droid to follow).
