### ISSUE TITLE
Move away from Google text-to-voice?

### ISSUE THREAD

**Issue by nicosomb** [wallabag/android-app#952]
Hello, 

Here is a mail I received from Frog: 

> is there a plan to move away from Google text-to- voice to a more privacy respecting provider of this service?

**Comment by tcitworld** [comment]
Pretty sure we don't use anything specific to a TTS engine. Any TTS engine should work, including the default Android TTS engine. User just needs to disable Google TTS or switch to a different engine in the Android Settings.

**Comment by di72nn** [comment]
That's correct: the app uses whatever is available in the system.
