### ISSUE TITLE
Incorrect app permissions on Android 10

### ISSUE THREAD

**Issue by RainCat1998** [wallabag/android-app#962]
Version: 220 (2.4.0-beta.1)
My phone is Samsumg S20+ with oneUI 2.1(Android 10). And the latest version doesn't require any permission (including usage of camera).
When I scan a QR code in the guide menu, It says "Sorry, the Android camera encountered a problem. You may need to restart the device.". But restarting the device does not help.
![Screenshot_20200429-225234_Knox Enrollment Servic](https://user-images.githubusercontent.com/36730607/80611360-1369f180-8a6d-11ea-8341-ddb2cb99c1f1.jpg)

**Comment by tcitworld** [comment]
Seems to be an issue with Knox Mobile Enrollment (I'm guessing your device is of your employer?), not with Android 10.

https://stackoverflow.com/questions/60313942/knox-enrollment-service-preventing-camera-access

**Comment by RainCat1998** [comment]
> Seems to be an issue with Knox Mobile Enrollment (I'm guessing your device belongs to your employer?), not with Android 10.
> 
> https://stackoverflow.com/questions/60313942/knox-enrollment-service-preventing-camera-access

No, my phone is not a contract phone. The problem is the app doesn‘t require any permission at all.
[](https://www.youtube.com/watch?v=NOhz8oDGFA4)

**Comment by di72nn** [comment]
wallabag app doesn't use camera by itself, it only asks some other app to scan a QR code (the system or the user decides which one). To the best of my knowledge, that doesn't require any permissions.
Can you try installing [Binary Eye](https://play.google.com/store/apps/details?id=de.markusfisch.android.binaryeye) and see if it makes any difference?

**Comment by RainCat1998** [comment]
> wallabag app doesn't use camera by itself, it only asks some other app to scan a QR code (the system or the user decides which one). To the best of my knowledge, that doesn't require any permissions.
> Can you try installing [Binary Eye](https://play.google.com/store/apps/details?id=de.markusfisch.android.binaryeye) and see if it makes any difference?

Yes, you're right. It works.

**Comment by di72nn** [comment]
I guess that's yet another Samsung quirk.
