### ISSUE TITLE
Connection test failed - wallabag service not found - check URL

### ISSUE THREAD

**Issue by ErikMonten** [wallabag/android-app#966]
# Issue Details
I'm using the official Docker image, but am not able to connect to the Android app. I get this error:

`Connection test failed - wallabag service not found - check URL`

# Steps to reproduce the issue
1. Run the connection wizard

# Environment details
- **wallabag app version**: 2.3.0 (219)
- **wallabag app installation source** (e.g. Gplay, F-Droid, manual): Gplay
- **Android OS version**: Version One UI 2.0 - Android version 10
- **Android ROM** (e.g. stock, LineageOS, SlimRom,…): Stock
- **Android hardware**: Samsung A40
- **wallabag server version**: 2.3.8 (from Docker)
- **Do you have Two-Factor-Authentication enabled?**: no

# Logs
## wallabag server
2020/05/01 08:58:05 [error] 247#247: *39 FastCGI sent in stderr: "PHP message: PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2636PHP message: PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2665" while reading response header from upstream, client: 192.168.0.254, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "wallabag.dsemo.com"

192.168.0.254 - - [01/May/2020:08:58:05 +0000] "GET / HTTP/1.1" 302 209 "-" "okhttp/4.2.2"

2020/05/01 08:58:05 [error] 247#247: *41 FastCGI sent in stderr: "PHP message: PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2636PHP message: PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2665" while reading response header from upstream, client: 192.168.0.254, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "wallabag.dsemo.com"

192.168.0.254 - - [01/May/2020:08:58:05 +0000] "GET / HTTP/1.1" 302 209 "-" "okhttp/4.2.2"

# Your experience with wallabag Android app
Till now I did not have any luck using wallabag Android app. I'm using it now via my chrome browser on my mobile, but in this way I can not save any web pages to Wallabag.

**Comment by Strubbl** [comment]
Are you typing the URL with https into the url field? because your http resolves to another site. 
I remember we had a strange issue like this. 

Would it be possible that you resolve wallabag URL on http to wallabag too?

**Comment by Strubbl** [comment]
it was issue #911 and you have the same issue. Please see:

```
$ curl -I https://wallabag.dsemo.com
HTTP/2 302 
server: nginx
date: Fri, 01 May 2020 10:23:40 GMT
content-type: text/html; charset=UTF-8
x-powered-by: PHP/7.3.11
set-cookie: PHPSESSID=b1e704d48cb36eae50ca299b9b593135; path=/; HttpOnly
cache-control: no-cache, private
location: http://wallabag.dsemo.com/login
strict-transport-security: max-age=15768000; includeSubdomains; preload
```

You are redirecting from https to http://wallabag.dsemo.com/login. Can you please fix that in your webserver's config.

**Comment by ErikMonten** [comment]
Thank you so much !! That solved my problem. It works perfect now on my mobile. Very much appreciated.
