### ISSUE TITLE
Synchronization error 500

### ISSUE THREAD

**Issue by Suncatcher** [wallabag/android-app#97]
I tried to sunchronize Wallabag and got following message. 

![screenshot_2015-10-20-18-58-37](https://cloud.githubusercontent.com/assets/6388034/10614344/658d0a10-7762-11e5-9d88-702e29330920.png)

I host Wallbag on Framabag. Token and ID was generated properly and seem to be correct.These are the settings I use

![settings](https://cloud.githubusercontent.com/assets/6388034/10614348/693a31b0-7762-11e5-840e-ef6cbd3b0d63.png)

**Comment by tcitworld** [comment]
Hi,
This shows issues on our side. It had problems yesterday, but it works right now. Can you try again ?

**Comment by Suncatcher** [comment]
The same result.

**Comment by tcitworld** [comment]
Hmm, your token is correct but feeds generation [failed](https://www.framabag.org/u/Suncatcher/?feed&type=home&user_id=1&token=NjQ1NzE4NjM2NTYyNjYz). You must have some kind of special character that causes problems. Can you try deleting your first entry and retrying ? Also, regenerating token could make changes too.

**Comment by Suncatcher** [comment]
> Can you try deleting your first entry and retrying ? Also, regenerating token could make changes too

What do you mean under "first entry"? You mean articles in my bag?

**Comment by tcitworld** [comment]
That's right.

**Comment by Suncatcher** [comment]
> Hmm, your token is correct but feeds generation failed. You must have some kind of special character that causes problems. Can you try deleting your first entry and retrying ? Also, regenerating token could make changes too.

Done that but it again [failed](https://www.framabag.org/u/Suncatcher/?feed&type=home&user_id=1&token=MzQ0MTc3Mzg1NTYyN2M2)

What am I doing wrong? And what special characters do you mean?

**Comment by tcitworld** [comment]
I just asked the Framabag admin to have a look at your account, the issue is on wallabag's side, not on the android app side.

**Comment by nicosomb** [comment]
There are some cyrillic characters in your entries. Maybe it's the problem.

**Comment by Suncatcher** [comment]
> There are some cyrillic characters in your entries. Maybe it's the problem.

And why that should be a problem? I thought most of the nowadays projects are implemented in Unicode. If Framabag is not, it's a great flaw. Don't you think so?
Pocket quite perfectly handles all types of characters.

**Comment by tcitworld** [comment]
We agree on this, but right now we have a bug. If we could be sure it's related to Cyrillic characters, we could work in order to resolve the issue. 

So could you try to delete the entry just to try if this changes anything ?

**Comment by Suncatcher** [comment]
> So could you try to delete the entry just to try if this changes anything ?

OK, but I have several hundreds of Cyrillic entries, it will take too much time to delete. If you contact Frababag admin, he will do this much faster and simpler, as he has direct access to database.

**Comment by tcitworld** [comment]
Can you give me a link to a Cyrillic entry so that I can test it myself on my own account ?

**Comment by Suncatcher** [comment]
Here they are:
https://www.framabag.org/u/Suncatcher/index.php?view=view&id=1013
https://www.framabag.org/u/Suncatcher/index.php?view=view&id=1012
https://www.framabag.org/u/Suncatcher/index.php?view=view&id=1008

**Comment by tcitworld** [comment]
Sorry for the delay, can you give me the original urls instead ?

**Comment by Suncatcher** [comment]
https://rufabula.com/articles/2015/10/21/economic-marathon
http://ttolk.ru/?p=21055
https://pieramoha.org/artykuly/zianon-pazniak-histarycznaje-niaszczascie-i-daroha-napierad

**Comment by tcitworld** [comment]
Thanks. Working on it.

**Comment by tcitworld** [comment]
Well, it's not (these) cyrillic entries that are causing your issue, so I think wallabag works properly with cyrillic characters. 

I think I'll have to go one by one through your entries to find which one is the culprit, if you allow me and **if they don't contain personal data**. Can you sent me your entries exported as json (through wallabag config panel - this *should* take a while) and sent them to me at tcit at tcit dot fr ?

**Comment by Suncatcher** [comment]
Okay, no problem. No personal data at all. But when I try to export to JSON, the page suddenly breaks loading.
![unbenannt](https://cloud.githubusercontent.com/assets/6388034/11234085/a821cd46-8dd5-11e5-9131-8111b40818ec.png)

**Comment by nicosomb** [comment]
I think it's the same problem. @Suncatcher, as a Framabag admin, can I send your database to @tcitworld (who is a wallabag admin too)?

**Comment by Suncatcher** [comment]
Yes, of course. Send it.

**Comment by Suncatcher** [comment]
Are there any updates about this issue?

**Comment by tcitworld** [comment]
I didn't find the time to finish it (I found the error, maybe there's more). Hope to find some time to do it before the end of the week.

**Comment by Suncatcher** [comment]
Ok, thanks.

**Comment by tcitworld** [comment]
Hi,
Terribly sorry for delay, but I didn't find a single reason why this happens. As I said, I thought I had, but I was mistaken. I'll do more work on this during my holidays next week.

**Comment by mlncn** [comment]
I'm receiving this error after importing some couple thousand articles from Pocket/ReadItLater.  I get the error "Error loading feed :Request unsuccessful; response code: 500, response message: Internal Server Error" for both Unread and Archived.  Favorites can still sync (and then those articles will also show up in Unread).

I'm at https://www.framabag.org/u/mlncn/

Could it be just sheer volume of articles that is the problem?

**Comment by Suncatcher** [comment]
Finally, after import having been done (see #198 ) I was able to reproduce the bug again

![photo_2016-02-26_10-00-51](https://cloud.githubusercontent.com/assets/6388034/13345517/62c34baa-dc70-11e5-8c07-a7dec123f75d.jpg)

But! 
Beforehand I intentionally tried to do this with reduced file (all the links except first 29 were deleted) and it worked! Therefore, I can make an assumption about possible causes of this bug:

1. It is a performance issue: for some reason server doesn't accept big files (more than N rows)

2.  Something wrong with my file, which is posted in issue #198

**Comment by Suncatcher** [comment]
Considering @mlncn report where he says about 2000+ articles, we can conclude that performance is a pitfall.

**Comment by mlncn** [comment]
Is there any workaround for this?  From the Android app side, could it start requesting only 20 articles at a time?

**Comment by Strubbl** [comment]
@mlncn This is not possible with wallabag v1, but with wallabag v2 it is. You can set the number of items in RSS feed in your Wallabag settings.

**Comment by mlncn** [comment]
The app and the server need to be using the same version, correct?  (I'm on framabag currently— eager to try the new app, not ready right now to switch to self-hosting) - sandstorm.io doesn't offer Wallabag yet it seems.

**Comment by Strubbl** [comment]
No, the latest app should work with both Wallabag main versions (v1 and v2). 

The problem with framabag is, that they are still using v1, which does not support limiting the number of items to request. You always get all in one call.

**Comment by Suncatcher** [comment]
> The problem with framabag is, that they are still using v1, which does not support limiting the number of items to request

But can you confirm this or deny? Is this bug connected with Framabag+Wallabag or Wallabag itself?

**Comment by mlncn** [comment]
Can confirm that i am using Framabag, and that the problem is too many items in the feed resulting in a 500 error (i can still refresh my favorites list, which is not so long).  I'm sorry i don't have time right now to try out an upgrade on my own server.

**Comment by Suncatcher** [comment]
So is there any update about this bug? When it gonna be fixed?

**Comment by di72nn** [comment]
I don't know much about current state of wallabag-server development, but I guess you may consider migrating to wallabag v2.

@tcitworld @nicosomb
Is https://v2.wallabag.org public?

**Comment by Suncatcher** [comment]
> Is https://v2.wallabag.org public?

It is an analog of Framabag but on v.2?

**Comment by tcitworld** [comment]
It is public, also hosted on Framasoft servers, but works on latest versions.

**Comment by Suncatcher** [comment]
You introduced it too late, I've already installed Wallabag on my AWS. 
Will report if this bug still exists soon.

**Comment by di72nn** [comment]
Legacy version is no longer supported.
