### ISSUE TITLE
Error 500 on wallabag.it

### ISSUE THREAD

**Issue by nicosomb** [wallabag/android-app#999]
Hello, 

One of wallabag.it user has this error with the android app. 

![Screenshot_20200617-235452_wallabag](https://user-images.githubusercontent.com/121870/84993828-15d1f900-b14a-11ea-9f86-4af59ab82a42.jpg)

Could you tell me what happened please?

**Comment by tcitworld** [comment]
`HTTP 500`. You tell us. :p
